"""Editorial copy and metadata for the 22-26 August 2026 release run."""

from __future__ import annotations

import html


def picture(root: str, name: str, alt: str) -> str:
    return f'''<figure class="media article-inline-image"><picture><source type="image/webp" srcset="{root}/{name}-640.webp 640w, {root}/{name}-960.webp 960w, {root}/{name}.webp 1536w" sizes="(max-width: 760px) calc(100vw - 2rem), 760px"><img src="{root}/{name}.jpg" width="1536" height="1024" loading="lazy" decoding="async" alt="{html.escape(alt)}"></picture></figure>'''


TREND_SOURCE = "https://newsroom.pinterest.com/en-ca/news/summer-trend-report-2026/"


RUNNER_ROOT = "/assets/images/blogs/fashion/runner-flats-outfit"
RUNNER_BODY = f'''<div class="article-layout"><aside class="article-aside"><p class="kicker">The field guide</p><ol><li><a href="#answer">The short answer</a></li><li><a href="#definition">What runner flats are</a></li><li><a href="#proportion">The proportion rules</a></li><li><a href="#outfits">Seven outfit formulas</a></li><li><a href="#fit">How to judge the fit</a></li><li><a href="#buy">What is worth buying</a></li></ol><button class="copy-link" data-copy-link type="button">Copy link</button></aside><div class="article-body">
<p class="article-opening">Runner flats are easiest to style when the shoe is treated as a flat first and a trainer second. Keep the trouser hem precise, expose a little ankle or sock, and repeat one technical detail elsewhere in the outfit. The most convincing pair has a low profile, a recognisable flat-shaped opening and enough sole to feel intentional, not a ballet pump placed on foam.</p>
<p>The name sounds like two incompatible shoes pushed together by a search bar. In person, the idea is more useful. A runner flat borrows mesh, suede panels, elastic, tread and cushioning from a trainer, then removes the bulky upper and high collar. What remains sits close to the foot like a ballet flat or Mary Jane. It solves a real styling problem: how to keep the lightness of a flat when the rest of an outfit needs more texture and grip.</p>
<div class="summary-box" id="answer"><p class="kicker">The useful answer</p><h2>Use one sleek line and one technical interruption</h2><p>Pair runner flats with full-length tailored trousers, a clean midi skirt or fluid capris. Let either the shoe or the sock provide the sporty detail, not both at maximum volume. Choose a colour that connects to the outfit, check that the heel stays secure, and avoid a hem that collapses across the shoe. If the sole becomes chunky, style it as a trainer. If the sole is almost invisible, style it as a delicate flat.</p></div>
<section id="definition"><h2>What exactly is a runner flat?</h2><p>The category includes several related shapes. Some are ballet runners with a rounded opening, mesh vamp and technical sole. Some use a Mary Jane strap across the instep. Others look like slim trail shoes cut below the sides of the foot. Pinterest grouped runner flats, runner Mary Janes, runner mules, wedge runners and ballet runners together in its Summer 2026 report. Search interest for “runner flats outfit” rose 432 per cent, while “runner Mary Janes outfit” rose 267 per cent.</p><p>Those numbers describe momentum on Pinterest, not a guarantee of Google volume or proof that every version will last. The more interesting evidence is visual. After years of substantial retro trainers, the eye is ready for a shoe that takes up less vertical space. At the same time, many people do not want to return to an unstructured pump with a paper-thin sole. The hybrid keeps the foot close to the ground without erasing every practical feature.</p><h3>The three details that make the shoe legible</h3><p>First, the opening should clearly expose the top of the foot. Second, the upper needs at least one technical material, usually mesh, ripstop, suede panelling or elastic webbing. Third, the sole needs a visible relationship to movement, through tread, a shaped heel or a slightly raised toe. Without the first detail it is simply a trainer. Without the other two it is an ordinary flat.</p><p>That clarity matters when shopping from photographs. A product description can use a new trend name for an old object. Ignore the label and examine the silhouette. The useful pair should earn its hybrid status from construction.</p></section>
{picture(RUNNER_ROOT, "runner-mary-jane-styling", "Black leather and mesh runner Mary Janes with ivory socks and a chocolate satin skirt")}
<section id="proportion"><h2>The proportion rules are simpler than the shoe</h2><p>A runner flat is visually busy at the lowest point of the outfit. Mesh, seams and tread divide a small area into several parts. The clothing above it needs a calmer outline or the whole look becomes granular. That does not mean everything must be minimal. It means one garment should establish a long, uninterrupted line.</p><h3>Give the shoe a clean exit</h3><p>The hem should finish decisively above the shoe or pass it cleanly. A midi skirt can end between lower calf and ankle. A full trouser can skim the top without pooling. Cropped trousers need enough space to reveal the ankle rather than stopping at the widest part of the calf by accident. A weak two-centimetre gap often looks like a tailoring error.</p><p>This is the same discipline that makes <a href="/blogs/fashion/jelly-kitten-heels/">jelly kitten heels</a> easier to wear. Novelty at the foot benefits from restraint immediately above it. A narrow ribbed sock can bridge the gap, particularly with Mary Jane versions, but a thick scrunched athletic sock changes the shoe into a sportier proposition.</p><h3>Match visual weight, not literal colour</h3><p>A pale mesh shoe can still feel substantial if the sole is dark and deeply cut. A black pair may read lightly when the topline is open. Judge the total weight from a standing distance. Then give the outfit a corresponding anchor: a dark belt, structured bag, dense knit or crisp collar. Exact colour matching is less important than preventing the shoes from looking detached.</p><p>When in doubt, repeat one material. Suede trim can connect to a brushed leather bag. Silver eyelets can echo a watch. Nylon in the shoe can meet a fine windbreaker, but only if the rest of the outfit remains tailored. The repetition should be discoverable, not announced.</p></section>
<section id="outfits"><h2>Seven runner flats outfits that work in real life</h2><h3>1. Charcoal trousers, fine knit, taupe runner flats</h3><p>This is the cleanest entry point because the trouser supplies length and the shoe supplies texture. Choose a hem that nearly reaches the upper but does not catch under the heel. A slim knit keeps the waist clear. Taupe or stone shoes soften charcoal without producing a stark white punctuation mark.</p><h3>2. Navy midi skirt, sheer sock, burgundy pair</h3><p>A pleated or straight navy skirt gives burgundy enough quiet space to feel rich rather than collegiate. Use a fine charcoal sock, not an opaque black one, so the transition remains light. The outfit can take a plain cotton shirt or a compact cardigan. Avoid adding a varsity jacket unless the explicit goal is sports nostalgia.</p><h3>3. Dark denim, white shirt, black runner Mary Janes</h3><p>Keep the jeans straight and full length, with no heavy distressing around the hem. The strap gives the shoe definition under denim. A white shirt adds an ordinary, grown-up counterweight. This formula is especially good for testing whether the shoe belongs in your wardrobe because it uses pieces most people already understand.</p><h3>4. Fluid capris, longline blazer, low-profile runners</h3><p>The exposed lower leg makes the shoe visible, so reduce the number of colours. Cream capris, a tobacco blazer and a brown-black shoe are enough. The blazer should cover the waistband or finish clearly above it. An uncertain hip-length jacket can divide the outfit into too many equal sections. Our forthcoming flowy-capri guide will go deeper on hem placement, but the immediate rule is to preserve one long vertical line.</p><h3>5. Slip dress, dry wool cardigan, grey mesh flats</h3><p>The contrast is useful: liquid fabric, fuzzy knit, technical mesh. Keep the dress simple and the cardigan slightly substantial. A tiny cardigan plus tiny shoe can make the body of the dress feel visually unsupported. Grey works better than bright white when the dress is black, olive or chocolate.</p><h3>6. Khaki field trousers, silk blouse, cream runner flats</h3><p>Utility clothes and technical footwear share a language, so the blouse needs to interrupt it. Silk, fine cotton voile or a soft draped knit prevents the outfit becoming literal gear. The same contrast drives our guide to <a href="/blogs/fashion/khaki-coded-style/">wearing khaki without the costume</a>.</p><h3>7. Black column skirt, oversized shirt, red pair</h3><p>A coloured runner flat works when the rest of the outfit creates a single field. Black from waist to ankle gives the shoe permission to be noticed. Let an oversized ivory or pale-blue shirt provide volume at the top. Do not add a matching red bag. One red object is a decision; two can look like a set.</p></section>
{picture(RUNNER_ROOT, "runner-flats-city", "Burgundy technical runner flats with charcoal socks and a navy pleated skirt stepping from a wet city curb")}
<section id="fit"><h2>The fit test matters more in a hybrid shoe</h2><p>A runner flat may look cushioned while behaving like a loose pump. The low topline removes some of the structure that holds a conventional trainer to the foot. A strap, elastic binding or well-shaped heel can help, but none compensates for the wrong length or width.</p><p>Try both shoes with the socks or tights you intend to wear. Walk on a clean indoor surface, turn sharply and climb a few steps. The heel should not lift dramatically, the edge should not cut across the toes and the widest part of the foot should sit within the widest part of the sole. Do not assume mesh will stretch into the correct shape.</p><p>Guy’s and St Thomas’ NHS Foundation Trust advises roughly one centimetre between the longest toe and the end of a shoe, enough width across the ball of the foot and a toe box that does not squeeze. Its podiatry guidance also notes that slip-ons may force the toes to grip when they lack a fastening. A runner Mary Jane can therefore be easier to secure than a completely open version, provided the strap lies flat and does not press.</p><h3>Do not buy the fantasy of running in them</h3><p>“Runner” describes the visual vocabulary, not necessarily the intended activity. Unless a manufacturer explicitly designs and tests the shoe for running, treat it as fashion footwear. Use an actual activity-specific shoe for training. The hybrid may be comfortable for a commute, gallery day or dinner, but comfort is personal and not visible in a campaign photograph.</p></section>
<section id="buy"><h2>What to inspect before buying</h2><div class="article-table-wrap" role="region" aria-label="Runner flats buying checklist" tabindex="0"><table class="article-visual-table"><thead><tr><th>Detail</th><th>Promising sign</th><th>Warning sign</th></tr></thead><tbody><tr><td>Heel</td><td>Shaped cup or secure elastic edge</td><td>Large lift at every step</td></tr><tr><td>Toe box</td><td>Follows the foot without pressing</td><td>Decorative taper that crowds toes</td></tr><tr><td>Sole</td><td>Even attachment and useful tread</td><td>Heavy sole on a flimsy upper</td></tr><tr><td>Strap</td><td>Adjustable and flat against the instep</td><td>Rigid edge or purely decorative buckle</td></tr><tr><td>Mesh</td><td>Supported at high-friction areas</td><td>Open mesh rubbing directly at the toe</td></tr></tbody></table></div><p>Look at the side profile before the front. The profile reveals whether the sole has been balanced with the upper. Check the inside for rough seams, particularly where technical panels meet soft binding. Flex the forefoot gently, then twist only as much as the product is meant to allow. A shoe can be soft without feeling structurally vague.</p><p>Colour should be the final decision. Black and dark brown integrate most easily with tailoring. Stone and grey make the technical construction visible without the force of white. Burgundy, faded blue and olive can work as contained accents. Highly reflective silver is more demanding because every seam becomes brighter.</p><p>If you already own <a href="/blogs/fashion/summer-loafers-outfit-guide/">summer loafers</a>, ballet flats and trainers, identify the actual gap. Runner flats make sense when you want the exposure of a flat with the surface interest of a trainer. They are less useful if every ordinary day already ends in loafers. A trend earns space by solving a repeated outfit, not by producing a new category in the wardrobe spreadsheet.</p></section>
<section class="article-faq"><h2>Runner flats questions</h2><h3>Are runner flats comfortable?</h3><p>Some are, but the appearance of cushioning does not guarantee fit. Check length, width, heel security, strap pressure and how the shoe behaves during a real indoor walk.</p><h3>What trousers work with runner flats?</h3><p>Full-length tailored trousers, straight jeans and deliberate mid-calf crops work best. Avoid a hem that bunches across the upper or stops in an accidental gap.</p><h3>Can runner flats be worn to work?</h3><p>Yes, when the workplace allows fashion trainers or flats. Choose a dark low-profile pair and combine it with clear tailoring rather than overt sportswear.</p></section>
<section class="source-note"><h2>Sources and image note</h2><p>Search-growth figures come from Pinterest’s <a href="{TREND_SOURCE}">Summer 2026 Trend Report</a>, published 26 May 2026 and based on global Pinterest search behaviour. Footwear-fit guidance was checked against <a href="https://www.guysandstthomas.nhs.uk/health-information/choosing-shoes-reduce-foot-pain">Guy’s and St Thomas’ NHS Foundation Trust</a>, last reviewed in April 2025. The styling analysis and all photographs are original by.foro editorial work. The shoes shown are fictional, unbranded designs created for illustration.</p></section>
<section><h2>The strange shoe succeeds when the outfit stays calm</h2><p>Runner flats do not need a theory once they are on the foot. They need a clean hem, a secure fit and one reason to belong with the clothes above them. Let the technical detail remain small. Let the long line come from the garment. The hybrid looks modern when neither half is asked to perform too loudly.</p></section><div class="article-end"><span>End</span><p>Published by by.foro Editorial on 22 August 2026. For corrections, contact <a href="mailto:hello@byforo.com">hello@byforo.com</a>.</p></div></div></div>'''


PONCHO_ROOT = "/assets/images/blogs/fashion/sheer-poncho-outfit"
PONCHO_BODY = f'''<div class="article-layout"><aside class="article-aside"><p class="kicker">The modern poncho</p><ol><li><a href="#answer">The short answer</a></li><li><a href="#fabric">Choose the right sheer fabric</a></li><li><a href="#balance">Balance volume</a></li><li><a href="#formulas">Eight outfit formulas</a></li><li><a href="#occasions">Beach, city and evening</a></li><li><a href="#care">Care and storage</a></li></ol><button class="copy-link" data-copy-link type="button">Copy link</button></aside><div class="article-body">
<p class="article-opening">A sheer poncho looks modern when it is used as a controlled top layer, not as a theme. Keep the layer underneath opaque and close to the body, let the lower half provide one clean line, and choose transparency that reveals movement rather than every detail. The poncho should change the silhouette without making the outfit harder to understand.</p>
<p>The return of the poncho is easy to dismiss because the garment carries too many memories: crochet at festivals, fleece on a sofa, plastic in the rain, beading over an evening dress. The sheer version can escape all four. In organza, chiffon, voile or an open fine knit, it behaves more like portable atmosphere. It softens a shoulder, catches light and creates width without the weight of a jacket.</p>
<div class="summary-box" id="answer"><p class="kicker">The modern formula</p><h2>One transparent plane over one complete outfit</h2><p>Dress fully underneath first. A tank and trousers, column dress, swimsuit or fitted knit with a straight skirt should already work alone. Add the poncho as the final plane. Keep jewellery close to the body, avoid a second floating layer and show either the wrist or ankle so the silhouette retains an edge.</p></div>
<section id="fabric"><h2>The fabric decides whether it looks elegant or theatrical</h2><p>Pinterest reported a 1,093 per cent rise in searches for “sheer poncho outfit” in its Summer 2026 trend report. That rapid growth makes sense visually, but the search phrase covers very different objects. A crochet square, silk-organza cape and polyester beach cover-up may all be sold under the same name. The material determines what the garment can do.</p><h3>Organza holds an outline</h3><p>Organza is useful when you want architecture. It stands away from the body, keeps a crisp edge and photographs with clear shadows. Choose a version with enough softness to move at the sides. Very stiff organza can resemble gift wrapping, particularly in pale colours. Smoke, ink, sand and softened olive are easier than optic white for everyday wear.</p><h3>Chiffon follows the body</h3><p>Chiffon falls closer, so it works over a column dress, sleeveless shell or slim trousers. The edge should be finished cleanly because the hem is constantly visible. A poorly cut chiffon poncho often twists toward one side and reveals the shortcut. Check the garment while standing and walking, not only on a hanger.</p><h3>Fine knit offers texture rather than transparency</h3><p>An open knit can be easier during the day because the surface breaks up the body without producing a glossy veil. Look for a stable neckline and an edge that does not curl. Large crochet motifs read more nostalgic and may be exactly right at the beach, but they require a quieter outfit elsewhere.</p><p>Fibre content matters for comfort and care, but it cannot be guessed from appearance. Read the label. The US Federal Trade Commission notes that most textile products must disclose fibre content and carry care instructions. Follow the specific garment label rather than applying a universal “delicates” routine.</p></section>
{picture(PONCHO_ROOT, "sheer-poncho-capsule", "Sand-coloured sheer poncho folded beside dark denim, an ivory ribbed tank, leather belt and black sandals")}
<section id="balance"><h2>Balance the volume instead of fighting it</h2><p>A poncho creates a horizontal line across the upper body and often hides the waist. The standard response is to make everything underneath tight. That works, but it is not the only option. The more useful principle is clarity. At least one part of the outfit should show where the body ends and the fabric begins.</p><p>With wide trousers, reveal the forearm and choose a poncho that ends around the high hip. With a full skirt, keep the layer narrower and let it finish above the waistband. With a column dress, a longer poncho can work because the dress supplies one uninterrupted line underneath. A short poncho over a short full skirt creates two stacked triangles, which can look like costume unless the materials are exceptionally restrained.</p><h3>Do not belt the sheer layer by default</h3><p>A belt can trap the fabric, distort the fall and create a gathered bubble at the waist. If shaping is necessary, belt the opaque layer underneath and let the poncho pass over it. A side opening or asymmetric hem can reveal the waist without adding hardware.</p><h3>Expose one joint</h3><p>Wrist, ankle or collarbone gives the eye a scale reference. This is why a three-quarter poncho sleeve often looks lighter than a full draped square. It is also why a long trouser works better with an open sandal than a heavy boot in warm weather. The exposed joint prevents a large piece of fabric from becoming the whole person.</p><p>The same logic appears in our <a href="/blogs/fashion/how-to-wear-peplum-tops/">modern peplum guide</a>: volume looks deliberate when the transition points are clear. The waist, wrist and hem do more work than decoration.</p></section>
<section id="formulas"><h2>Eight sheer poncho outfits that avoid festival costume</h2><h3>1. Grey organza, ivory shell, black trousers</h3><p>This is the strongest city formula. The colours form a quiet gradient, while the organza edge remains visible against both light and dark. Use a simple sandal or pointed flat. A large pendant will compete with the neckline; choose one cuff or small earrings instead.</p><h3>2. Black chiffon over a black column dress</h3><p>Monochrome allows transparency to become the detail. The dress should be matte and the poncho slightly lighter in surface. Finish with a low shoe so the entire look remains vertical. This can replace a conventional evening jacket without feeling bridal or overly formal.</p><h3>3. Sand voile over white tank and dark denim</h3><p>Denim gives the sheer layer an ordinary foundation. Keep the jean dark and clean, without shredded knees or decorative seams. A brown belt and black sandal make the outfit feel collected rather than matched. This is a useful transition from the <a href="/blogs/fashion/european-summer-style-2026/">European summer wardrobe</a> into early autumn.</p><h3>4. Open-knit poncho over a swimsuit and linen trousers</h3><p>Use the swimsuit as a bodysuit once away from the water, but make the trousers opaque. The knit can hold a little more texture because the palette is limited. Avoid shell necklaces, rope bags and nautical earrings all at once. One contextual detail is enough.</p><h3>5. Ink poncho over a pale-blue shirt and straight skirt</h3><p>A collar emerging through the neckline makes the piece feel closer to tailoring. Choose a poncho with a generous opening that does not crush the shirt. The skirt can be charcoal, navy or brown. Keep the shirt cuffs visible and skip a necklace.</p><h3>6. Rust chiffon over a cream knit and tobacco trousers</h3><p>Low-contrast colour makes transparency look richer. Rust, cream and tobacco share warmth while differing in depth. Use a dark shoe to stop the palette becoming hazy. This formula works particularly well in late summer when the weather is warm but the light has changed.</p><h3>7. Sheer black layer over jeans and a white vest</h3><p>The most casual version needs the best fabric. A clean black edge and controlled drape are essential because the pieces underneath are plain. Add a polished loafer rather than a festival boot. Our guide to <a href="/blogs/fashion/summer-loafers-outfit-guide/">summer loafers</a> offers useful low-profile options.</p><h3>8. Short asymmetric poncho over tonal separates</h3><p>An asymmetric hem already provides movement, so keep the colour relationship close: olive over moss, navy over ink, cream over oatmeal. Let the lower point fall beside the body rather than directly over the centre. The effect should be a line, not a superhero cape.</p></section>
{picture(PONCHO_ROOT, "black-sheer-poncho-evening", "Black chiffon poncho layered over a matte black column dress in a warm stone hotel corridor")}
<section id="occasions"><h2>The same poncho should not perform every job</h2><p>A beach layer can be open, tactile and easy to wash. A city layer needs a neckline that stays in position while carrying a bag. An evening layer should survive sitting, coat check and a crowded table. Decide where the piece will be worn before choosing the fabric.</p><div class="article-table-wrap" role="region" aria-label="Sheer poncho outfit guide by occasion" tabindex="0"><table class="article-visual-table"><thead><tr><th>Occasion</th><th>Best fabric</th><th>Layer underneath</th><th>Avoid</th></tr></thead><tbody><tr><td>Beach</td><td>Washable open knit or voile</td><td>Swimsuit and opaque shorts or trousers</td><td>Fragile trim and dry-clean-only fabric</td></tr><tr><td>City day</td><td>Soft organza or stable fine knit</td><td>Tank, shirt or close knit</td><td>Large bags that crush the side</td></tr><tr><td>Work</td><td>Matte chiffon or fine wool blend</td><td>Sleeveless shell and tailored trouser</td><td>Very transparent front panel</td></tr><tr><td>Evening</td><td>Silk chiffon or fluid crepe</td><td>Column dress or tonal separates</td><td>Too many reflective accessories</td></tr></tbody></table></div><p>Consider the bag before leaving home. A shoulder strap can pull sheer fabric into a tight rope and cause abrasion. Carry a top-handle or small hand-held bag when the material is delicate. If a crossbody is essential, place it underneath the poncho so the fabric can move freely over it.</p><p>Outerwear requires the opposite order. Fold the poncho neatly under a coat rather than allowing it to bunch at the sleeves. A sleeveless coat or wide armhole is easiest. If the poncho creases dramatically after ten minutes, it may not be a useful commuting piece.</p></section>
<section id="care"><h2>Care for the edges, not only the fabric</h2><p>Sheer garments often fail first at the neckline, side point or hem. These areas carry weight and catch on jewellery. Inspect the stitching after each wear, particularly where a narrow rolled hem changes direction. Repair a loose thread before it becomes a long pulled line.</p><p>Follow the attached care label. If hand washing is permitted, support the whole garment in water rather than lifting it by one corner. Avoid wringing. Dry it in the specified position and keep direct heat away. If the label requires professional cleaning, tell the cleaner about any beads, metal pieces or mixed fabrics.</p><h3>Store it with room to breathe</h3><p>A very light poncho can be folded flat with acid-free tissue at sharp points, while a stable knit may be folded without padding. Hanging can stretch an open neckline and create two permanent peaks at the shoulders. If you do hang it, use a broad padded hanger and support the lower fabric across the bar.</p><p>Keep the surface away from rough jewellery, unfinished wood and crowded zips. The goal is not museum storage for an everyday garment. It is preventing one metal edge from pulling a thread across the entire transparent field.</p></section>
<section class="article-faq"><h2>Sheer poncho questions</h2><h3>What do you wear under a sheer poncho?</h3><p>Wear an opaque, complete base such as a sleeveless shell and trousers, a column dress, a swimsuit with opaque bottoms or a fitted knit with a straight skirt.</p><h3>Can a sheer poncho look professional?</h3><p>Yes, if the transparency is restrained, the base layer covers appropriately and the poncho has a stable neckline and clean matte finish.</p><h3>How do you keep a poncho from looking bulky?</h3><p>Expose the wrist or ankle, choose a decisive hem and make sure one garment underneath creates a long uninterrupted line.</p></section>
<section class="source-note"><h2>Sources and image note</h2><p>Trend context comes from Pinterest’s <a href="{TREND_SOURCE}">Summer 2026 Trend Report</a>, published 26 May 2026. Fibre and care-label context was checked against the US Federal Trade Commission’s <a href="https://www.ftc.gov/news-events/topics/tools-consumers/apparel-labeling">apparel labelling guidance</a>. Garment-specific instructions always take priority. Styling analysis and all photographs are original by.foro editorial work; the clothes shown are fictional and unbranded.</p></section>
<section><h2>The best layer changes the air around an outfit</h2><p>A sheer poncho earns its place when it adds movement without demanding a costume underneath. Start with a real outfit, add one transparent plane and keep the edges precise. The result can be practical, even quiet. What looks dramatic in a still photograph should feel almost weightless once the wearer moves.</p></section><div class="article-end"><span>End</span><p>Published by by.foro Editorial on 23 August 2026. For corrections, contact <a href="mailto:hello@byforo.com">hello@byforo.com</a>.</p></div></div></div>'''


CAPRI_ROOT = "/assets/images/blogs/fashion/flowy-capri-pants-outfit"
CAPRI_BODY = f'''<div class="article-layout"><aside class="article-aside"><p class="kicker">The proportion guide</p><ol><li><a href="#answer">The short answer</a></li><li><a href="#length">Find the right length</a></li><li><a href="#shape">Choose the shape</a></li><li><a href="#outfits">Nine outfit formulas</a></li><li><a href="#shoes">The shoe decision</a></li><li><a href="#alter">Alterations and care</a></li></ol><button class="copy-link" data-copy-link type="button">Copy link</button></aside><div class="article-body">
<p class="article-opening">Flowy capri pants work when the hem looks chosen. Aim for a finish below the widest part of the calf or clearly closer to the knee, then balance the width with a defined shoulder, visible waist or narrow shoe. The trouser should move away from the leg without pretending to be a shortened palazzo.</p>
<p>Capris have a reputation for making every proportion difficult. The problem is rarely the existence of a cropped trouser. It is the accumulation of uncertain decisions: a hem at the widest calf, fabric with no fall, a top ending at the same horizontal line as the waistband and a shoe that adds another heavy block. Correct one or two of those decisions and the silhouette becomes surprisingly calm.</p>
<div class="summary-box" id="answer"><p class="kicker">The working formula</p><h2>Choose the hem first, then build one long line above it</h2><p>Stand in the shoes you expect to wear and pin the trouser at several lengths. Keep the version that clears the widest calf and leaves enough lower leg to make the crop obvious. Pair it with a tucked shirt, compact knit or long open layer. Finish with a low-vamp flat, slim sandal, loafer or refined runner flat.</p></div>
<section id="length"><h2>The most flattering length is not a universal number</h2><p>Pinterest recorded a 527 per cent rise in searches for “flowy capri pants outfit” in its Summer 2026 trend report. The exact phrase matters because it distinguishes a fluid wider shape from tight pedal pushers. Yet even within the flowy category, retailers use capri, crop and culotte for overlapping lengths. The product name cannot tell you where the hem will fall on your body.</p><p>Ignore the model’s height for a moment and look at the relationship between hem and calf. A strong capri usually finishes in a visually narrow zone. That may be just below the knee on one person and several centimetres above the ankle on another. The widest point of the calf is often the hardest stopping place because the horizontal hem underlines it.</p><h3>Pin three versions before shortening</h3><p>Try the trouser with its intended rise properly positioned. Fold and pin one version just below the knee, one below the broadest calf and one at lower calf. Photograph each from hip height, front and side. The camera is useful here because a mirror encourages the eye to fixate on the unfamiliar exposed leg rather than the whole outline.</p><p>Walk, sit and climb a stair. Flowing fabric can rise several centimetres when the knee bends. A hem that feels elegant while standing may pull too high when seated. If the trouser has a deep pleat, check whether shortening will cut into the point where the pleat opens.</p><h3>Make the crop unmistakable</h3><p>A trouser ending one or two centimetres above a shoe can look accidentally short. Either let a full trouser nearly meet the shoe or reveal a deliberate section of lower leg. Capris belong to the second category. This is why footwear with an open instep often helps: it extends the visible skin and makes the length read as design.</p></section>
{picture(CAPRI_ROOT, "navy-flowy-capris", "Deep navy fluid capri trousers with a pale blue cotton shirt and dark brown pointed flats beside a window")}
<section id="shape"><h2>Flow comes from cut and fabric working together</h2><p>A wide leg made from stiff fabric does not flow. It stands. That can be beautiful, but it creates a different, more architectural garment. For movement, look for cloth that folds back toward the leg after each step: tropical wool, viscose blends, washed linen with enough weight, fine cotton twill or fluid crepe.</p><p>Hold the trouser by the waistband and watch the legs hang. They should form long vertical folds rather than a rigid triangle. Then inspect the side seam. If it swings forward or backward, the cut may be fighting the grain or the garment may be twisted.</p><h3>Three useful silhouettes</h3><p><strong>The soft A-line</strong> begins relatively clean at the hip and widens gradually. It is the easiest to style because the upper body remains defined. <strong>The pleated crop</strong> has more room through the thigh and looks best when the waistband is visible. <strong>The straight fluid capri</strong> keeps nearly the same width from hip to hem and can take a longer shirt or jacket.</p><p>Large patch pockets, cargo straps and heavy cuffs interrupt the line. If those details are the point, keep the fabric less fluid and style the piece as utility clothing. For the elegant version, side pockets should lie flat and the hem should move as one continuous edge.</p><h3>The rise changes the entire equation</h3><p>A high rise lengthens the trouser section and makes a short or tucked top straightforward. A mid rise can feel more relaxed with an untucked shirt that ends between waist and high hip. A low rise combined with a wide crop exposes more torso and more lower leg, so it requires deliberate volume at the top. None is universally correct. The goal is to avoid three equal horizontal bands.</p></section>
<section id="outfits"><h2>Nine flowy capri pants outfits with clear proportions</h2><h3>1. Ivory capris with a black fine-knit top</h3><p>The contrast draws a precise line at the waist, while a dark slingback repeats the upper colour at the foot. Choose a small brown bag to keep the palette from becoming graphic black and white. This is the strongest starting formula for a dressier daytime look.</p><h3>2. Navy capris with a pale-blue shirt</h3><p>Stay within one colour family and let the difference in texture create depth. Tuck the shirt fully if the trouser has pleats. A pointed brown flat extends the foot and warms the blue without competing with it.</p><h3>3. Sand linen capris with an oversized white shirt</h3><p>Use a front tuck or open the shirt over a fitted tank. The back can remain loose, but the front needs a visible relationship to the waistband. Tobacco loafers make the linen feel urban. This outfit benefits from the restraint described in our <a href="/blogs/fashion/european-summer-style-2026/">European summer wardrobe</a>.</p><h3>4. Black capris with a long cream waistcoat</h3><p>The waistcoat supplies one vertical line through the centre. Wear it open over a narrow tank and keep the trouser hem clean. A simple sandal or low runner flat works; a tall ankle strap can make the lower section feel crowded.</p><h3>5. Chocolate capris with a rust silk shirt</h3><p>Close colour values make the crop feel sophisticated. Roll the sleeve once and expose the wrist. Add a cream or oxblood shoe rather than matching chocolate from head to toe. The outfit can carry one gold cuff, but it does not need a statement necklace.</p><h3>6. Grey pleated capris with a fitted cardigan</h3><p>Button the cardigan as a top and let it finish at the waistband. A compact shoulder line balances the width below. This is a useful early-autumn formula with a fine sock and <a href="/blogs/fashion/runner-flats-outfit/">runner Mary Jane</a>.</p><h3>7. Olive capris with an ivory sleeveless shell</h3><p>Keep the shell smooth and choose a trouser with minimal pocket detail. Black or dark-brown sandals ground the olive. A field jacket would repeat the utility reference too literally; use a linen blazer if another layer is needed.</p><h3>8. Pinstriped capris with a plain white T-shirt</h3><p>The vertical stripe helps the shortened trouser retain length. The T-shirt should have enough structure at the sleeve and neckline to meet the tailoring. Finish with a loafer or minimal sneaker, then add a belt only if the waistband is designed to take one.</p><h3>9. Fluid black capris with a sheer poncho</h3><p>Keep the tank underneath fitted and let the poncho finish above the widest part of the trouser. The black lower half provides a calm base for smoke, sand or ink transparency. Our <a href="/blogs/fashion/sheer-poncho-outfit/">sheer poncho guide</a> explains how to prevent the two volumes from competing.</p></section>
{picture(CAPRI_ROOT, "linen-flowy-capris", "Sand linen-blend wide capri trousers with a white shirt, slim brown belt and tobacco loafers against terracotta plaster")}
<section id="shoes"><h2>The shoe changes where the eye believes the leg ends</h2><p>A low-vamp pointed flat exposes more of the foot and extends the line. A loafer adds weight and works best when the trouser has enough structure or the top includes another grounded element. A slim sandal produces the lightest result. Runner flats add texture and make tailored capris less formal.</p><div class="article-table-wrap" role="region" aria-label="Shoes to wear with flowy capri pants" tabindex="0"><table class="article-visual-table"><thead><tr><th>Shoe</th><th>Effect</th><th>Best with</th><th>Watch for</th></tr></thead><tbody><tr><td>Pointed flat</td><td>Lengthens the exposed foot</td><td>Fluid wool and pleated capris</td><td>Toe box comfort</td></tr><tr><td>Loafer</td><td>Adds polish and weight</td><td>Linen, cotton and pinstripes</td><td>Heavy sock plus heavy hem</td></tr><tr><td>Slim sandal</td><td>Keeps the lower line open</td><td>Summer crepe and soft A-lines</td><td>Too many ankle straps</td></tr><tr><td>Runner flat</td><td>Adds modern technical texture</td><td>Plain tailored capris</td><td>Bulky sole overwhelming the crop</td></tr><tr><td>Minimal wedge</td><td>Adds height without a thin heel</td><td>Longer lower-calf hems</td><td>Platform turning the look retro</td></tr></tbody></table></div><p>An ankle boot is possible, but it creates a continuous covered section from foot to hem. Keep the boot close to the ankle and the colours related. A wide boot shaft under a wide capri produces friction and may distort the hem.</p><p>Do not choose a shoe solely because it is labelled flattering. Wear the pair long enough to test comfort and movement. A beautiful line disappears once the wearer is gripping the shoe or shortening every step.</p></section>
<section id="alter"><h2>Alterations are worth the trouble</h2><p>The hem is the defining feature, so professional alteration can transform an average pair. Ask the tailor to pin both legs while you stand in the intended shoes. Check whether the garment has been washed or pre-shrunk according to its care instructions before deciding the final length. Linen and viscose can change with cleaning.</p><p>Preserve the original hem depth when possible. A tiny hem may flare on fluid cloth, while a very deep hem can add useful weight. If the trouser has a cuff, shortening may require rebuilding it rather than simply cutting fabric away.</p><h3>Keep creases intentional</h3><p>Some flowy capris look best with a pressed front crease; others should fall softly. Follow the original construction. Hang creased trousers from the hem or fold them along the crease. Let linen retain a little movement rather than pressing it into a brittle board.</p><p>Read the care label before steaming. The FTC requires manufacturers and importers covered by its Care Labeling Rule to provide a supported cleaning method, but mixed fibres and trims still vary. A cool iron that suits one viscose blend may damage another finish.</p></section>
<section class="article-faq"><h2>Flowy capri pants questions</h2><h3>Where should capri pants end?</h3><p>Aim for a deliberately narrow zone of the leg, often below the widest calf or clearly nearer the knee. Pin several lengths while wearing the intended shoes.</p><h3>What tops work with wide capris?</h3><p>Fitted knits, tucked shirts, sleeveless shells, compact cardigans and long open layers all work when they create one clear vertical or reveal the waistband.</p><h3>Can petite people wear flowy capris?</h3><p>Yes. The exact hem and rise matter more than height labels. Keep the crop obvious, define one long line and alter the length to the wearer rather than the product photograph.</p></section>
<section class="source-note"><h2>Sources and image note</h2><p>Search-growth context comes from Pinterest’s <a href="{TREND_SOURCE}">Summer 2026 Trend Report</a>, published 26 May 2026. Care-label context was checked against the US Federal Trade Commission’s <a href="https://www.ftc.gov/business-guidance/resources/clothes-captioning-complying-care-labeling-rule">Care Labeling Rule guidance</a>. Styling, proportion tests and photographs are original by.foro editorial work; garments shown are fictional and unbranded.</p></section>
<section><h2>The hem should end the argument</h2><p>A good pair of flowy capris does not apologise for being shorter than trousers and longer than shorts. The hem lands with intent, the fabric returns to the leg after movement and the outfit gives the eye one uninterrupted route. Once those decisions are clear, the supposed difficult trouser becomes a useful one.</p></section><div class="article-end"><span>End</span><p>Published by by.foro Editorial on 24 August 2026. For corrections, contact <a href="mailto:hello@byforo.com">hello@byforo.com</a>.</p></div></div></div>'''


BANDANA_ROOT = "/assets/images/blogs/fashion/bandana-jewellery"
BANDANA_BODY = f'''<div class="article-layout"><aside class="article-aside"><p class="kicker">The accessory edit</p><ol><li><a href="#answer">The short answer</a></li><li><a href="#definition">What counts as bandana jewellery</a></li><li><a href="#materials">Choose silk and metal</a></li><li><a href="#necklace">Necklace placements</a></li><li><a href="#other">Bracelets, bags and collars</a></li><li><a href="#buy">Buy and care for it</a></li></ol><button class="copy-link" data-copy-link type="button">Copy link</button></aside><div class="article-body">
<p class="article-opening">Bandana jewellery works when the fabric acts as a setting for one metal detail. Fold the scarf narrowly, choose a ring, slide or pendant with enough weight to hold its position, and keep the surrounding neckline plain. The piece should look like jewellery made from textile, not a scarf decorated with everything in the drawer.</p>
<p>The category is still loose enough to be interesting. It can mean a silk square threaded through a sculptural ring, a narrow bandana carrying a pendant, a scarf wrapped with a fine chain, or a small textile bracelet closed with metal. That uncertainty is exactly where bad styling enters. Tassels, coins, pearls, charms and a large knot can all be individually appealing, but together they turn the neck into a souvenir display.</p>
<div class="summary-box" id="answer"><p class="kicker">The modern rule</p><h2>One textile, one piece of hardware, one clear placement</h2><p>Start with a scarf between 45 and 65 centimetres square or a narrow purpose-made band. Fold it to the width the hardware can hold. Place the metal slightly off-centre or at the hollow of the throat, then stop. Wear it with cotton, denim, dry wool or a simple knit. If the scarf has a busy print, choose plain metal. If the scarf is solid, one irregular pearl or carved charm can work.</p></div>
<section id="definition"><h2>What bandana jewellery is, and what it is not</h2><p>Pinterest’s Summer 2026 report showed searches for “bandana jewellery” rising 303 per cent. Related searches for bandana scarves and scarves on bags were also up. The momentum sits at the intersection of two larger returns: scarves are being used as functional styling tools again, while jewellery is becoming more tactile and personal after a long minimalist period.</p><p>A traditional scarf knot is not automatically jewellery. The category begins when hardware changes the way the textile hangs or fastens. A scarf ring can replace the knot. A pendant can give the point a centre of gravity. A fine chain can stabilise a wrist wrap. The metal has a job as well as an appearance.</p><p>This makes bandana jewellery different from simply adding a brooch to a scarf. A brooch pierces the textile and sits on its surface. A ring or slide uses compression and friction. A pendant hangs from an attachment point. Each method affects the fabric differently, and each should be judged for abrasion, weight and security.</p><h3>The appeal is scale</h3><p>A silk square covers more visual space than a chain, but it can carry less apparent formality than a gemstone necklace. That makes it useful between a bare neckline and a statement jewel. It also changes with the print. Burgundy paisley feels earthy; navy and cream can feel graphic; a solid tobacco twill reads almost like soft leather.</p><p>The closest existing by.foro relative is the <a href="/blogs/fashion/how-to-wear-a-scarf-belt/">scarf belt</a>. Both depend on tension, placement and enough fabric to hold a knot. The jewellery version operates at smaller scale, so finishing quality becomes even more visible.</p></section>
{picture(BANDANA_ROOT, "bandana-necklace-shirt", "Navy silk bandana necklace held by an aged-gold ring and irregular pearl over a white cotton shirt")}
<section id="materials"><h2>Choose the scarf for friction, not only colour</h2><p>Silk twill is particularly effective because its diagonal weave has body and a lightly grippy surface. It holds a fold, slides through hardware without becoming limp and can support a modest pendant. Very thin chiffon may collapse inside a ring or pull into a cord. Heavy cotton can work with larger hardware, but a bulky knot may sit awkwardly at the neck.</p><p>Run the fabric through the ring before committing to an outfit. The hardware should hold when the scarf is gently tugged, yet release without snagging when intentionally removed. Check every interior edge with a fingertip. A decorative ring can be beautifully polished outside and rough inside where the scarf actually moves.</p><h3>Match hardware weight to fabric weight</h3><p>A broad brushed-metal slide can stabilise folded silk. A small fine ring suits a narrow band. Heavy pendants need a reinforced loop or separate connector rather than being hooked through one layer of fabric. If the point visibly stretches, the combination is too heavy.</p><p>Material descriptions deserve scrutiny. “Gold tone” does not state the base metal or plating. “Silver colour” does not mean sterling silver. The US Federal Trade Commission’s jewellery guidance says sellers should represent metallic content, treatments and other material facts truthfully. Read the detailed description, especially if metal sensitivity or long-term wear matters.</p><h3>Print and metal should not tell the same story twice</h3><p>A Western paisley with a large concho can become costume quickly. A marine print with an anchor charm has the same problem. Let one element provide context and the other provide contrast. Paisley with a smooth modern ring, or solid silk with an antique coin, leaves more interpretive room.</p></section>
<section id="necklace"><h2>Five necklace placements, from quiet to dramatic</h2><h3>1. The throat ring</h3><p>Fold the scarf into a narrow band, wrap it once and pull both ends through a ring at the hollow of the throat. Keep the ends short and even. This is the most jewellery-like placement and works with an open white shirt, crew-neck knit or strapless evening top. Check that the wrap remains comfortable when sitting and turning the head.</p><h3>2. The offset slide</h3><p>Move the ring several centimetres toward one collarbone and let the scarf tails fall diagonally. The asymmetry modernises a classic print and works well under a blazer. Keep earrings small because the slide already occupies the side of the neck.</p><h3>3. The pendant point</h3><p>Fold the scarf into a triangle, roll from the long edge and leave the centre point slightly visible. Attach one pendant below the knot or ring. The point acts like a soft chain. Use a pendant with a rounded bail and no sharp back.</p><h3>4. The collar bridge</h3><p>Wear a narrow band under a shirt collar and close it with a ring just below the first open button. The shirt supplies structure, which allows the silk to remain soft. This placement can replace a tie without imitating one. A dry poplin or chambray shirt gives the most useful contrast.</p><h3>5. The long textile necklace</h3><p>Roll a larger square, join the ends behind the neck and place a slide lower on the chest. Keep the rest of the outfit very plain. The line works over a fine knit or column dress, but the pendant should not collide with buttons, zips or a bag strap.</p><p>These placements share the formality-contrast rule from our guide to <a href="/blogs/fashion/how-to-wear-brooches/">modern brooches</a>. Put the elaborate detail on an ordinary fabric. Crystal against denim, pearls against cotton and aged gold against dry wool all feel more current than ornament layered over ornament.</p></section>
{picture(BANDANA_ROOT, "bandana-bracelet", "Rust-and-ink silk bandana bracelet wrapped with a fine silver chain and small abstract charm on a stone café table")}
<section id="other"><h2>The idea moves beyond the neckline</h2><h3>A bracelet needs a mechanical closure</h3><p>A fabric bracelet should not depend on a large decorative bow. Fold the band narrowly, wrap it twice and secure it with a ring, chain or small clasp that has been designed for the job. Leave enough ease for one fingertip. Test it while typing and washing hands. Remove silk before water, lotion or cleaning products reach it.</p><h3>A bag charm should protect the handle</h3><p>A scarf wrapped around a top handle can reduce direct contact with skin oils, but hardware changes the equation. Keep pendants away from painted leather and corners where they can strike repeatedly. One ring and one short tail are enough. If the bag already has visible buckles, chains and a logo, use plain fabric or skip the extra jewellery.</p><h3>A collar piece can replace a necklace</h3><p>Thread a narrow scarf through two small rings at the collar points, or use one central slide under the collar. Do not pierce fine silk with ordinary safety pins. If a pin is essential, use a proper brooch on a garment strong enough to carry it and follow the support advice in our brooch guide.</p><h3>Hair placement requires smooth hardware</h3><p>A small slide can hold a scarf over a low ponytail, but it must not catch hair. Test the seam, hinge and inner ring. Heavy pendants are a poor choice near moving hair because they pull and tangle. The bandana should be tied to the hair securely before the decorative element is added.</p><p>For a more sculptural neck option without textile, see our guide to the <a href="/blogs/fashion/how-to-wear-a-bib-necklace/">new bib necklace</a>. The two accessories occupy similar visual territory, so wearing both together usually removes the clarity that makes either successful.</p></section>
<section id="buy"><h2>How to buy bandana jewellery that survives real wear</h2><p>Examine the scarf and hardware separately. The silk should have even edges, secure corners and a print that remains attractive when reduced to a narrow fold. The ring should be smooth inside, appropriately weighted and large enough for the intended fabric. The connector between charm and ring should close completely.</p><div class="article-table-wrap" role="region" aria-label="Bandana jewellery buying guide" tabindex="0"><table class="article-visual-table"><thead><tr><th>Part</th><th>Look for</th><th>Avoid</th></tr></thead><tbody><tr><td>Scarf</td><td>Stable weave and finished edges</td><td>Loose threads near the hardware path</td></tr><tr><td>Ring</td><td>Polished interior and useful weight</td><td>Sharp seam or rough casting</td></tr><tr><td>Pendant</td><td>Rounded bail and secure connector</td><td>Open jump ring or sharp back</td></tr><tr><td>Chain</td><td>Enough ease to move naturally</td><td>Fine links sawing across the silk</td></tr><tr><td>Description</td><td>Specific fibre and metal information</td><td>Vague “luxury” wording without content</td></tr></tbody></table></div><p>Vintage hardware can be beautiful, but oxidation, rough solder and unstable plating deserve professional assessment before contact with valuable silk. Do not clean an unknown metal with household acids or abrasive pastes. What removes tarnish can also remove a surface finish.</p><h3>Store the parts apart</h3><p>Unthread the scarf after wear. Fold or roll it without a hard crease and store it clean and dry. Keep the metal in a soft separate pouch so it cannot mark the textile. The Canadian Conservation Institute notes that moisture, pollutants and direct contact can contribute to metal corrosion and physical damage. Everyday jewellery does not require museum conditions, but dry storage and separated surfaces are sensible habits.</p><p>Perfume belongs on skin before the scarf is tied, with time to dry. Hand cream should also settle before a textile bracelet goes on. If the hardware changes colour, develops a rough surface or leaves residue on the silk, stop wearing the combination until the material is identified.</p></section>
<section class="article-faq"><h2>Bandana jewellery questions</h2><h3>What is bandana jewellery?</h3><p>It is a scarf-based accessory in which a ring, slide, pendant, chain or clasp changes how the textile fastens or hangs, making the fabric part of the jewellery structure.</p><h3>How do you keep a scarf ring from slipping?</h3><p>Use a stable fabric such as silk twill, fold it to fit the ring and choose hardware with enough friction and weight. Never rely on a rough interior edge to grip the fabric.</p><h3>Can bandana jewellery be worn with earrings?</h3><p>Yes. Keep earrings small when the scarf ring sits near the collarbone. A central low pendant can tolerate a slightly larger stud or hoop.</p></section>
<section class="source-note"><h2>Sources and image note</h2><p>Search-growth context comes from Pinterest’s <a href="{TREND_SOURCE}">Summer 2026 Trend Report</a>, published 26 May 2026. Material-description guidance was checked against the US Federal Trade Commission’s <a href="https://www.ftc.gov/news-events/topics/tools-consumers/jewelry-guides">Jewelry Guides</a>. Storage principles were checked against the Canadian Conservation Institute’s <a href="https://www.canada.ca/en/conservation-institute/services/preventive-conservation/guidelines-collections/metal-objects.html">care guidance for metal objects</a>. The styling analysis and all photographs are original by.foro editorial work; patterns and hardware shown are fictional and unbranded.</p></section>
<section><h2>Soft material can still make a precise object</h2><p>The best bandana jewellery does not disguise a scarf as a necklace. It uses the difference between textile and metal. Silk folds, metal holds, and one small weight gives the whole piece direction. Keep the construction legible and the outfit ordinary enough to receive it.</p></section><div class="article-end"><span>End</span><p>Published by by.foro Editorial on 25 August 2026. For corrections, contact <a href="mailto:hello@byforo.com">hello@byforo.com</a>.</p></div></div></div>'''


SARDINE_ROOT = "/assets/images/blogs/culture/sardines-breakfast"
SARDINE_BODY = f'''<div class="article-layout"><aside class="article-aside"><p class="kicker">The breakfast table</p><ol><li><a href="#answer">The short answer</a></li><li><a href="#choose">Choose the tin</a></li><li><a href="#formula">The flavour formula</a></li><li><a href="#ideas">Seven breakfast ideas</a></li><li><a href="#serve">Serve without fuss</a></li><li><a href="#safety">Storage and safety</a></li></ol><button class="copy-link" data-copy-link type="button">Copy link</button></aside><div class="article-body">
<p class="article-opening">Sardines make a good breakfast when richness is balanced immediately. Start with one tin in olive oil, add something crisp, something acidic and one soft element, then stop. Toast, lemon, cucumber, tomato, beans, a soft egg or cultured dairy all work. The fish should be part of the plate, not buried under a decorative grazing board.</p>
<p>Breakfast sardines sound novel only in places where sweet cereals and eggs have narrowed the morning imagination. Preserved fish already belongs to many breakfast tables in different forms. The current search interest is less about inventing the combination than noticing how well a small tin fits modern mornings: no cooking required, a clear portion and enough flavour that a plain slice of bread becomes a meal.</p>
<div class="summary-box" id="answer"><p class="kicker">The useful formula</p><h2>Fish, crunch, acid and one soft counterpoint</h2><p>Drain only as much oil as the plate needs. Add grilled bread, crisp potatoes or cucumber for structure. Use lemon, tomato, pickles or vinegar for brightness. Finish with a soft egg, white beans, labneh or butter if the plate needs calm. Keep strong extras to two or three, because capers, olives, mustard and hot sauce can quickly turn balance into noise.</p></div>
<section id="choose"><h2>Choose the tin by the breakfast you want</h2><p>Pinterest recorded a 1,815 per cent rise in searches for “sardines breakfast” in its Summer 2026 report, along with growth for sardine toast and tinned-fish boards. The number shows rapid momentum on Pinterest, not a universal change in eating habits. It does, however, reveal a useful search question: people want to know what to do with the tin before noon.</p><p>Sardines packed in olive oil are the most adaptable. The oil carries flavour into toast, beans and tomatoes. Sardines in water are lighter but may need a spoon of good oil or butter elsewhere. Tomato sauce creates a ready-made direction and works with eggs, rice or potatoes. Spiced oil needs fewer condiments because the seasoning has already begun.</p><h3>Whole, skinless or boneless</h3><p>Whole sardines have the fullest texture and strongest visual presence. Skinless and boneless versions are milder in appearance and easier for a first attempt. Neither choice is morally superior at breakfast. Buy the form you will actually eat. If the sight of whole fish makes the plate feel confrontational, start with fillets and let flavour lead.</p><p>Inspect the can before opening. Do not use a container that is bulging, leaking, badly rusted or deeply damaged. When the lid opens, the fish should smell cleanly marine and like its packing medium, not sour or putrid. If anything seems wrong, do not taste it to investigate.</p><h3>Read the label before adding salt</h3><p>Oil, sauce, smoke and seasoning vary widely. Taste one small piece before salting the rest of the plate. Capers, olives, pickles, cheese and salted butter can all add more. Breakfast should wake the palate, not overwhelm it.</p></section>
{picture(SARDINE_ROOT, "sardine-breakfast-toasts", "Three distinct sardine breakfast toasts with tomato and parsley, white beans and lemon, and a soft egg with capers")}
<section id="formula"><h2>Build the plate through contrast</h2><p>Sardines are soft, rich and intensely savoury. A successful breakfast provides an opposing texture and a quick line of acidity. Toast is popular because it does both when rubbed with tomato or finished with lemon. Crisp potatoes, radish, cucumber, endive and toasted seeds can provide the same structural role.</p><h3>Choose one base</h3><p>Use sourdough, rye, flatbread, rice, potatoes, white beans or sliced cucumber. The base should be able to carry oil without collapsing. Toast bread more deeply than you would for jam. Let boiled potatoes steam dry before crushing them. Rinse and drain canned beans well so the plate does not become watery.</p><h3>Add one acid</h3><p>Lemon is the obvious choice because it brightens without introducing sweetness. Tomato adds acid and moisture. Pickled onion, cornichons, capers and a little sherry vinegar give sharper results. Use one as the main acid and another only as a small accent.</p><h3>Add softness only if needed</h3><p>A jammy egg makes the plate more substantial but also richer. Labneh, yoghurt, white beans, butter and avocado soften the fish’s intensity. Do not add all of them. If the sardines are already in a generous oil, cucumber or tomato may be more useful than another creamy component.</p><h3>Finish with a fresh edge</h3><p>Parsley, dill, chives, celery leaves, sliced spring onion or a few bitter leaves keep the plate awake. Herbs should look handled, not scattered for a photograph. Tear or chop them and let them touch the food they are meant to flavour.</p></section>
<section id="ideas"><h2>Seven sardine breakfast ideas worth repeating</h2><h3>1. Tomato-rubbed toast with parsley</h3><p>Grill thick sourdough until the edges darken. Rub the cut side of a ripe tomato across the surface, add sardines and finish with parsley, lemon and black pepper. The tomato enters the bread rather than sitting as a wet slice on top. This is the fastest version and needs no egg.</p><h3>2. Rye toast, cucumber and dill butter</h3><p>Mix softened butter with chopped dill and a small amount of lemon zest. Spread it thinly on deeply toasted rye, add overlapping cucumber and place sardines on top. The cucumber gives clean crunch while the butter connects the fish to the bread. Skip capers unless the tin is very mild.</p><h3>3. White beans, lemon and sardines</h3><p>Dress drained white beans with lemon juice, a little tin oil, parsley and black pepper. Spoon them onto toast or eat them from a shallow bowl with sardines laid across the top. The beans make the breakfast calm and satisfying without another animal ingredient.</p><h3>4. Soft egg, capers and grilled bread</h3><p>Cook an egg until the white is set and the yolk remains soft. Place it beside, not over, the sardines so each bite can control the richness. Add capers sparingly and serve with toast. A small mustard vinaigrette on bitter leaves can replace lemon.</p><h3>5. Crushed potatoes with pickled onion</h3><p>Boil small potatoes, crush them and crisp the edges in a pan or oven. Top with sardines, pickled red onion and parsley. This is the warmest option and works particularly well with fish in tomato or spiced oil. Keep the onion sharp and the portion small enough for morning.</p><h3>6. Labneh, radish and sardine flatbread</h3><p>Spread a thin layer of labneh over warm flatbread. Add radish slices, sardines and dill. The cultured dairy softens the fish, while radish keeps the surface crisp. Fold and eat immediately before the bread steams itself soft.</p><h3>7. The no-toast breakfast plate</h3><p>Arrange cucumber, tomato, a soft egg, lemon and one tin on an ordinary plate. Add a small bowl of beans or a piece of fruit separately if needed. This is not a charcuterie board. It is a direct breakfast with enough choices to vary each bite and few enough elements to finish.</p><p>If the meal continues into lunch, a chilled light red can be an interesting pairing, but not for an ordinary working morning. Our guide to <a href="/blogs/culture/how-to-serve-chilled-red-wine/">serving red wine cold</a> explains which styles tolerate lower temperatures and how to avoid flattening aroma.</p></section>
{picture(SARDINE_ROOT, "sardines-toast-preparation", "Two hands using a fork to place sardines over cucumber and grilled rye toast on a dark kitchen counter")}
<section id="serve"><h2>How to make the table look considered without making breakfast a performance</h2><p>Open the tin in the kitchen, wipe the exterior and place it on a small plate if oil may drip. Use one dinner plate, one fork and one cloth napkin. A low bowl is useful for beans or potatoes. The food already has enough silver, green and gold colour; it does not need a themed coastal setting.</p><p>Let the tin remain visible when it helps identify the packing medium and portion. Transfer the fish when the lid is sharp, the container rocks or several people are sharing. A small shallow dish keeps fillets intact and makes serving easier. Never ask guests to reach across a table around a cut metal edge.</p><h3>Balance temperature</h3><p>Room-temperature shelf-stable sardines can meet hot toast, but cold accompaniments should be intentionally cold. A warm cucumber and cold egg make the plate feel neglected. Prepare the vegetables first, toast last and open the tin just before serving.</p><p>For a group breakfast, build individual plates rather than one enormous board. Each person can receive toast, acid and a small fish portion without the most delicate ingredients sitting out. A shared basket of bread and bowl of lemon wedges is enough theatre.</p><h3>Choose a drink that clears rather than competes</h3><p>Black coffee can work with a simple buttered toast version, though heavily roasted coffee may dominate delicate fish. Tea with brightness and low sweetness is easier. Sparkling water with lemon is reliable. Tomato juice suits a savoury breakfast but can make a tomato-packed sardine plate feel repetitive.</p><p>The larger by.foro principle from <a href="/blogs/culture/how-taste-is-built/">how taste is built</a> applies here: attention develops through comparison. Try the same tin with lemon one day and tomato the next. Notice whether rye or sourdough supports it better. Preference becomes useful when it is specific.</p></section>
<section id="safety"><h2>Storage and food safety are not styling details</h2><p>Commercially canned fish is shelf stable only until the container is opened, unless the label specifically says it must be refrigerated. Follow the package date and storage instructions. Store unopened tins in a cool, dry place away from heat and damp.</p><p>After opening, refrigerate unused fish promptly in a clean food-grade container. The US Department of Agriculture says opened low-acid canned foods, including fish, can generally be stored in the refrigerator for three to four days. Quality may be better when the food is moved from the can into glass or plastic. If the manufacturer gives a shorter period, follow it.</p><h3>Use the two-hour rule at the table</h3><p>The US Food and Drug Administration advises that perishable seafood should not remain unrefrigerated for more than two hours, or more than one hour when the temperature is above 90°F (32°C). For a long brunch, bring out a smaller amount and replenish from the refrigerator rather than leaving every open tin in warm light.</p><p>Use clean utensils and avoid repeatedly dipping a used fork into a tin that will be stored. Wipe oil from the prep surface before it travels to handles or cupboard doors. The transfer-route method in our guide to <a href="/blogs/home/how-to-keep-your-space-clean/">keeping a space clean</a> is especially useful in a small kitchen.</p><p>People who are pregnant, immunocompromised or managing a medical condition should follow their clinician’s advice and official food-safety guidance. This article is an editorial serving guide, not individual nutrition or medical advice.</p><h3>Dispose of the lid carefully</h3><p>Fold it back only as the can is designed to open. Do not leave a detached sharp lid under a napkin or on a crowded plate. Place it inside the empty can when safe to do so, or move it directly to the appropriate waste container where nobody will reach blindly.</p></section>
<section class="article-faq"><h2>Sardines for breakfast questions</h2><h3>What goes well with sardines for breakfast?</h3><p>Toast, lemon, tomato, cucumber, white beans, soft eggs, potatoes, labneh, parsley, dill, capers and pickled onion all work. Choose one base, one acid and one soft element.</p><h3>Can sardines be eaten straight from the tin?</h3><p>Commercially canned sardines are generally ready to eat unless the label says otherwise. Inspect the can, follow the package instructions and use a safe utensil.</p><h3>How long do opened sardines last in the refrigerator?</h3><p>USDA guidance places opened low-acid canned foods such as fish at three to four refrigerated days. Transfer leftovers promptly to a clean container and follow any shorter manufacturer instruction.</p></section>
<section class="source-note"><h2>Sources and image note</h2><p>Search-growth context comes from Pinterest’s <a href="{TREND_SOURCE}">Summer 2026 Trend Report</a>, published 26 May 2026. Storage guidance was checked against the US Department of Agriculture’s pages on <a href="https://www.fsis.usda.gov/food-safety/safe-food-handling-and-preparation/food-safety-basics/shelf-stable-food">shelf-stable food</a> and <a href="https://ask.fsis.usda.gov/article/After-you-open-a-can-how-long-can-you-keep-the-food-in-the-refrigerator">opened canned foods</a>. Serving-time guidance was checked against the US Food and Drug Administration’s <a href="https://www.fda.gov/food/buy-store-serve-safe-food/selecting-and-serving-fresh-and-frozen-seafood-safely">seafood safety advice</a>. Recipes, observations and all photographs are original by.foro editorial work; tins shown are fictional and unbranded.</p></section>
<section><h2>A small tin does not need a large performance</h2><p>The best sardine breakfast is direct. Toast something properly, add a sharp element, choose one soft counterpoint and let the fish retain its character. What makes the plate feel generous is not the number of bowls around it. It is the care taken with contrast, temperature and the next bite.</p></section><div class="article-end"><span>End</span><p>Published by by.foro Editorial on 26 August 2026. For corrections, contact <a href="mailto:hello@byforo.com">hello@byforo.com</a>.</p></div></div></div>'''


ARTICLES = [
    {
        "publish_on": "2026-08-22",
        "url": "/blogs/fashion/runner-flats-outfit/",
        "seo": "Runner Flats Outfit Ideas: How to Style the Hybrid Shoe",
        "title": "Runner Flats Are the Shoe Fashion Could Not Name",
        "description": "Learn how to style runner flats with trousers, skirts, denim and socks, plus practical fit checks that make ballet-runner hybrids genuinely wearable.",
        "deck": "Part ballet flat, part technical trainer, the season’s strangest shoe becomes useful once the hem, sock and sole agree.",
        "department": "Fashion",
        "topic": "Trends",
        "hero": f"{RUNNER_ROOT}/runner-flats-hero",
        "alt": "Taupe mesh and suede runner flats worn with fluid charcoal trousers in a limestone arcade",
        "body": RUNNER_BODY,
        "keywords": ["runner flats outfit", "runner Mary Janes outfit", "ballet runners", "hybrid sneaker flats"],
        "reciprocal": {
            "path": "blogs/fashion/jelly-kitten-heels/index.html",
            "sentence": '<p>For another flat that mixes beauty with a practical question, our <a href="/blogs/fashion/runner-flats-outfit/">runner flats outfit guide</a> explains the new ballet-trainer hybrid, including proportion and fit.</p>',
        },
    },
    {
        "publish_on": "2026-08-23",
        "url": "/blogs/fashion/sheer-poncho-outfit/",
        "seo": "Sheer Poncho Outfit Ideas That Look Modern in 2026",
        "title": "The Sheer Poncho, Minus the Festival Costume",
        "description": "Style a sheer poncho for city days, work, evenings and the beach with modern proportions, considered base layers and fabrics that move beautifully.",
        "deck": "A transparent layer can feel precise, not theatrical. The difference is in the fabric, the base outfit and the edges left visible.",
        "department": "Fashion",
        "topic": "Trends",
        "hero": f"{PONCHO_ROOT}/sheer-poncho-hero",
        "alt": "Smoke-grey sheer organza poncho over an ivory shell and black tailored trousers on a pale stone terrace",
        "body": PONCHO_BODY,
        "keywords": ["sheer poncho outfit", "how to wear a sheer poncho", "modern poncho outfit", "sheer layering ideas"],
        "reciprocal": {
            "path": "blogs/fashion/european-summer-style-2026/index.html",
            "sentence": '<p>For a lighter late-summer layer, our <a href="/blogs/fashion/sheer-poncho-outfit/">sheer poncho outfit guide</a> shows how organza, chiffon and fine knit can look precise rather than festival-themed.</p>',
        },
    },
    {
        "publish_on": "2026-08-24",
        "url": "/blogs/fashion/flowy-capri-pants-outfit/",
        "seo": "Flowy Capri Pants Outfits: The Modern Proportion Guide",
        "title": "Flowy Capris Are Easier Than They Look",
        "description": "Find the right flowy capri length, fabric, top and shoes with a practical proportion guide and nine polished outfits for summer and early autumn.",
        "deck": "The supposedly difficult trouser becomes simple when the hem is deliberate, the fabric truly moves and one line stays uninterrupted.",
        "department": "Fashion",
        "topic": "Trends",
        "hero": f"{CAPRI_ROOT}/flowy-capri-pants-hero",
        "alt": "Ivory fluid wide-leg capri trousers with a black fine-knit top, brown bag and dark slingback flats",
        "body": CAPRI_BODY,
        "keywords": ["flowy capri pants outfit", "wide capri pants outfit", "how to style capri pants", "capri pants shoes"],
        "reciprocal": {
            "path": "blogs/fashion/runner-flats-outfit/index.html",
            "sentence": '<p>The exposed lower leg makes shoe choice especially visible. Our <a href="/blogs/fashion/flowy-capri-pants-outfit/">flowy capri proportion guide</a> explains the hem lengths and outfit lines that work with runner flats.</p>',
        },
    },
    {
        "publish_on": "2026-08-25",
        "url": "/blogs/fashion/bandana-jewellery/",
        "seo": "Bandana Jewellery: How to Wear the Scarf Necklace Trend",
        "title": "Bandana Jewellery Is More Than a Scarf and Charm",
        "description": "Learn how to wear bandana jewellery as a necklace, bracelet or bag detail, with guidance on scarf rings, pendants, materials, placement and care.",
        "deck": "Silk folds, metal holds, and one small weight gives the accessory direction. The construction should remain easy to read.",
        "department": "Fashion",
        "topic": "Accessories",
        "hero": f"{BANDANA_ROOT}/bandana-jewellery-hero",
        "alt": "Oxblood and cream silk bandana threaded through a brushed-gold ring and pendant on dark walnut",
        "body": BANDANA_BODY,
        "keywords": ["bandana jewellery", "bandana necklace", "scarf necklace trend", "how to wear a scarf ring"],
        "reciprocal": {
            "path": "blogs/fashion/how-to-wear-a-scarf-belt/index.html",
            "sentence": '<p>The same attention to tension applies at a smaller scale in our <a href="/blogs/fashion/bandana-jewellery/">bandana jewellery guide</a>, where scarf rings, pendants and chains turn silk into a structured accessory.</p>',
        },
    },
    {
        "publish_on": "2026-08-26",
        "url": "/blogs/culture/sardines-breakfast/",
        "seo": "Sardines for Breakfast: 7 Easy Ideas That Taste Good",
        "title": "Sardines for Breakfast, Without Making It a Performance",
        "description": "Make sardines for breakfast with seven practical combinations, a simple flavour formula and clear advice on choosing, serving and storing each tin.",
        "deck": "One tin, something crisp, something acidic and one soft counterpoint. A good savoury breakfast can stay direct.",
        "department": "Culture",
        "topic": "Hosting",
        "hero": f"{SARDINE_ROOT}/sardines-breakfast-hero",
        "alt": "Open tin of sardines with grilled sourdough, a jammy egg, tomato, lemon, capers and espresso on ivory linen",
        "body": SARDINE_BODY,
        "keywords": ["sardines for breakfast", "sardines breakfast", "sardine toast breakfast", "canned fish breakfast ideas"],
        "reciprocal": {
            "path": "blogs/culture/how-to-serve-chilled-red-wine/index.html",
            "sentence": '<p>For the morning version of the same direct, ingredient-led table, our <a href="/blogs/culture/sardines-breakfast/">sardines for breakfast guide</a> builds seven plates around crispness, acidity and careful serving.</p>',
        },
    },
]
