"""Build the 12 August 2026 jelly heels and subtle cat-eye features."""

from __future__ import annotations

import html
import json
from pathlib import Path

import build_august_two_features as base


ROOT = Path(__file__).resolve().parents[1]
PUBLISHED = "2026-08-12"
PUBLISHED_LABEL = "12 August 2026"
PUBLISHED_ISO = "2026-08-12T15:00:00+02:00"

base.PUBLISHED = PUBLISHED
base.PUBLISHED_LABEL = PUBLISHED_LABEL
base.PUBLISHED_ISO = PUBLISHED_ISO


def picture(root: str, name: str, alt: str) -> str:
    return f'''<figure class="media article-inline-image"><picture><source type="image/webp" srcset="{root}/{name}-640.webp 640w, {root}/{name}-960.webp 960w, {root}/{name}.webp 1536w" sizes="(max-width: 760px) calc(100vw - 2rem), 760px"><img src="{root}/{name}.jpg" width="1536" height="1024" loading="lazy" decoding="async" alt="{html.escape(alt)}"></picture></figure>'''


JELLY_URL = "/blogs/fashion/jelly-kitten-heels/"
JELLY_TITLE = "Jelly Kitten Heels: The Beautiful Shoe With a Practical Problem"
JELLY_SEO = "Jelly Kitten Heels: How to Wear the 2026 Shoe Trend"
JELLY_DESCRIPTION = "Jelly kitten heels are 2026's breakout shoe. Learn how to check the fit, prevent rubbing, style them well and keep translucent pairs looking clear."
JELLY_ROOT = "/assets/images/blogs/fashion/jelly-kitten-heels"
JELLY_HERO = f"{JELLY_ROOT}/jelly-kitten-heels-hero"

jelly_body = f'''<div class="article-layout"><aside class="article-aside"><p class="kicker">The jelly heel file</p><ol><li><a href="#answer">The short answer</a></li><li><a href="#why-now">Why now</a></li><li><a href="#definition">What counts</a></li><li><a href="#fit">The fitting-room test</a></li><li><a href="#friction">Rubbing and blisters</a></li><li><a href="#style">Six outfit formulas</a></li><li><a href="#quality">Quality and care</a></li></ol><button class="copy-link" data-copy-link type="button">Copy link</button></aside><div class="article-body">
<p class="article-opening">The best jelly kitten heels have a low, stable heel, a softly flexible upper and enough room for the foot to expand in warm weather. Style them as the only playful element in an otherwise grown-up outfit: dry tailoring, dark denim, a plain column dress or a fluid skirt. If a pair pinches while you are standing still, it will not become kinder during a hot walk.</p>
<p>Jelly shoes have escaped the beach. Google&rsquo;s Summergeist report names &ldquo;jelly kitten heels&rdquo; as a breakout search and jelly slides as the top-trending slide type, with red the most searched jelly-shoe colour. Chlo&eacute;&rsquo;s Spring/Summer 2026 runway placed translucent kitten heels beneath soft dresses and tailoring, giving a childhood material an adult silhouette. The idea is witty. The material can be unforgiving. That tension is the entire trend.</p>
<div class="summary-box" id="answer"><p class="kicker">The concise answer</p><h2>Buy them for the finish, but judge them by the walk</h2><p>Look for a smooth interior, a heel fixed squarely beneath your weight and an upper that holds the foot without cutting across it. Try them late in the day, walk on hard flooring and reject any pair that makes the toes grip to keep the shoe on. Wear them first for an hour close to home. A clear or oxblood pair with quiet clothes looks modern; too many nostalgic details make the outfit read like a theme.</p></div>

<section id="why-now"><h2>Why jelly kitten heels suddenly make sense</h2><p>The kitten heel has already spent several seasons replacing higher, more declarative pumps. Jelly changes its tone. Instead of ladylike leather, the translucent upper catches light, reveals the construction and makes a conventional shape slightly strange. It is glamour with a sense of humour, which explains why the shoe feels more current than a literal revival of the jelly sandal.</p><p>There is also a practical visual reason. Summer outfits rely on fewer layers, so texture has to do more work. A smoked-cherry or amber shoe gives a white shirt and black trouser the same small jolt that coloured glass gives a plain table. The material looks especially effective beside linen, dry wool, washed denim and matte cotton because those surfaces resist its shine.</p><p>Current coverage in British Vogue, Harper&rsquo;s Bazaar and Marie Claire has concentrated on the runway return and the pleasure of the look. The unanswered question is whether the pair in your hand is made well enough to survive actual pavements. &ldquo;Jelly&rdquo; describes an appearance, not one universal composition. Retailers may use PVC, TPU or other flexible plastics and blends. Read the product listing, particularly if material, recycling or allergy concerns affect your decision.</p></section>

<section id="definition"><h2>What counts as a jelly kitten heel?</h2><p>It needs two things. The upper, heel or both should have the translucent, moulded quality associated with jelly footwear, and the heel should be low and narrow enough to create the lifted line of a kitten heel. A completely flat fisherman sandal is a jelly shoe, but not a jelly kitten heel. A clear vinyl stiletto with a high heel belongs to another family.</p><h3>The strongest 2026 shapes</h3><p>The most convincing versions are restrained: a two-strap mule, a softly squared peep toe, a neat slingback or a minimal cage sandal with a heel around three to five centimetres. They reveal enough foot to keep the material light. Dense uppers, thick platforms and heavy embellishment can make the plastic look clumsy rather than clever.</p><p>Colour changes the level of formality. Clear smoke and pale amber behave almost like neutrals. Oxblood, tomato red and deep brown make the shoe look more intentional and hide clouding better. Sugary pink, glitter and neon can be enjoyable, but they require especially sober clothing if the goal is polish rather than nostalgia.</p></section>

{picture(JELLY_ROOT, "jelly-kitten-heels-construction", "Translucent oxblood jelly kitten-heel mule on a scratched steel worktable showing its moulded upper and low heel")}

<section id="fit"><h2>The five-minute fitting-room test</h2><p>Do not evaluate this shoe while perched on a carpeted bench. Put on both feet, stand on a hard surface and give the material time to warm slightly. Feet often swell through the day, which is why late-afternoon fitting is more informative than a quick morning try-on.</p><ol><li><strong>Check the edge.</strong> Run a finger around every opening. A sharp ridge, exposed seam or hard flash of moulded material is a likely friction point.</li><li><strong>Look at toe pressure.</strong> The toes should lie naturally rather than bunching or pushing visibly against a clear strap.</li><li><strong>Watch the heel.</strong> From behind, it should sit upright and land cleanly. If it bends sideways during a slow step, leave the pair.</li><li><strong>Listen to your toes.</strong> If they curl to stop a mule sliding away, the upper is not holding you securely. Gripping changes the walk and tires the foot.</li><li><strong>Test heat and suction.</strong> After several minutes, notice trapped moisture or a suction sound beneath the sole. Neither improves during a long summer day.</li></ol><p>A slingback should remain in place without sawing into the heel. A mule needs enough upper coverage to hold the forefoot, but not a strap positioned across the widest joint. The best size may differ from your usual leather shoe because flexible plastic stretches and rebounds differently.</p><h3>Perform the stair and corner test</h3><p>Walk quickly, turn sharply, climb a stair if the shop allows it and stop without shuffling. The heel should not wobble and the shoe should not lag behind the foot. If you are buying online, keep the protective film intact and repeat the test on a clean indoor surface while the return window remains open.</p></section>

<section id="friction"><h2>The practical problem: heat, friction and blisters</h2><p>Plastic does not absorb moisture like many natural linings. Warm skin, a snug edge and repeated movement can create friction. The NHS notes that most blisters are caused by friction and advises wearing well-fitting footwear, breaking in new shoes for short periods and avoiding the shoe that caused a blister until it has healed.</p><p>Start with a one-hour wear near home. Keep the route cool and dry. If a specific edge begins to rub, stop rather than treating pain as the cost of breaking the pair in. A pharmacist can advise on blister dressings, including hydrocolloid options. This article is not medical advice, and persistent pain, broken skin or signs of infection deserve proper care.</p><p>Transparent gel pads are not automatically invisible beneath a jelly upper. More importantly, a pad can reduce internal space and move pressure elsewhere. Apply only a small one after testing it indoors. Do not coat the inside of the shoe with oils or powders that can degrade the material, stain it or make the foot slide.</p><h3>Who should probably skip the trend</h3><p>If you already know that non-breathable shoes irritate your skin, if your feet need prescription support or if every strap lands on a sensitive joint, this is not a trend worth negotiating with. The visual effect can be borrowed through a translucent bag, resin cuff or coloured-glass earring. Style has no prize for enduring the wrong shoe.</p></section>

<section id="style"><h2>Six jelly heels outfits that look adult</h2><div class="article-table-wrap" role="region" aria-label="Six ways to style jelly kitten heels" tabindex="0"><table class="article-visual-table"><thead><tr><th>Shoe</th><th>Clothes</th><th>Why it works</th></tr></thead><tbody><tr><td>Clear smoke mule</td><td>Black capri trouser, ivory poplin shirt</td><td>The shoe lightens a strict two-colour uniform</td></tr><tr><td>Oxblood slingback</td><td>Dark indigo jeans, fine grey knit</td><td>Deep colour reads closer to polished leather</td></tr><tr><td>Amber peep toe</td><td>White linen midi dress, brown belt</td><td>Warm transparency connects linen and leather</td></tr><tr><td>Tomato-red cage heel</td><td>Stone Bermuda shorts, navy shirt</td><td>One bright punctuation mark, no competing novelty</td></tr><tr><td>Black translucent mule</td><td>Bias-cut black skirt, washed cotton tee</td><td>Mixed sheen gives monochrome depth</td></tr><tr><td>Brown jelly slingback</td><td>Khaki utility trouser, cream vest</td><td>A playful material softens functional clothes</td></tr></tbody></table></div>
<p>The capri formula is the cleanest entry point. A cropped hem leaves a small interval between trouser and shoe, so the translucent heel can be read without the ankle becoming visually crowded. Keep the trouser tailored rather than skin-tight. The proportion is closely related to the neat exposed ankle in our <a href="/blogs/fashion/summer-loafers-outfit-guide/">summer loafers guide</a>.</p><p>With a dress, avoid stacking nostalgic signals. A smocked mini, beaded bag, jelly heel and hair bow tell the same story four times. Choose a column, shirt or bias-cut dress instead. The contrast between a disciplined line and a playful shoe is what makes the result feel editorial.</p><p>For a holiday wardrobe, use the heels after sunset and keep a flat walking shoe in the daytime. They can complement the raffia, stripes and relaxed trousers in our <a href="/blogs/fashion/european-summer-style-2026/">European summer wardrobe</a>, but the outfit should never feel assembled from trend labels. If you want another small, high-impact accessory, our <a href="/blogs/fashion/how-to-wear-a-scarf-belt/">scarf belt guide</a> explains how to control colour and proportion.</p></section>

{picture(JELLY_ROOT, "jelly-kitten-heels-evening", "Burgundy translucent jelly kitten heels worn with a black satin midi skirt on damp pavement at blue hour")}

<section id="quality"><h2>How to tell considered jelly heels from disposable ones</h2><p>Hold the pair at eye level. The two heels should match in height and angle. Set them on a flat table and press gently at the back; excessive rocking suggests an uneven base. Flex the forefoot, not the arch, and look for whitening where the material bends. Examine attachment points for bubbles, lifted edges and glue residue.</p><p>A stronger design usually has a separate outsole with visible tread, an insole that does not lift at the corners and a heel tip that can be replaced. The product page should disclose the upper, lining and sole materials rather than calling everything simply &ldquo;jelly.&rdquo; It should also provide a size guide and return policy. Price alone proves none of these things.</p><h3>Cleaning without creating cloudiness</h3><p>After wearing, wipe the shoes with a barely damp soft cloth and remove grit from the tread. Let them dry away from a radiator and direct sun. Store them separately in a breathable cloth bag so darker material cannot transfer colour to a clear pair. Avoid alcohol, acetone, perfume and aggressive household cleaners. Test any recommended cleaner on a hidden area first.</p><p>Do not leave the shoes compressed under other footwear or in a hot car. Flexible plastics can distort with heat. If the maker supplies specific care instructions, follow those over a generic method. A small amount of ordinary wear looks believable; yellowing, deep scratches and a tilted heel do not.</p></section>

<section class="article-faq"><h2>Jelly kitten heel questions</h2><h3>Are jelly heels comfortable?</h3><p>They can be comfortable for short wear if the fit is secure and the edges are smooth, but the material may trap heat and create friction. Comfort varies by construction and foot. Test both shoes on a hard surface and begin with a short outing.</p><h3>How do you stop jelly shoes from rubbing?</h3><p>Choose the correct fit, wear them for short periods at first and stop when a hot spot develops. A small protective dressing may help in one area, but padding cannot correct a badly positioned strap or unstable heel.</p><h3>What do you wear with jelly kitten heels?</h3><p>Pair them with matte, structured clothes such as cropped trousers, dark denim, a plain shirt dress or a black bias skirt. Let the translucent shoe be the only obviously playful element.</p><h3>Will clear jelly shoes turn yellow?</h3><p>Some transparent materials can discolour with age, heat, ultraviolet exposure or contact with chemicals. Material quality and care differ, so check the maker&rsquo;s instructions and store clear pairs away from direct sun.</p></section>

<section class="source-note"><h2>Sources and editorial notes</h2><p>Search-interest facts were checked on 12 August 2026 against <a href="https://trends.withgoogle.com/trends/summergeist/">Google Summergeist</a>. Runway and styling context was reviewed in <a href="https://www.vogue.co.uk/article/jelly-heel-trend">British Vogue</a>, <a href="https://www.harpersbazaar.com/fashion/trends/a70966900/how-to-style-jelly-shoes/">Harper&rsquo;s Bazaar</a> and <a href="https://www.marieclaire.co.uk/fashion/jelly-heels">Marie Claire UK</a>. The reported rise in demand was cross-checked with <a href="https://corq.studio/insights/fashion-forward-demand-for-jelly-kitten-heels-is-350-yoy-ahead-of-peak-summer/">CORQ</a>. Friction and blister-care guidance comes from the <a href="https://www.nhs.uk/conditions/blisters/">NHS</a>. Material, styling and buying recommendations are by.foro editorial analysis. The photographs are original, fictional editorial images created for this article.</p></section>
<section><h2>The shoe succeeds when the joke is quiet</h2><p>Jelly kitten heels are appealing because they place a slightly unserious material beneath a very exact silhouette. Keep the clothes calm, demand a good fit and give the shoe a real walk before trusting it. The best pair does not look like a nostalgic prop. It looks like a beautiful object that happens to be made from something unexpected.</p></section>
<div class="article-end"><span>End</span><p>Published by by.foro Editorial on 12 August 2026. For corrections, contact <a href="mailto:hello@byforo.com">hello@byforo.com</a>.</p></div></div></div>'''


CAT_URL = "/blogs/fashion/subtle-cat-eye-sunglasses/"
CAT_TITLE = "Subtle Cat-Eye Sunglasses: The Cat-Eye Without the Costume"
CAT_SEO = "Subtle Cat-Eye Sunglasses: The Complete 2026 Guide"
CAT_DESCRIPTION = "Find subtle cat-eye sunglasses that lift without looking retro. Compare frame shapes, fit, UV protection, colours and styling for a modern finish."
CAT_ROOT = "/assets/images/blogs/fashion/subtle-cat-eye-sunglasses"
CAT_HERO = f"{CAT_ROOT}/subtle-cat-eye-sunglasses-hero"

cat_body = f'''<div class="article-layout"><aside class="article-aside"><p class="kicker">The frame file</p><ol><li><a href="#answer">The short answer</a></li><li><a href="#definition">What subtle means</a></li><li><a href="#geometry">Read the geometry</a></li><li><a href="#fit">Fit before face shape</a></li><li><a href="#lenses">UV and lenses</a></li><li><a href="#colour">Colour and material</a></li><li><a href="#style">How to style them</a></li></ol><button class="copy-link" data-copy-link type="button">Copy link</button></aside><div class="article-body">
<p class="article-opening">Subtle cat-eye sunglasses have a gentle upward turn at the outer corners, moderate lens height and no exaggerated wing. The easiest pair to wear follows the brow rather than fighting it, sits level without touching the cheeks and extends only slightly beyond the widest part of the face. Ignore rigid face-shape rules until the bridge, frame width and temples fit.</p>
<p>Google&rsquo;s Summergeist report identifies &ldquo;subtle cat eye sunglasses&rdquo; as a breakout search. That qualifier matters. The 2026 version is not the sharp, tiny retro frame that dominates an outfit. It is closer to a softened oval or squoval with a quiet lift at the edge. The frame makes the eye line look alert, yet still works with a shirt, swimsuit or tailored jacket without turning each outfit into 1950s dress-up.</p>
<div class="summary-box" id="answer"><p class="kicker">The concise answer</p><h2>Look for a lift of millimetres, not a theatrical wing</h2><p>Choose a frame whose upper edge rises gently from bridge to temple. The outer point should sit near the brow tail rather than halfway to the hairline. Check that your pupils sit close to the lens centres, the bridge does not slide and the temples remain level. Then verify that the lenses are labelled UV400 or 100 percent UV protection. A darker tint is not proof of better protection.</p></div>

<section id="definition"><h2>What makes a cat-eye subtle?</h2><p>All cat-eye frames share an upswept outer corner. Subtle versions reduce the angle, the projection or both. Their lenses are often fuller than a narrow retro pair, and the lower rim may be softly rounded or almost square. From several steps away, the frame reads as balanced eyewear. The cat-eye becomes apparent only when you notice the direction of the upper line.</p><p>This softness explains the overlap with &ldquo;squoval&rdquo; sunglasses. A squoval frame combines a square&rsquo;s stability with an oval&rsquo;s rounded corners. Add a slight lift to its top edge and it becomes a restrained cat-eye. Current 2026 runway coverage from Who What Wear points to this middle ground, with softened shapes appearing at Coperni, Magda Butrym, Courr&egrave;ges and Givenchy.</p><p>The frame is useful because it provides direction without requiring a vintage wardrobe. A dramatic point can compete with brows, earrings and a strong collar. A quiet lift does the opposite: it organises those details.</p></section>

{picture(CAT_ROOT, "subtle-cat-eye-sunglasses-shapes", "Three unbranded sunglasses shapes on cream paper showing a soft cat-eye, dramatic cat-eye and squoval frame")}

<section id="geometry"><h2>Subtle cat-eye, dramatic cat-eye or squoval?</h2><div class="article-table-wrap" role="region" aria-label="Comparison of subtle cat-eye, dramatic cat-eye and squoval sunglasses" tabindex="0"><table class="article-visual-table"><thead><tr><th>Shape</th><th>Outer corner</th><th>Overall effect</th><th>Best use</th></tr></thead><tbody><tr><td>Subtle cat-eye</td><td>Small, smooth rise</td><td>Lifted and modern</td><td>Daily wear, tailoring, dresses</td></tr><tr><td>Dramatic cat-eye</td><td>Sharp projected wing</td><td>Graphic and deliberately retro</td><td>Simple evening looks, strong editorial styling</td></tr><tr><td>Squoval</td><td>Little or no rise</td><td>Stable, quiet and architectural</td><td>Minimal wardrobes, wider everyday coverage</td></tr></tbody></table></div>
<p>Photograph a candidate pair straight on, not at the flattering three-quarter angle used on many product pages. Trace an imaginary line from the bridge to each outer corner. A subtle pair climbs slowly. A dramatic frame accelerates sharply near the temple and often extends beyond the lens itself.</p><h3>Lens height is the hidden variable</h3><p>Two frames can have the same outer lift and feel completely different because one is narrow and the other is deep. A taller lens softens the cat-eye by adding visual weight below the eye. A narrow lens concentrates attention at the upper edge, making even a small point look severe. If you dislike a &ldquo;costume&rdquo; effect, moderate lens height is usually more important than choosing a neutral colour.</p></section>

<section id="fit"><h2>Fit matters more than the face-shape chart</h2><p>Most online guides begin by classifying faces as round, oval, square or heart-shaped. Those labels can be a loose visual prompt, but they do not tell you whether a bridge will slide, a temple will pinch or a lens will touch the cheek. Real faces combine widths and angles. Eyebrow height, nose bridge, cheek projection, prescription needs and hairstyle can change the result more than the outline of the jaw.</p><h3>Use four measurements</h3><ol><li><strong>Total frame width:</strong> compare it with a pair you already wear comfortably. The new frame should not squeeze at the temples or extend so far that it slips when you look down.</li><li><strong>Bridge width:</strong> this controls where the glasses sit. A bridge that is too wide slides; one that is too narrow can pinch and raise the frame unnaturally.</li><li><strong>Lens width and height:</strong> these determine coverage and whether your pupils sit near the optical centres.</li><li><strong>Temple length:</strong> the arms should curve behind the ears without pressing before they reach them.</li></ol><p>Numbers are often printed inside the temple in a sequence such as lens width, bridge width and temple length, measured in millimetres. Brand sizing is not perfectly consistent, so treat those figures as comparison points rather than a complete fit guarantee.</p><h3>The five-position mirror check</h3><p>Look straight ahead. The frame should sit level and the outer corners should not disappear into the hairline. Smile. The lower rims should not lift noticeably with the cheeks. Turn sideways. The arms should travel straight back rather than bowing outward. Look down for ten seconds. The bridge should hold. Finally, place a finger lightly under one temple and release it; a badly twisted frame may spring out of alignment.</p></section>

{picture(CAT_ROOT, "subtle-cat-eye-sunglasses-fit", "Rear close-up showing a tortoiseshell sunglasses temple resting level above the ear with the face outside the frame")}

<section id="lenses"><h2>Do not confuse darkness with UV protection</h2><p>The United States Food and Drug Administration advises choosing sunglasses labelled UV400 or 100 percent UV protection. It also notes that a light tint can offer the same ultraviolet protection as a very dark lens, and that price does not guarantee protection. The filter is in the lens construction, not the drama of the tint.</p><p>This matters with fashion frames because pale amber, grey and gradient lenses can look less serious than black ones. If they carry the correct protection claim from a reputable seller, the tint alone is not a reason to reject them. Conversely, a nearly black lens without a reliable UV statement should not be assumed safe.</p><p>Larger frames and wraparound styles can provide more coverage from light entering at the side. A subtle cat-eye does not need to be tiny. Look for enough lens area to cover the eye comfortably and consider a closer-fitting shape for strong sun, water or high-reflection environments. Sunglasses do not replace other sun protection.</p><h3>Polarisation solves a different problem</h3><p>Polarised lenses reduce certain reflected glare, which can be useful around water, roads and bright horizontal surfaces. Polarisation is not the same claim as ultraviolet protection. Check both separately. Also test phone, dashboard and payment screens, because some polarised lenses make particular displays difficult to read at certain angles.</p><p>If you need prescription lenses, ask an optician whether the frame&rsquo;s curve, depth and acetate thickness suit your prescription. A beautiful narrow frame may not leave enough usable lens area. Eye discomfort or vision questions belong with a qualified eye-care professional, not a trend guide.</p></section>

<section id="colour"><h2>Choose colour by contrast, not by complexion rules</h2><p>Black is the clearest graphic choice and makes a gentle cat-eye look more defined. Dark tortoiseshell softens the line and adds variation beside brown, navy, cream and denim. Smoky taupe can almost disappear against the face, which is useful if the shape itself is new to you. Oxblood and deep olive behave like unusual neutrals when the acetate is translucent rather than opaque.</p><p>Instead of asking whether a colour is universally &ldquo;right&rdquo; for your skin tone, look at the contrast already present in your features and wardrobe. If you wear crisp black and white, a fine black rim may feel coherent. If your clothes are mostly washed linen, tobacco suede and muted knits, amber tortoiseshell is less abrupt. Try the frame in daylight; shop lighting can make acetate warmer and lenses clearer than they appear outdoors.</p><h3>Material details that signal quality</h3><p>Open and close both arms. Hinges should move with similar resistance, without grinding or visible gaps. Set the frame upside down on a flat surface; both upper corners should touch evenly. Inspect the acetate for cloudy joins, rough edges and bubbles around the hinge. A small amount of variation in tortoiseshell is desirable. Identical printed repetition can make it look flat.</p><p>Check whether adjustments and replacement screws are available. A frame that can be fitted by an optician and repaired is more valuable than one that arrives perfectly photographed but cannot survive a loose hinge.</p></section>

<section id="style"><h2>How to wear a cat-eye without looking retro</h2><p>The easiest method is to remove the expected companions. Skip the headscarf, red lip, polka dot and fitted cardigan when wearing the frame. Pair it with a white men&rsquo;s shirt, a washed tee, an unstructured blazer or a long linen dress. The glasses supply the curve; the clothes supply resistance.</p><p>For a <a href="/blogs/fashion/european-summer-style-2026/">European summer wardrobe</a>, choose fine tortoiseshell with a blue shirt, cream pyjama trouser and flat leather sandal. The result refers to holiday dressing without becoming a social-media costume. With a strong shoulder, use a slightly fuller lens so the eyewear is not overwhelmed. Our <a href="/blogs/fashion/glamoratti-style-2026/">Glamoratti guide</a> uses the same balance between 1980s volume and controlled accessories.</p><p>Jewellery should relate to the frame&rsquo;s scale. A thin rim can take a sculptural earring; a thick black acetate frame often needs only a small stud or no earring at all. If the sunglasses are tortoiseshell, gold is the obvious metal, but silver creates a cooler and more contemporary interruption.</p><h3>Three reliable outfit formulas</h3><ul><li><strong>City:</strong> smoky cat-eye, charcoal trouser, white ribbed tank, oversized blue shirt and black flat.</li><li><strong>Holiday:</strong> fine tortoiseshell frame, ecru pyjama trouser, navy swimsuit and woven leather bag.</li><li><strong>Evening:</strong> black subtle cat-eye, collarless ivory jacket, dark denim and one gold cuff.</li></ul><p>The frame can also finish more personal celebrity-inspired dressing without copying an entire look. Our analysis of <a href="/blogs/fashion/celebrity-style-is-getting-personal/">why celebrity style is getting personal again</a> explains why one recognisable decision is more persuasive than a full aesthetic package.</p></section>

<section><h2>How to buy sunglasses online without guessing</h2><p>Start with a pair that fits. Record the three temple numbers, then measure the total width across the front because that figure is not always listed. Photograph them straight on next to a ruler. Compare bridge style as well as width: a keyhole bridge and a saddle bridge can sit differently even when the printed number matches.</p><p>On the product page, look for front, side and folded views; exact measurements; UV information; lens material; return conditions; and a model image that states frame size. A virtual try-on can estimate the look, but it cannot tell you pressure, weight or whether the frame touches your cheeks. Keep the tags attached until you have tested the pair in daylight and worn it indoors for at least fifteen minutes.</p><p>When the parcel arrives, check that straight lines do not appear distorted through the lenses. Mild curvature can alter the view at the edge, but strong rippling, headache or discomfort is a reason to stop wearing them and consult the seller or an optician.</p></section>

<section class="article-faq"><h2>Subtle cat-eye sunglasses questions</h2><h3>What are subtle cat-eye sunglasses?</h3><p>They are sunglasses with gently upswept outer corners rather than a long, sharp wing. Moderate lens height and a softly curved lower rim make the shape easier to wear every day.</p><h3>Do cat-eye sunglasses suit every face shape?</h3><p>There is no useful universal rule. A restrained cat-eye can work on many faces when the total width, bridge, lens position and temples fit. Use face-shape advice as inspiration, not a substitute for measurements.</p><h3>Are subtle cat-eye sunglasses still trendy in 2026?</h3><p>Yes. Google listed the phrase as a breakout search in Summergeist, while current runway coverage shows softened cat-eye and squoval frames across several 2026 collections.</p><h3>What UV protection should sunglasses have?</h3><p>Look for a reliable label stating UV400 or 100 percent UV protection. Lens darkness and price do not by themselves confirm ultraviolet protection.</p></section>

<section class="source-note"><h2>Sources and editorial notes</h2><p>Search-interest facts were checked on 12 August 2026 against <a href="https://trends.withgoogle.com/trends/summergeist/">Google Summergeist</a>. Current shape and styling context was reviewed in <a href="https://www.glamourmagazine.co.uk/article/best-subtle-cat-eye-sunglasses">Glamour UK</a>, <a href="https://www.whowhatwear.com/fashion/trends/sunglasses-trends-2026-uk">Who What Wear</a> and <a href="https://www.warbyparker.com/learn/cat-eye-sunglasses-retro-angles-everyday-wear">Warby Parker&rsquo;s frame guide</a>. UV and lens guidance comes from the <a href="https://www.fda.gov/consumers/consumer-updates/tips-stay-safe-sun-sunscreen-sunglasses">US Food and Drug Administration</a> and its <a href="https://www.fda.gov/regulatory-information/search-fda-guidance-documents/guidance-document-nonprescription-sunglasses-guidance-industry">nonprescription sunglasses guidance</a>. Fit and styling recommendations are by.foro editorial analysis. The photographs are original, fictional editorial images created for this article.</p></section>
<section><h2>The best cat-eye is felt before it is noticed</h2><p>A subtle frame does not need to advertise its reference. It should lift the line of the face, sit securely and protect the eyes, then disappear into the rhythm of what you already wear. That is what makes the 2026 cat-eye useful: less costume, more structure.</p></section>
<div class="article-end"><span>End</span><p>Published by by.foro Editorial on 12 August 2026. For corrections, contact <a href="mailto:hello@byforo.com">hello@byforo.com</a>.</p></div></div></div>'''


ARTICLES = [
    dict(url=JELLY_URL, seo=JELLY_SEO, title=JELLY_TITLE, description=JELLY_DESCRIPTION, deck="The translucent heel is 2026's prettiest contradiction. Before buying one, test the edge, the heat and the walk.", department="Fashion", topic="Accessories", hero=JELLY_HERO, alt="Faceless summer outfit with black cropped trousers and translucent red jelly kitten heels on worn limestone", body=jelly_body, words=2100, keywords=["jelly kitten heels", "jelly heels trend 2026", "how to style jelly shoes", "are jelly heels comfortable"]),
    dict(url=CAT_URL, seo=CAT_SEO, title=CAT_TITLE, description=CAT_DESCRIPTION, deck="The modern cat-eye lifts by degrees, not drama. Here is how to judge its geometry, fit, lenses and place in a real wardrobe.", department="Fashion", topic="Accessories", hero=CAT_HERO, alt="Black, tortoiseshell and smoky taupe subtle cat-eye sunglasses arranged on travertine and brown silk", body=cat_body, words=2050, keywords=["subtle cat eye sunglasses", "soft cat eye sunglasses", "cat eye sunglasses trend 2026", "modern cat eye sunglasses"]),
]


def write_pages() -> None:
    for item in ARTICLES:
        document = base.page(item["url"], item["seo"], item["title"], item["description"], item["deck"], item["department"], item["topic"], item["hero"], item["alt"], item["body"], "BlogPosting", item["words"], item["keywords"])
        destination = ROOT / item["url"].strip("/") / "index.html"
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(document, encoding="utf-8", newline="\n")
        print(f"Built {destination.relative_to(ROOT)}")


def update_catalogue() -> None:
    path = ROOT / "content/articles.json"
    current = json.loads(path.read_text(encoding="utf-8"))
    additions = []
    for item in ARTICLES:
        additions.append({
            "title": item["title"], "seoTitle": item["seo"], "department": item["department"].lower(),
            "topic": item["topic"].lower(), "published": PUBLISHED, "readingMinutes": round(item["words"] / 195),
            "readingWordsPerMinute": 195, "url": item["url"], "excerpt": html.unescape(item["deck"]),
            "metaDescription": item["description"],
            "image": {"webp": f'{item["hero"]}.webp', "fallback": f'{item["hero"]}.jpg', "alt": item["alt"], "width": 1536, "height": 1024},
            "articleSection": item["topic"], "breadcrumbTopic": True,
        })
    urls = {item["url"] for item in additions}
    path.write_text(json.dumps(additions + [item for item in current if item["url"] not in urls], ensure_ascii=False, indent=2) + "\n", encoding="utf-8", newline="\n")


def main() -> None:
    write_pages()
    update_catalogue()


if __name__ == "__main__":
    main()
