"""Build three by.foro cluster features for 5 September 2026."""

from __future__ import annotations

import html
import json
import re
from pathlib import Path

import build_august_two_features as base


ROOT = Path(__file__).resolve().parents[1]
PUBLISHED = "2026-09-05"
PUBLISHED_LABEL = "5 September 2026"
PUBLISHED_ISO = "2026-09-05T10:00:00+02:00"
base.PUBLISHED = PUBLISHED
base.PUBLISHED_LABEL = PUBLISHED_LABEL
base.PUBLISHED_ISO = PUBLISHED_ISO


def picture(root: str, name: str, alt: str) -> str:
    return f'''<figure class="media article-inline-image"><picture><source type="image/webp" srcset="{root}/{name}-640.webp 640w, {root}/{name}-960.webp 960w, {root}/{name}.webp 1536w" sizes="(max-width: 760px) calc(100vw - 2rem), 760px"><img src="{root}/{name}.jpg" width="1536" height="1024" loading="lazy" decoding="async" alt="{html.escape(alt)}"></picture></figure>'''


NECKLACE_URL = "/blogs/fashion/kitchen-sink-necklace/"
NECKLACE_ROOT = "/assets/images/blogs/fashion/kitchen-sink-necklace"
NECKLACE_TITLE = "The Kitchen-Sink Necklace, Without the Junk-Drawer Effect"
NECKLACE_SEO = "Kitchen-Sink Necklace Trend 2026: How to Wear It"
NECKLACE_DESCRIPTION = "Learn how to build and wear a kitchen-sink necklace with charms, medallions and keepsakes while keeping the fall 2026 jewellery trend intentional."
NECKLACE_DECK = "The season's fullest necklace works when the objects are personal, the chain is simple and one decision holds the apparent chaos together."
NECKLACE_BODY = f'''<div class="article-layout"><aside class="article-aside"><p class="kicker">The assembly guide</p><ol><li><a href="#answer">The short answer</a></li><li><a href="#why">Why it is rising</a></li><li><a href="#edit">The editing rule</a></li><li><a href="#build">Build the necklace</a></li><li><a href="#outfits">Six outfit formulas</a></li><li><a href="#problems">Fix common problems</a></li><li><a href="#care">Weight and care</a></li></ol><button class="copy-link" data-copy-link type="button">Copy link</button></aside><div class="article-body">
<p class="article-opening">A kitchen-sink necklace is a long, deliberately crowded necklace carrying an eclectic mix of charms, medallions, shells, letters, found objects and small keepsakes. To make it look intentional, use one plain chain, choose one dominant metal or colour and leave a little space between objects. Wear it over a quiet neckline and let it be the only complicated part of the outfit.</p>
<p>The name suggests indiscriminate accumulation. The good version is more precise. A brass saint medal can sit beside a silver key, a shell and an enamel fruit, but the eye still needs a route through them. Scale, spacing or colour must repeat somewhere. Without that rhythm, the necklace reads as a drawer emptied onto a cord. With it, unrelated objects begin to look like a private archive.</p>
<p>That tension is exactly why the idea feels current. Vogue identified the &ldquo;everything and the kitchen sink necklace&rdquo; in its fall 2026 runway report, citing the DIY spirit of charm-heavy pieces at Celine and Marni. Its September accessories update returned to long bohemian necklaces at Altuzarra, Celine, Marni and Dries Van Noten. The trend is maximal, but its real subject is personal selection rather than generic excess.</p>
<div class="summary-box" id="answer"><p class="kicker">The concise answer</p><h2>Choose one anchor, one rhythm and one quiet background</h2><p>Start with a 60-to-80-centimetre chain and one anchor charm roughly the size of a large coin. Add three to seven smaller objects that repeat either its metal, colour or shape. Keep the heaviest pieces near the centre, test the necklace while walking and remove anything that turns rather than hangs. Wear it over a crew neck, button-down, plain knit or simple dress with no competing earrings.</p></div>
<section id="why"><h2>Why the kitchen-sink necklace feels new now</h2><p>Charm necklaces are not new, and that is part of their appeal. A bracelet charm from childhood, a travel token and a pendant bought last week can occupy the same chain without pretending to share an origin. Fall 2026 styling makes that accumulation visible instead of hiding it inside a jewellery box.</p><p>The runway version is longer and less polished than the neat charm chains of recent seasons. Vogue's September report describes medallions, letters, shells and horns piled over knits and button-downs. The length matters. Once the objects fall below the collarbone, the necklace behaves more like a narrow vertical layer than a conventional piece of jewellery.</p><p>It also extends a larger shift already visible across by.foro's accessories coverage: the return of pieces that can be rearranged and interpreted. A <a href="/blogs/fashion/mahjong-necklace-meaning/">mahjong pendant</a> carries meaning in one object; <a href="/blogs/fashion/bandana-jewellery/">bandana jewellery</a> changes the chain itself; a kitchen-sink necklace turns the full collection into the message.</p><h3>Personal does not have to mean precious</h3><p>An object earns its place through shape, memory or visual use, not market value. A button can be more convincing than a gemstone if it repeats the warm brown of the coat beneath it. A small hotel key tag may matter more than a newly purchased &ldquo;vintage-inspired&rdquo; charm. The necklace looks strongest when at least one item could not have been chosen by an algorithm.</p></section>
{picture(NECKLACE_ROOT, "kitchen-sink-necklace-charms", "Vintage medallions, a small key, shell, enamel fruit and mismatched metal charms being arranged beside a long dark chain on worn oak")}
<section id="edit"><h2>The editing rule: repeat one thing, vary the rest</h2><p>A crowded necklace needs a quiet form of repetition. Choose one variable to control and allow the others to move. If most pieces are mixed metals, repeat rounded shapes. If shapes range from keys to shells and letters, keep the palette largely brass. If colour is the attraction, use a simple dark cord and similar spacing.</p><div class="article-table-wrap" role="region" aria-label="Kitchen-sink necklace editing rules" tabindex="0"><table class="article-visual-table"><thead><tr><th>Control</th><th>Let vary</th><th>Result</th></tr></thead><tbody><tr><td>Mostly one metal</td><td>Shape, age and subject</td><td>Rich but coherent</td></tr><tr><td>Repeated round shapes</td><td>Metal and colour</td><td>Eclectic with rhythm</td></tr><tr><td>One colour family</td><td>Material and scale</td><td>Playful, not random</td></tr><tr><td>Even spacing</td><td>Almost everything else</td><td>Graphic and readable</td></tr></tbody></table></div><p>Do not try to control every variable. Matching the metal, shape, colour, age and finish turns the necklace back into a coordinated set. The interest comes from difference; the editing rule simply prevents that difference from becoming visual noise.</p><h3>Choose an anchor before the supporting cast</h3><p>The anchor is the piece the eye finds first. It may be the largest medallion, the palest shell or the only coloured charm. Place it at or just below the centre, then build asymmetrically around it. Perfect symmetry can make found objects look mass-produced. A one-charm difference between the two sides usually feels more natural.</p></section>
<section id="build"><h2>How to build one from jewellery you already own</h2><ol><li><strong>Lay out every candidate.</strong> Include pendants, single earrings, keys, ribbons and small brooches with secure loops, but exclude anything sharp, fragile or impossible to clean.</li><li><strong>Choose the chain by weight.</strong> A fine chain can hold two light charms; a full arrangement needs a stronger curb, belcher or cable link. Check the clasp as carefully as the links.</li><li><strong>Set the anchor.</strong> Put the largest or most meaningful object near the centre and test where it falls against a plain top.</li><li><strong>Add in odd numbers.</strong> Three, five or seven supporting objects are easier to stagger than a matched pair on either side.</li><li><strong>Create breathing room.</strong> Leave enough link between objects for each silhouette to remain visible. Crowded does not mean fused.</li><li><strong>Perform the movement test.</strong> Walk, sit and bend. Remove the charm that flips, strikes another loudly or pulls the whole chain sideways.</li></ol><p>Use removable jump rings or small locking connectors if you want the arrangement to change. Permanent soldering is safer for valuable pieces but removes the playful, evolving quality of the trend. Ask a jeweller to assess antique or sentimental objects before altering them.</p><h3>Know what the symbols say</h3><p>Not every found object is neutral. Religious medals, military insignia, cultural symbols and game pieces may carry meanings beyond their graphic appeal. Research an unfamiliar object before wearing it. The same principle matters with <a href="/blogs/fashion/mahjong-necklace-meaning/">mahjong jewellery</a>: understanding the symbol makes the styling more personal, not less.</p></section>
<section id="outfits"><h2>Six outfits that give the necklace enough room</h2><h3>1. Grey crew-neck knit and dark trousers</h3><p>Let the necklace sit entirely on the knit rather than crossing the neckline. Grey accommodates silver, brass and colour without making any one metal look accidental. Keep the shoe simple and the bag hardware quiet.</p><h3>2. White shirt, buttoned high</h3><p>Wear a long chain over a crisp shirt, with the collar acting as a frame. The contrast between orderly cloth and irregular objects is the point. Skip a scarf, brooch and statement cuff.</p><h3>3. Black column dress</h3><p>A plain knitted or jersey dress turns the necklace into a vertical line. Choose a length that ends above the waist seam, or remove the belt so the two horizontals do not compete.</p><h3>4. Denim shirt and tailored coat</h3><p>Blue denim prevents antique brass from looking ceremonial. Keep the necklace inside the open coat so its edges create a second frame. This formula also works with the restrained approach in our <a href="/blogs/fashion/how-to-wear-turquoise-accessories/">turquoise accessories guide</a>.</p><h3>5. Soft blouse with a bare neckline</h3><p>Choose fewer, lighter charms and let the chain touch skin. Avoid lace, ruching or a bow at the same height. The blouse can be romantic; its neckline must remain visually clear.</p><h3>6. T-shirt and blazer</h3><p>This is the lowest-risk formula. A washed T-shirt absorbs the DIY quality while a tailored jacket supplies structure. If the lapel still needs something, use a tiny quiet pin rather than the <a href="/blogs/fashion/textured-brooch-trend/">oversized textured brooch</a> you would wear on another day.</p></section>
{picture(NECKLACE_ROOT, "kitchen-sink-necklace-outfit", "Long mixed-charm necklace worn over a plain charcoal crew-neck knit beneath an open camel coat, cropped from chin to hip on a real city pavement")}
<section id="problems"><h2>Why a crowded necklace sometimes looks wrong</h2><h3>Every charm is trying to be the anchor</h3><p>If four objects are equally large, bright and detailed, the eye cannot decide where to rest. Keep one, move one to another chain and replace the others with flatter supporting pieces. The discarded charms are not failures; they may become the beginning of a second necklace.</p><h3>The chain disappears</h3><p>A chain that is too fine makes heavy objects seem suspended and anxious. Choose links visible enough to belong to the composition. Conversely, an enormous chain plus many charms can look industrial. One element should supply the mass; the other should carry it.</p><h3>The necklace fights the neckline</h3><p>Do not let the anchor repeatedly cross a V-neck, lapel edge or button placket. Shorten or lengthen the chain until the pendant lands clearly on skin or cloth. A five-centimetre change often fixes an outfit more effectively than replacing any charm.</p><h3>Everything looks newly bought</h3><p>Uniform patina, identical jump rings and a ready-made story can make eclectic jewellery feel strangely impersonal. Mix in one piece you already own and allow modest wear to remain. Do not artificially damage new metal or misrepresent reproduction objects as antique.</p></section>
<section id="care"><h2>Weight, skin and garment care matter</h2><p>Weigh the complete necklace if it begins to pull. There is no universal comfortable number: chain thickness, object distribution, neckline and individual sensitivity all matter. The useful test is whether you forget the piece for ten minutes. Persistent pressure at the back of the neck, red skin or a clasp rotating forward means the arrangement needs fewer objects or a different chain.</p><p>Mixed metals may react differently to moisture and cleaning products. Wipe pieces individually with a soft dry cloth, keep plated and porous objects away from aggressive dips and do not soak shells, glued stones, pearls, painted enamel or paper inclusions. Store the necklace flat with its charms separated so chains do not knot and hard edges do not scratch softer surfaces.</p><p>Before converting a brooch or antique pendant, inspect every loop. A connector is only as secure as the thinnest old ring attached to it. For valuable or irreplaceable pieces, let a professional jeweller add a reversible bail.</p></section>
<section class="article-faq"><h2>Kitchen-sink necklace questions</h2><h3>What is a kitchen-sink necklace?</h3><p>It is a long, eclectic necklace carrying multiple charms, medallions and small objects. The fall 2026 version is deliberately abundant and often mixes shapes, eras and materials.</p><h3>How many charms should it have?</h3><p>Begin with one anchor and three supporting charms. Add up to seven if the chain remains balanced and each object is still visible. More is possible, but weight and noise become practical limits.</p><h3>Can you mix gold and silver charms?</h3><p>Yes. Repeat at least one of the metals twice and keep another element consistent, such as rounded shapes or even spacing. One isolated silver charm on an otherwise brass necklace can look accidental.</p><h3>Can it be worn with other jewellery?</h3><p>Use small earrings and one quiet ring or bracelet. Avoid another statement necklace and keep the lapel free. The crowded necklace needs to remain the outfit's only complicated sentence.</p></section>
<section class="source-note"><h2>Sources and image note</h2><p>Runway context was reviewed in Vogue's <a href="https://www.vogue.com/article/the-best-fall-2026-accessory-trends">March 2026 fall accessory report</a> and its <a href="https://www.vogue.com/article/fall-2026-accessory-trends">4 September fall accessories update</a>. Styling, assembly, symbolism and care guidance is by.foro editorial analysis. Antique and sentimental pieces should be assessed by a qualified jeweller before alteration. The photographs show fictional, unbranded jewellery scenes created for this article.</p></section>
<section><h2>The best version should keep changing</h2><p>A kitchen-sink necklace is not finished when the clasp closes. Remove the charm that annoys you, add the object that acquires a story and change the chain when the weight changes. Its coherence comes from one person's editing over time. That is why the necklace can be full without feeling generic.</p></section><div class="article-end"><span>End</span><p>Published by by.foro Editorial on 5 September 2026. For corrections, contact <a href="mailto:hello@byforo.com">hello@byforo.com</a>.</p></div></div></div>'''


GREEK_URL = "/blogs/home/greek-chic-interiors/"
GREEK_ROOT = "/assets/images/blogs/home/greek-chic-interiors"
GREEK_TITLE = "Greek Chic Interiors, Without the Holiday-Villa Theme"
GREEK_SEO = "Greek Chic Interiors: How to Get the Look in 2026"
GREEK_DESCRIPTION = "Create Greek chic interiors at home with limewash, stone, linen, timber and softened blue while avoiding nautical clichés and ancient-temple pastiche."
GREEK_DECK = "Chalky walls, worn stone and washed linen can hold onto Mediterranean light long after summer. The room does not need a bust or a blue stripe."
GREEK_BODY = f'''<div class="article-layout"><aside class="article-aside"><p class="kicker">The material guide</p><ol><li><a href="#answer">The short answer</a></li><li><a href="#meaning">What Greek chic means</a></li><li><a href="#palette">Build the palette</a></li><li><a href="#materials">The five materials</a></li><li><a href="#rooms">Room-by-room ideas</a></li><li><a href="#small">Small homes and rentals</a></li><li><a href="#avoid">What to leave out</a></li></ol><button class="copy-link" data-copy-link type="button">Copy link</button></aside><div class="article-body">
<p class="article-opening">Greek chic interiors combine warm chalky white, sun-softened stone, washed linen, aged timber and a small amount of sea or mineral blue. The modern version is elemental rather than themed: use three natural material families, soften the light and add one sculptural form. Avoid matching blue-and-white accessories, literal temple motifs and shelves of seaside objects.</p>
<p>The distinction is important because Mediterranean decorating has acquired a costume box. Lemons, stripes, shells, amphora reproductions and brilliant cobalt can each be beautiful. When all arrive together, the room begins to sell a destination instead of creating a place to live.</p>
<p>Greek chic is the quieter alternative emerging in late summer 2026. Ideal Home described it as a breakout microtrend built from crisp white, marble and sun-washed natural materials. Good Homes connected the renewed interest to the rougher visual world surrounding Christopher Nolan's <em>The Odyssey</em>: weathered timber, natural stone, tactile cloth and colour softened by exposure. The useful idea is not film-set imitation. It is a room whose beauty comes from surface, proportion and light.</p>
<div class="summary-box" id="answer"><p class="kicker">The concise answer</p><h2>Use the three-material rule</h2><p>Choose one chalky surface, one woven material and one piece of warm wood or stone. Build the palette from limestone, sand and unbleached linen, then add blue only once. Keep furniture contemporary and let irregular texture provide age. If the room already contains arches, columns or patterned tile, reduce the decorative objects rather than adding more historical references.</p></div>
<section id="meaning"><h2>What Greek chic means in a real home</h2><p>At its most useful, Greek chic is a material mood. Walls look mineral rather than flat. Linen filters daylight instead of framing the window heavily. Ceramics retain the evidence of a hand. A clean-lined sofa sits beside something rougher: a stone table, a timber stool or a woven rush chair.</p><p>That balance separates it from both coastal décor and archaeological pastiche. Coastal rooms often use nautical colour and motif to announce proximity to water. Greek chic can work in a landlocked flat because it borrows the effect of sun and weather rather than copying boats, beaches or islands.</p><p>It also differs from pure <a href="/blogs/home/warm-minimalist-bedroom/">warm minimalism</a>. Both use calm colour and natural texture, but Greek chic permits a stronger silhouette: a deep blue vessel, a plaster niche, a heavy stone top or a chair with an almost sculptural back. The room remains edited without becoming anonymous.</p><h3>Old surface, new silhouette</h3><p>The safest formula is to place an imperfect material beside a current shape. Put a simple modular sofa against a cloudy mineral wall. Set a polished reading lamp on a roughly grained table. Use an angular side chair beside a rounded ceramic vessel. When both the material and the silhouette attempt to look ancient, the room slips towards a set.</p></section>
{picture(GREEK_ROOT, "greek-chic-materials", "Warm limewash sample, washed linen, pale limestone, aged olive wood and one muted Aegean-blue ceramic tile arranged in daylight")}
<section id="palette"><h2>Build the palette from stone, sand and one piece of sea</h2><p>Begin with warm white rather than optical white. A small amount of ochre, grey or pink in the undertone keeps the walls from turning clinical beside stone and wood. Add two adjacent neutrals so the room has depth: limestone with sand, or chalk with weathered taupe.</p><p>Good Homes recommends softened landscape colours including limestone, chalky white, warm sand, clay and weathered taupe, with charcoal, bronze or muted sea blue used sparingly. The restraint matters more than the precise shade. Blue becomes richer when it is allowed to be an event rather than a uniform.</p><div class="article-table-wrap" role="region" aria-label="Greek chic interior palette" tabindex="0"><table class="article-visual-table"><thead><tr><th>Role</th><th>Useful colour</th><th>Where it works</th></tr></thead><tbody><tr><td>Background</td><td>Chalk, limestone, warm ivory</td><td>Walls, ceiling, large upholstery</td></tr><tr><td>Middle tone</td><td>Sand, clay, weathered taupe</td><td>Rugs, curtains, timber, cushions</td></tr><tr><td>Dark anchor</td><td>Charcoal, bronze, olive wood</td><td>Lighting, frames, one table</td></tr><tr><td>Sea note</td><td>Muted Aegean or mineral blue</td><td>One chair, vessel, tile or textile</td></tr></tbody></table></div><h3>Test white at three times of day</h3><p>Paint a large movable board instead of several small squares directly on the wall. Look at it in morning light, late afternoon and under the lamps used at night. The warm white should remain mineral, not yellow; the blue should deepen, not turn electric. Move the samples beside the actual stone, timber and upholstery before committing.</p></section>
<section id="materials"><h2>The five materials that carry the look</h2><h3>1. Mineral wall finish</h3><p>Limewash, clay paint and mineral-effect finishes create variation as light crosses the wall. Real limewash requires a compatible porous surface and proper preparation; not every sealed wall can accept it directly. Follow the manufacturer's system and test for rub-off, colour variation and patching before covering a room.</p><h3>2. Washed linen</h3><p>Use linen where movement improves the room: loose curtains, a bed cover or one relaxed cushion. Avoid putting ruffles on every edge. The fibre should soften light and introduce a dry, rumpled texture, not turn the room into a romantic theme.</p><h3>3. Natural or convincing stone</h3><p>Limestone, travertine and marble bring cool mass, but a small home does not need a new floor. A remnant top, lamp base or shallow dish can supply the same visual weight. Seal and care for natural stone according to its type; acidic cleaners can etch carbonate stones such as marble and limestone.</p><h3>4. Weathered timber</h3><p>Choose one piece with visible grain and a quiet shape. Olive wood, oak and elm all work, but provenance and construction matter more than a species name. Avoid coating every surface in an identical pale stain. Variation is part of the effect.</p><h3>5. Hand-finished ceramic</h3><p>One asymmetrical vessel can replace a shelf of themed accessories. Leave it empty, fill it with an olive branch or use a low bowl for fruit. The object should have enough scale to stand alone. This follows the same editing logic as our guide to <a href="/blogs/home/coffee-table-styling-that-looks-collected/">a collected coffee table</a>: fewer objects, clearer relationships.</p></section>
<section id="rooms"><h2>Greek chic, room by room</h2><h3>Living room</h3><p>Keep the largest upholstery plain and low-contrast. Add a stone or timber table, a woven chair and one strong ceramic. If the architecture is ordinary, let a limewashed wall behind the sofa provide depth. If the room already has an arch or old fireplace, use a simpler painted finish and allow the structure to lead.</p><h3>Bedroom</h3><p>Start with unbleached or warm-white bedding, then add a clay-coloured throw and dark timber beside the bed. Hang linen curtains close to the ceiling so the cloth reads as one continuous plane. A niche can be suggested with a shallow wall-mounted shelf in the wall colour; there is no need to construct a faux arch.</p><h3>Kitchen</h3><p>Use the look through surfaces that can tolerate work: honed stone or a convincing composite, timber boards, off-white cabinetry and simple metal hardware. Decorative plaster should not be placed where grease and water make it impractical. A single blue stool or glazed bowl is enough to introduce the sea.</p><h3>Bathroom</h3><p>This is where the theme risk is highest. Skip borders of blue mosaic and printed shells. Pair warm plaster-effect walls with a stone basin or ledge, simple chrome or bronze fittings and a washed linen blind outside splash zones. For a richer material comparison, see our <a href="/blogs/home/red-marble-bathroom-ideas/">red marble bathroom guide</a>; the discipline of one dominant stone applies even when the colour changes.</p><h3>Entryway</h3><p>An entry can carry the idea with almost no floor area: mineral wall colour, a narrow timber bench and one generous vessel beneath a modern wall light. Good Homes notes that stairwells and entrances show off the movement of a cloudy wall finish particularly well because light changes along the vertical surface.</p></section>
{picture(GREEK_ROOT, "greek-chic-entryway", "Compact city-flat entry with chalky mineral walls, a slim aged-wood bench, limestone floor, linen curtain and one muted blue ceramic vessel")}
<section id="small"><h2>How to use the trend in a small home or rental</h2><p>Do not miniaturise every feature. One full-size lamp, vessel or artwork creates more confidence than several tiny references. Keep floors and large furniture close in tone so the room reads continuously, then use texture to create distinction.</p><ul><li><strong>Change the light:</strong> replace a bare cool bulb with a warm, shaded source appropriate to the fitting.</li><li><strong>Hang one linen panel:</strong> even if the blind remains functional, a side panel can soften daylight.</li><li><strong>Use removable colour:</strong> paint a board, freestanding shelf or second-hand side table in muted blue instead of altering walls.</li><li><strong>Bring in mineral mass:</strong> use a stone remnant, vintage marble board or heavy ceramic bowl.</li><li><strong>Edit the motifs:</strong> if the room already has stripes or shell objects, keep only the best one.</li></ul><p>Photograph the room before buying anything. On a small screen, repeated motifs and weak little objects become obvious. Remove first, then add the single missing material. That sequence keeps Greek chic compatible with the <a href="/blogs/home/lived-in-interior-design-2026/">anti-algorithm, lived-in home</a> rather than turning it into another shopping list.</p></section>
<section id="avoid"><h2>What turns Greek chic into a holiday-villa theme</h2><h3>Blue repeated everywhere</h3><p>A cobalt vase, striped cushion, blue glass, painted stool and tiled border may each work alone. Together they become branding. Keep one blue gesture and let its shade reappear only faintly, perhaps in a book spine or artwork.</p><h3>Literal antiquity</h3><p>Busts, columns, key patterns and amphorae carry strong historical associations. Use one only if it is an object you genuinely love, then surround it with contemporary forms. Buying several reproductions at once creates instant pastiche.</p><h3>Texture without relief</h3><p>If the walls, sofa, rug, curtains and pottery are all chalky and pale, the room can feel dusty rather than calm. Add something smooth and dark: bronze, smoked glass, a lacquered tray or a modern black frame. The contrast gives rough surfaces meaning.</p><h3>Ignoring climate and use</h3><p>A breezy linen room behaves differently in a damp, dark winter. Add lined curtains, a denser rug and warm pools of light without abandoning the palette. The aim is not to preserve a summer photograph. It is to translate its material logic into the home you actually occupy.</p><p>The broader principle is the same as <a href="/blogs/home/how-to-make-a-home-look-expensive/">making a home look expensive without making it cold</a>: spend attention on scale, light and finish before adding decorative evidence of a trend.</p></section>
<section class="article-faq"><h2>Greek chic interior questions</h2><h3>What is Greek chic interior design?</h3><p>It is a contemporary Mediterranean look based on warm white, natural stone, linen, weathered timber, softened blue and sculptural simplicity. The current version prioritises texture over literal ancient Greek motifs.</p><h3>Does Greek chic have to be blue and white?</h3><p>No. A stronger foundation is chalk, limestone, sand, clay and timber. Blue works best as one concentrated accent rather than the room's entire identity.</p><h3>Can Greek chic work in a dark room?</h3><p>Yes. Use warmer mineral neutrals, a darker timber anchor and several shaded lamps. Avoid brilliant white, which can turn grey without strong daylight.</p><h3>Is limewash suitable for every wall?</h3><p>No. True limewash needs a compatible surface or specified primer system. Test the finish and follow the manufacturer's preparation guidance. A mineral-effect paint can be a more practical alternative in some rentals or high-contact areas.</p></section>
<section class="source-note"><h2>Sources and image note</h2><p>Trend context was reviewed in Ideal Home's <a href="https://www.idealhome.co.uk/all-rooms/greek-chic-mictrotrend">31 August 2026 Greek chic report</a> and Good Homes' <a href="https://www.goodhomesmagazine.com/inspiration/odyssey-interiors-decorating-ideas/">Odyssey-inspired interiors guide</a>, published 24 August 2026. Palette, proportion and rental guidance is by.foro editorial analysis. Product instructions and professional advice take priority for mineral finishes and natural stone. The photographs show fictional interiors created for this article.</p></section>
<section><h2>Keep the weather, lose the symbols</h2><p>The most convincing Greek chic room does not announce Greece through souvenirs. It feels sun-softened, tactile and slightly ancient because light moves across mineral colour and natural material. Keep one piece of sea, one rough surface and enough empty space for both to register. The room will hold the mood without becoming a postcard.</p></section><div class="article-end"><span>End</span><p>Published by by.foro Editorial on 5 September 2026. For corrections, contact <a href="mailto:hello@byforo.com">hello@byforo.com</a>.</p></div></div></div>'''


RICE_URL = "/blogs/beauty/rice-perfume-guide/"
RICE_ROOT = "/assets/images/blogs/beauty/rice-perfume-guide"
RICE_TITLE = "Rice Perfume Smells More Like Skin Than Supper"
RICE_SEO = "Rice Perfume: What the Quiet Gourmand Smells Like"
RICE_DESCRIPTION = "Discover what rice perfume smells like, how steamed, toasted and powdery rice accords differ, which notes suit them and how to test and layer one."
RICE_DECK = "Soft starch, warm steam, pale woods and a trace of nuttiness make rice one of fragrance's quietest gourmands."
RICE_BODY = f'''<div class="article-layout"><aside class="article-aside"><p class="kicker">The scent file</p><ol><li><a href="#answer">The short answer</a></li><li><a href="#smell">What it smells like</a></li><li><a href="#styles">Four rice styles</a></li><li><a href="#compare">Rice, milk or skin scent</a></li><li><a href="#test">How to test it</a></li><li><a href="#layer">How to layer it</a></li><li><a href="#choose">Choose the right bottle</a></li></ol><button class="copy-link" data-copy-link type="button">Copy link</button></aside><div class="article-body">
<p class="article-opening">Rice perfume usually smells softly starchy, creamy, powdery and faintly nutty. A steamed-rice accord can suggest warm skin and clean paper; toasted rice can feel drier and more cereal-like; rice milk brings lactonic sweetness; rice powder leans cosmetic beside iris and musk. Most versions are quieter than vanilla gourmands and wear relatively close to the body.</p>
<p>The word &ldquo;rice&rdquo; makes the note sound literal, but fragrance treats it as texture. There may be a suggestion of steam lifting from a cooker, the dry surface of a grain or the pale dust of face powder. What remains on skin is often difficult to name: warm, clean and gently sweet, with none of the obvious sugar of caramel or marshmallow.</p>
<p>That subtlety gives rice a particularly useful place in fall 2026. Allure reports that gourmands rose sharply in popularity while moving towards more complex textures, with tea, coffee, rice and spice interrupting straightforward sugar. Who What Wear places rice inside the &ldquo;quiet gourmand&rdquo; family, where creaminess supports florals, woods and musk rather than becoming dessert.</p>
<div class="summary-box" id="answer"><p class="kicker">The concise answer</p><h2>Expect warm starch, pale powder and restrained sweetness</h2><p>Choose steamed rice with musk or sandalwood for a close skin scent; rice powder with iris or violet for a cosmetic finish; toasted rice with sesame, barley or woods for something dry; and rice milk with vanilla or cardamom for a softer gourmand. Test for at least four hours, because many rice accords move from recognisable steam to an understated musky base.</p></div>
<section id="smell"><h2>What rice perfume actually smells like</h2><p>A rice accord is usually an interpretation built by a perfumer, not the smell of cooked grains poured into a bottle. The surrounding notes decide which part of rice the fragrance suggests. Musk can turn starch into clean skin. Almond or milk makes it creamier. Iris emphasises powder. Sesame, barley and woods make it toasted and dry.</p><p>Who What Wear describes the family as subtly sweet and creamy, with powdery, nutty and milky facets. Marie Claire UK goes further through an interview with BORNTOSTANDOUT founder Jun Lim, who characterises rice as a quiet gourmand with warm, nostalgic comfort rather than loud candy or caramel. That emotional association matters: rice can smell like care and home without smelling like a confection.</p><h3>The note often becomes quieter as it dries</h3><p>The opening may deliver the clearest image of steam or grain. After half an hour, the accord often blends into musk, soft wood, heliotrope or iris. That is not necessarily poor performance. The rice may be acting as a texture inside the heart rather than a recognisable top-to-bottom note.</p><h3>Close projection and short longevity are not the same</h3><p>A fragrance can last eight hours while remaining perceptible only within a small radius. Check the skin directly, then ask another person whether the scent is still present before deciding it has disappeared. Our broader <a href="/blogs/beauty/skin-scent-perfume-guide/">skin scent guide</a> explains why a wearer can become accustomed to a close musk while the perfume remains detectable to others.</p></section>
{picture(RICE_ROOT, "rice-perfume-notes", "Steamed white rice, dry grains, toasted rice, iris root, pale sandalwood and unbranded scent vials arranged on warm limestone")}
<section id="styles"><h2>Four kinds of rice perfume worth distinguishing</h2><h3>1. Steamed rice</h3><p>This is the soft cloud: warm starch, humid air and a faint sweetness. It works naturally with white musk, sandalwood, peony and tea. Choose it if you want intimacy and comfort without an obvious vanilla trail.</p><h3>2. Toasted rice</h3><p>Here the grain feels drier, nuttier and slightly roasted. Sesame, barley, hazelnut, vetiver or cedar can pull the fragrance towards a savoury cereal impression. The best versions keep enough musk or floral lift to prevent the drydown from feeling dusty.</p><h3>3. Rice milk</h3><p>Lactonic notes round the grain and make the scent creamier. Vanilla, tonka and cardamom can turn it towards rice pudding; pale woods and clean musk keep it sheer. Read the complete note list rather than assuming every &ldquo;rice milk&rdquo; fragrance is equally sweet.</p><h3>4. Rice powder</h3><p>Iris, violet, heliotrope and rose can transform rice into a cosmetic texture. The result may resemble a compact, warm paper or powdered skin more than food. This is often the most polished style and the least obviously gourmand.</p><div class="article-table-wrap" role="region" aria-label="Rice perfume style comparison" tabindex="0"><table class="article-visual-table"><thead><tr><th>Rice style</th><th>Main texture</th><th>Useful pairings</th></tr></thead><tbody><tr><td>Steamed</td><td>Warm, humid, starchy</td><td>Musk, tea, peony, sandalwood</td></tr><tr><td>Toasted</td><td>Dry, nutty, cereal-like</td><td>Sesame, barley, cedar, vetiver</td></tr><tr><td>Rice milk</td><td>Creamy, lactonic, softly sweet</td><td>Almond, vanilla, cardamom, tonka</td></tr><tr><td>Rice powder</td><td>Cosmetic, papery, smooth</td><td>Iris, violet, heliotrope, rose</td></tr></tbody></table></div></section>
<section id="compare"><h2>Rice perfume, milky perfume and skin scent are overlapping ideas</h2><p>A rice fragrance may belong to all three families, but the terms are not interchangeable. &ldquo;Rice&rdquo; describes the creative note or accord. &ldquo;Milky&rdquo; describes a lactonic texture. &ldquo;Skin scent&rdquo; describes the effect or projection: intimate, warm and close.</p><p>A dry rice-and-vetiver perfume can project moderately and contain no obvious milk. A milky vanilla may smell creamy without any rice effect. A white musk can behave like a skin scent without smelling edible at all. Decide which quality you actually want before searching by label.</p><h3>Rice is quieter than many green gourmands</h3><p>Matcha, tomato leaf and carrot seed each announce a clearer colour or texture. Rice is paler and more absorbent. In our <a href="/blogs/beauty/matcha-perfume-guide/">matcha perfume guide</a>, tea brings bitterness and leaf; <a href="/blogs/beauty/carrot-seed-perfume-guide/">carrot seed</a> brings earthy powder. Rice often behaves like the paper beneath those marks.</p></section>
<section id="test"><h2>How to test rice perfume without losing the quiet part</h2><p>Start on a blotter with one spray and write the time beside it. Smell at five minutes, thirty minutes, two hours and the following morning. Do not keep the strip under your nose; brief checks make it easier to notice change and reduce olfactory fatigue.</p><ol><li><strong>At five minutes:</strong> identify steam, grain, milk, almond or powder.</li><li><strong>At thirty minutes:</strong> note whether the rice remains recognisable or has become floral, woody or musky.</li><li><strong>At two hours:</strong> judge sweetness, projection and texture rather than searching for a literal bowl of rice.</li><li><strong>The next morning:</strong> smell the strip at arm's length, then close, to assess the base.</li></ol><p>Move the most promising sample to clean, unscented skin. Wear it on two ordinary days before buying a bottle. Warm weather may make lactonic sweetness feel denser; cool air can flatten a very sheer musk. Test under the conditions in which you expect to wear it.</p><h3>Compare different rice styles, not three similar bottles</h3><p>Sample one steamed-musky fragrance, one toasted style and one powdery iris. The contrast teaches your nose what &ldquo;rice&rdquo; is doing. Testing three near-identical milky musks can make tiny differences feel important while leaving the larger preference unresolved.</p></section>
{picture(RICE_ROOT, "rice-perfume-testing", "Two unbranded frosted perfume bottles with labelled paper blotters, a small linen pouch of rice and an open notebook in soft window light")}
<section id="layer"><h2>How to layer rice perfume</h2><p>Wear the fragrance alone several times first. Rice is quiet enough to disappear beneath a louder partner, so keep the total spray count low and place the two perfumes on separate areas of skin. That makes it possible to follow each one as it develops.</p><ul><li><strong>For brightness:</strong> bergamot, mandarin or green tea can lift steamed rice.</li><li><strong>For more skin:</strong> use a sheer white musk, ambrette or pale sandalwood.</li><li><strong>For a floral veil:</strong> try peony, iris, violet or a restrained white flower.</li><li><strong>For warmth:</strong> cardamom, soft incense or cedar gives the starch a dry edge.</li><li><strong>For dessert:</strong> vanilla, tonka or cinnamon pushes rice milk towards pudding.</li></ul><p>Jun Lim tells Marie Claire UK that a minimalist rice scent can act as a creamy blank canvas, pairing with citrus and green notes, florals, vanilla and spice or darker woods and amber. Use that as a map, not a requirement to combine everything. One small contrast is enough.</p><p>Within a <a href="/blogs/beauty/perfume-wardrobe-by-mood/">perfume wardrobe organised by mood</a>, rice belongs between clean and warm. It can replace a plain musk when you want more texture or a vanilla gourmand when you want less sugar.</p></section>
<section id="choose"><h2>How to choose a rice perfume you will keep wearing</h2><p>Ask which memory or texture you want after the novelty of the name disappears. If it is steam, make sure the opening lasts long enough to satisfy you. If it is creamy comfort, judge whether the late musk still feels distinctive. If it is rice powder, compare the fragrance with iris and heliotrope perfumes you already own.</p><h3>Buy the drydown, not the first bowl of steam</h3><p>The vivid opening sells the idea; the base occupies most of the day. Smell the sample after four hours and on clothing the next morning. If the rice has become a simple sandalwood or musk, decide whether you would buy that base without the story.</p><h3>Match bottle size to the role</h3><p>A close rice scent may become an easy office or bedtime fragrance and justify a larger bottle. A dense rice-milk gourmand may be something you wear only in cool weather. Track ten wears from a sample or travel size before assuming a full bottle is better value.</p><p>Store fragrance upright, shaded and away from heat or repeated bathroom humidity. Display the empty box or a sample card if you want the still life; keep the liquid where temperature remains stable. The practical compromise is explored in our <a href="/blogs/beauty/the-vanity-table-as-still-life/">vanity table guide</a>.</p></section>
<section class="article-faq"><h2>Rice perfume questions</h2><h3>Does rice perfume smell like cooked rice?</h3><p>Some openings evoke warm steamed rice, but most become a soft mixture of musk, powder, milk, woods or florals. Toasted styles can smell drier and nuttier.</p><h3>Is rice perfume sweet?</h3><p>Usually only gently. Rice milk with vanilla or tonka can be quite gourmand, while rice with iris, vetiver, tea or musk may feel dry, clean and close to skin.</p><h3>Is rice perfume a skin scent?</h3><p>Many are, because the accord blends naturally with musk and pale woods. But rice describes the note, not the projection, so some compositions can still be strong.</p><h3>What is the best season for rice perfume?</h3><p>Sheer steamed-rice and tea styles can work year-round. Creamy, toasted or spicy versions are often easiest in autumn and winter. Skin testing matters more than a fixed seasonal rule.</p></section>
<section class="source-note"><h2>Sources and image note</h2><p>Fall trend context was reviewed in Allure's <a href="https://www.allure.com/story/fall-fragrance-trends-2026">August 2026 fragrance report</a>. Rice scent descriptions and product-note comparisons were checked against <a href="https://www.whowhatwear.com/beauty/fragrance/best-rice-perfumes">Who What Wear's rice perfume guide</a> and Marie Claire UK's <a href="https://www.marieclaire.co.uk/beauty/fragrance/rice-perfumes">interview with BORNTOSTANDOUT founder Jun Lim</a>. Testing, comparison and wardrobe guidance is by.foro editorial analysis. The photographs show fictional unbranded fragrance scenes created for this article.</p></section>
<section><h2>Rice is most interesting when it almost disappears</h2><p>The note does not need to remain literal from first spray to bedtime. Its usefulness is the soft starch it leaves inside musk, wood, iris or milk. When a fragrance makes skin feel warmer and a gourmand feel quieter, the rice has done its work.</p></section><div class="article-end"><span>End</span><p>Published by by.foro Editorial on 5 September 2026. For corrections, contact <a href="mailto:hello@byforo.com">hello@byforo.com</a>.</p></div></div></div>'''


ARTICLES = [
    {
        "url": NECKLACE_URL, "seo": NECKLACE_SEO, "title": NECKLACE_TITLE,
        "description": NECKLACE_DESCRIPTION, "deck": NECKLACE_DECK,
        "department": "Fashion", "topic": "Accessories",
        "hero": f"{NECKLACE_ROOT}/kitchen-sink-necklace-hero",
        "alt": "Long eclectic necklace with old medallions, small keys, shells and enamel charms worn over a plain charcoal knit, cropped from chin to waist",
        "body": NECKLACE_BODY, "words": 2050,
        "keywords": ["kitchen sink necklace", "kitchen sink necklace trend 2026", "charm necklace trend", "how to wear a charm necklace"],
    },
    {
        "url": GREEK_URL, "seo": GREEK_SEO, "title": GREEK_TITLE,
        "description": GREEK_DESCRIPTION, "deck": GREEK_DECK,
        "department": "Home", "topic": "Luxury decor",
        "hero": f"{GREEK_ROOT}/greek-chic-interiors-hero",
        "alt": "Sunlit living room with warm limewash walls, low linen sofa, limestone table, aged wood and a single muted blue ceramic vessel",
        "body": GREEK_BODY, "words": 2050,
        "keywords": ["Greek chic interiors", "Greek chic decor", "Mediterranean interiors 2026", "Odyssey interior trend"],
    },
    {
        "url": RICE_URL, "seo": RICE_SEO, "title": RICE_TITLE,
        "description": RICE_DESCRIPTION, "deck": RICE_DECK,
        "department": "Beauty", "topic": "Fragrance",
        "hero": f"{RICE_ROOT}/rice-perfume-hero",
        "alt": "Unbranded frosted perfume bottle beside a shallow bowl of steamed rice, dry grains, white iris and pale wood on warm limestone",
        "body": RICE_BODY, "words": 2000,
        "keywords": ["rice perfume", "what does rice perfume smell like", "rice milk perfume", "quiet gourmand fragrance"],
    },
]


def add_reciprocal_link(path: Path, url: str, sentence: str) -> None:
    text = path.read_text(encoding="utf-8")
    if url in text:
        return
    match = re.search(r'(<p class="article-opening">.*?</p>)', text, flags=re.S)
    if not match:
        raise RuntimeError(f"Could not find opening paragraph in {path}")
    text = text[:match.end()] + sentence + text[match.end():]
    path.write_text(text, encoding="utf-8", newline="\n")


def main() -> None:
    for item in ARTICLES:
        document = base.page(
            item["url"], item["seo"], item["title"], item["description"],
            item["deck"], item["department"], item["topic"], item["hero"],
            item["alt"], item["body"], "BlogPosting", item["words"], item["keywords"],
        )
        document = document.replace("topic=luxury decor", "topic=luxury-decor")
        destination = ROOT / item["url"].strip("/") / "index.html"
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(document, encoding="utf-8", newline="\n")
        print("Built", destination.relative_to(ROOT))

    catalogue_path = ROOT / "content" / "articles.json"
    current = json.loads(catalogue_path.read_text(encoding="utf-8"))
    additions = []
    for item in ARTICLES:
        additions.append({
            "title": item["title"], "seoTitle": item["seo"],
            "department": item["department"].lower(), "topic": item["topic"].lower().replace(" ", "-"),
            "published": PUBLISHED, "readingMinutes": round(item["words"] / 195),
            "readingWordsPerMinute": 195, "url": item["url"], "excerpt": item["deck"],
            "metaDescription": item["description"],
            "image": {"webp": f'{item["hero"]}.webp', "fallback": f'{item["hero"]}.jpg', "alt": item["alt"], "width": 1536, "height": 1024},
            "articleSection": item["topic"], "breadcrumbTopic": True,
        })
    new_urls = {item["url"] for item in additions}
    catalogue_path.write_text(
        json.dumps(additions + [item for item in current if item["url"] not in new_urls], ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8", newline="\n",
    )

    links = [
        ("blogs/fashion/bandana-jewellery/index.html", NECKLACE_URL, '<p>For a fuller version of the same collected instinct, our <a href="/blogs/fashion/kitchen-sink-necklace/">kitchen-sink necklace guide</a> explains how to mix charms, medallions and keepsakes without losing visual order.</p>'),
        ("blogs/fashion/how-to-wear-a-bib-necklace/index.html", NECKLACE_URL, '<p>If one rigid statement feels too formal, the <a href="/blogs/fashion/kitchen-sink-necklace/">kitchen-sink necklace</a> offers a looser alternative built from personal charms, long chains and deliberate spacing.</p>'),
        ("blogs/home/warm-minimalist-bedroom/index.html", GREEK_URL, '<p>For a more elemental extension of this palette, our <a href="/blogs/home/greek-chic-interiors/">Greek chic interiors guide</a> adds limewash, stone, washed linen and one softened note of blue.</p>'),
        ("blogs/home/lived-in-interior-design-2026/index.html", GREEK_URL, '<p>The emerging <a href="/blogs/home/greek-chic-interiors/">Greek chic interior</a> works by the same principle: weathered material and personal use matter more than a perfectly themed Mediterranean room.</p>'),
        ("blogs/beauty/skin-scent-perfume-guide/index.html", RICE_URL, '<p>For a softly starchy variation on the close-wearing scent, our <a href="/blogs/beauty/rice-perfume-guide/">rice perfume guide</a> distinguishes steamed, toasted, milky and powdery rice accords.</p>'),
        ("blogs/beauty/perfume-wardrobe-by-mood/index.html", RICE_URL, '<p>Between the clean and warm moods, our <a href="/blogs/beauty/rice-perfume-guide/">rice perfume guide</a> explores a quiet gourmand that can feel like steam, powder, pale wood or warm skin.</p>'),
    ]
    for relative, url, sentence in links:
        add_reciprocal_link(ROOT / relative, url, sentence)


if __name__ == "__main__":
    main()
