"""Build three practical architecture guides about daylight and window spaces."""
import build_september_27_architecture as builder

builder.DATE = "2026-10-10"
builder.base.PUBLISHED = builder.DATE
builder.base.PUBLISHED_LABEL = "10 October 2026"
builder.base.PUBLISHED_ISO = builder.DATE + "T12:00:00+02:00"

builder.STORIES = [
{
    "slug": "internal-window-dark-hallway",
    "title": "The Internal Window That Gives a Dark Hallway Some Daylight",
    "seo": "Internal Windows for Dark Hallways: Ideas and What to Check",
    "description": "Explore internal window ideas for a dark hallway, including transoms, clear and reeded glass, privacy, sound and the practical checks before changing a wall.",
    "deck": "Before choosing a frame, find the daylight you want to borrow and follow its route into the hall.",
    "alt": "Oak-framed internal window between a pale hallway and a dining room with an exterior garden window",
    "image_source": "exec-cbcdc554-fd46-4cd9-95bd-cc69a6fdcd6e.png",
    "inline_sources": [
        ("exec-46233e6a-c4dc-4f3b-8438-780ec5dd5361.png", "high-transom", "High internal transom window over a timber door in a modest entrance hallway"),
        ("exec-1800c0d8-a6d4-4deb-8d81-6b807b9c2886.png", "reeded-glass", "Reeded glass set into a slim oak internal window frame within a plaster wall")
    ],
    "keywords": ["internal window dark hallway", "borrowed light hallway", "internal window ideas", "reeded glass internal window"],
    "body": """
<p class="article-opening">An internal window can bring borrowed daylight into a dark hallway by opening a glazed route to a brighter neighbouring room. It works best when that room has useful daylight to share and the glass sits where light can reach it. A window at eye level also changes the view between rooms, while a high transom can admit light with less visual connection.</p>
<p>There is a particular kind of hallway that feels dim even on a bright morning. The rooms beside it are perfectly pleasant, but their solid walls keep all the light to themselves. An internal window can make the plan feel more connected without taking away the door or opening the rooms into one large space.</p>
<div class="summary-box" id="answer"><p class="kicker">The short answer</p><h2>Start with the brighter room</h2><p>Identify the exterior window supplying the daylight, then check the route between it and the proposed internal glass. Choose the opening's position for light and privacy before deciding on its style. Keep evening lighting in the hallway, and have the wall, glazing and any fire requirements assessed before work begins.</p></div>
<section id="route"><h2>Find out where the borrowed light will come from</h2><p>Stand in the hallway with the neighbouring door open at different times of day. Notice where the light reaches and which parts remain dark. A bright room at the front of the house may be less useful than a smaller room with a window directly opposite the proposed opening.</p><p>Draw the route in plan. Daylight coming through an exterior window, passing a tall cupboard and turning into a corridor has more obstacles than light travelling across an open dining room. An internal window cannot create daylight, and a larger panel will not necessarily solve a poor position.</p><p>Check the room in winter and on an overcast day if you can. A photograph taken on a sunny afternoon can exaggerate what the glass will achieve during the rest of the year. For a substantial renovation, ask the designer to assess daylight as part of the layout rather than making the opening a decorative decision at the end.</p></section>
<section id="types"><h2>Three internal window ideas for a dark hallway</h2><h3>A fixed window beside a doorway</h3><p>This creates a view as well as a source of light. It can make a small entrance feel less enclosed, especially when the room beyond contains a garden window. Position the glass so the view lands on something you enjoy seeing. A dining table or a patch of planting is a more restful destination than the side of a fridge.</p><h3>A transom above the door</h3><p>A high glazed panel is useful where the lower wall needs to remain available for furniture or where direct views between rooms would be intrusive. Let its proportions relate to the door below. A narrow, considered opening can look more settled than a large panel squeezed against a ceiling detail.</p><h3>A glazed upper section of wall</h3><p>Keeping the lower wall solid can preserve space for a bench or console while sharing light higher up. Check the finished height from both sides. You may still see into the adjoining room when standing, especially if floor levels differ. A drawn elevation helps more than a small sample of the frame colour.</p></section>
<section id="glass"><h2>Clear, reeded or obscured glass?</h2><p>Clear glass offers the most direct connection and preserves a recognisable view. It also means that both rooms see each other's lights, furniture and everyday mess. If you want a visual connection, choose a frame that relates to the nearby doors and let the view do the work.</p><p>Reeded glass breaks up outlines while allowing light through, but it is not a promise of complete privacy. Shapes and movement can remain visible, particularly when someone is close to the pane or the room behind is brighter. Ask for a large sample and test it with the lighting conditions you expect.</p><p>Other obscured finishes may provide a more diffuse effect. Compare the actual glass rather than selecting from an online swatch. Texture, colour and light transmission vary between products. A pane that looks beautifully soft in a showroom may make your hallway feel greyer than you hoped.</p></section>
<section id="sound"><h2>What happens to sound and privacy?</h2><p>A fixed glazed opening keeps a physical division between rooms, but its acoustic performance depends on the whole construction. Glass type, frame, seals, surrounding wall and nearby doors all matter. If the adjoining room is an office, decide whether the glass needs to support calls and quiet work as well as daylight.</p><p><a href="https://www.pilkington.com/en-GB/gbl/architectural-and-technical-glass/product-categories/noise-control/pilkington-optiphon">Pilkington's acoustic laminated glass guidance</a> describes products designed to reduce noise transmission through glazing. That is a useful starting point for a specification conversation, not a reason to assume every laminated pane will provide the same result. Ask for performance information for the proposed assembly.</p><p>Think about privacy after dark too. An illuminated office may be visible from the entrance even if it feels discreet during the day. A blind, curtain or more obscured pane can help, but plan the fitting before the opening is built. Otherwise the practical fix may obscure the frame you chose so carefully.</p></section>
<section id="frame"><h2>Make the frame belong to the house</h2><p>Timber can give the opening warmth and a sense of depth. A painted frame can sit quietly with existing joinery. Slim dark metal is useful when the house already has a reason for that material, though a strong grid can become the main feature of a modest hall.</p><p>Look at the wall thickness and the sill as well as the front face. A neat reveal helps the opening feel architectural. If you plan to put objects on the sill, keep them low enough to leave the light route clear. A window intended to brighten a hall can quickly become a shelf full of obstructions.</p><p>Coordinate it with the rest of the entrance. Our <a href="/blogs/home/small-entryway-that-looks-expensive/">small entryway guide</a> covers storage and circulation, which still need to work once the new view is in place.</p></section>
<section id="checks"><h2>What to check before cutting the wall</h2><p>Have the existing wall assessed for structure, concealed services and its role in the building's fire strategy. Internal glazing beside a hall or stair can have requirements that ordinary decorative glass does not meet. The appropriate solution depends on the building and local rules.</p><p>Specify the glass for its position and intended use, including any safety requirements. Ask how the frame will be supported, how the opening will be finished and who is responsible for making good the surrounding wall. A quotation for the glass alone leaves much of the job unresolved.</p><p>If the wall cannot reasonably be altered, a suitable glazed door may provide some borrowed light with a different scope of work. You can also compare an external high window where the layout allows it. Our <a href="/blogs/home/clerestory-windows-light-privacy/">clerestory window guide</a> explains that option. Each solution needs to suit the building, not simply the mood board.</p></section>
<section class="article-faq"><h2>Internal window questions</h2><h3>Will an internal window brighten a windowless hallway?</h3><p>It can, if the adjoining room has enough daylight and the opening is well placed. It is still sensible to keep a useful lighting scheme for evenings and darker days.</p><h3>Does reeded glass give complete privacy?</h3><p>Not necessarily. Visibility depends on the product, distance and relative lighting. Test a sample from both sides.</p><h3>Can you put an internal window in any wall?</h3><p>No. Structure, services, fire requirements and the proposed glazing need assessment before the opening is made.</p></section>
<section class="source-note"><h2>Sources and image note</h2><p>Acoustic product information was checked against Pilkington's guidance linked above. The daylight, layout and styling observations are by.foro editorial analysis. Images are AI-generated architectural visualisations of fictional homes.</p></section>
<div class="article-end"><span>End</span><p>Published by by.foro Editorial on 10 October 2026. For corrections, contact <a href="mailto:hello@byforo.com">hello@byforo.com</a>.</p></div>
"""
},
{
    "slug": "clerestory-windows-light-privacy",
    "title": "Clerestory Windows Let the Sky In",
    "seo": "Clerestory Windows: Light, Privacy and Design Ideas",
    "description": "Learn how clerestory windows bring daylight into a home, where high glazing can improve privacy, and what to consider for shade, ventilation and cleaning.",
    "deck": "A high strip of glass can change a room while leaving the walls below available for everyday life.",
    "alt": "High horizontal clerestory windows beneath a sloping timber roof above a simple linen sofa",
    "image_source": "exec-1de76c77-e7a1-4a7e-a078-efecb8958e28.png",
    "inline_sources": [
        ("exec-53e3efbd-c9f4-4625-ab9f-306dbc1b0141.png", "kitchen-daylight", "Compact oak kitchen with a high horizontal exterior window above the cabinetry"),
        ("exec-0cf4858f-f2c0-4dba-be11-23e84491f508.png", "exterior-window-band", "Narrow band of high windows beneath the eave of a modest rendered house")
    ],
    "keywords": ["clerestory windows", "clerestory windows privacy", "high windows living room", "clerestory window kitchen"],
    "body": """
<p class="article-opening">Clerestory windows are high windows set near the top of a wall, often above the usual line of sight. They bring daylight into a room while leaving the lower wall available for furniture, cabinetry or a more private boundary. Their effect depends on orientation, roof shape, neighbouring buildings and the way the light meets the ceiling.</p>
<p>You may notice the light before you notice the window. The upper wall looks softer, the ceiling seems less heavy, and a room with a fairly solid exterior gains a view of the sky. That is the particular appeal of clerestory glazing. It changes the atmosphere without requiring a whole wall of glass at eye level.</p>
<div class="summary-box" id="answer"><p class="kicker">The short answer</p><h2>Use high glazing where daylight matters more than a low view</h2><p>Clerestory windows are worth considering beside a close boundary, above kitchen units or in a room where the walls below need to remain useful. Check the sun, overlooking, shading, operation and cleaning access as part of the design. High glass still needs a complete window specification.</p></div>
<section id="meaning"><h2>What makes a window a clerestory?</h2><p>The defining feature is its high position in the wall. A clerestory may be a continuous band, a series of smaller panes or glazing between different roof heights. It does not have to wrap the entire room or belong to a dramatic new house.</p><p>A rooflight sits within the roof plane. Clerestory glazing is generally vertical or near vertical, which gives it a different relationship to the sky, roof edge and walls. Both can introduce daylight, but their construction, shading and cleaning arrangements differ. Choose for the room and the site rather than treating the names as interchangeable.</p><p>A high internal window can look similar from one side, yet it borrows light from another room. An exterior clerestory has a direct route to daylight. Our <a href="/blogs/home/internal-window-dark-hallway/">internal window guide</a> covers the borrowed-light version and the privacy questions it brings indoors.</p></section>
<section id="light"><h2>How high windows change the daylight</h2><p>When a window sits near the ceiling, light can reach upper surfaces that an ordinary low opening leaves shaded. A pale ceiling can help distribute that brightness, although the actual result depends on geometry and the light available outside. A narrow window looking into a tall neighbouring wall will behave differently from one looking at open sky.</p><p>Ask to see a section drawing. Roof height, eave depth and the position of the window head are difficult to judge from a floor plan. A clerestory can look generous in elevation while being tucked under an overhang that blocks much of its useful sky view.</p><p>Direct sun also needs attention. A high window can cast a beautiful moving patch across a wall, but that same patch may produce glare on a screen or heat the room at an inconvenient time. Consider the furniture layout and seasonal sun together. A daylight strategy should account for an ordinary working afternoon as well as the best morning photograph.</p></section>
<section id="privacy"><h2>Are clerestory windows more private?</h2><p>They can reduce direct views between a room and people outside at a similar ground level. A higher sill often lets a boundary-facing wall admit light without putting the sofa on display. That is useful on tight plots, where a conventional picture window might mostly frame a fence.</p><p>High does not automatically mean private. A neighbour upstairs, a sloping site or a raised terrace can change the sightline. Check the room from the relevant viewpoints, including after dark when indoor lights make the glazing more visible.</p><p>If privacy is the main reason for the window, draw those views before choosing the glass. Obscured glazing may suit some positions, but it changes the quality of the sky view and does not remove the need to consider placement. Privacy and daylight work best when they are designed together.</p></section>
<section id="rooms"><h2>Where clerestory windows earn their place</h2><h3>Above a kitchen wall</h3><p>A high band can bring daylight over a run of worktop or cabinets. Coordinate the sill with the joinery and leave space for the window frame, finishes and any opening mechanism. The drawing needs to show how the kitchen and glazing meet, not simply a bright strip above a generic cabinet block.</p><h3>Along a private living-room edge</h3><p>Keeping lower walls solid can provide room for art, books and a sofa while the upper glazing brings in sky. It is especially useful when the garden-facing side already has a generous opening. The high windows can balance the room's light rather than compete with the main view.</p><h3>In a compact extension</h3><p>A change in roof height can create space for a clerestory where the old and new buildings meet. Its usefulness depends on the surrounding roofs and orientation. Have the daylight assessed before committing to a complicated roof junction solely to obtain the window.</p><p>For another way to bring light into the centre of a plan, compare our <a href="/blogs/home/small-courtyard-house-ideas/">small courtyard house ideas</a>. The floor-space and construction implications are different, even when the aim is similar.</p></section>
<section id="details"><h2>Fixed or opening glazing?</h2><p>Fixed panes can offer a clean appearance and avoid the need for daily operation. They still need access for cleaning and maintenance. Opening units may support ventilation, but their benefit depends on a usable air path and the conditions outside.</p><p>If the window is out of reach, decide how it will open before ordering. Manual poles, controls and motors have different practical implications. Ask what happens during rain, whether operation is accessible to the people using the room and how a failed mechanism would be serviced.</p><p>Do the same for shading. A blind that cannot be reached easily is a poor answer to frequent glare. External shade, glass specification and the roof design should be considered together, with a solution appropriate to the climate and orientation.</p></section>
<section id="project"><h2>A project to study for the idea</h2><p><a href="https://www.boboarch.ca/projects/pp-laneway-house">Bobo Architecture's Clerestory Laneway House</a> uses staggered rooflines to bring northern light into a compact plan. The studio's project page describes the relationship between daylight, privacy and ceiling height, and lists the project as under construction at the time of review.</p><p>Study the roof section and the placement of the living spaces rather than treating the imagery as a universal recipe. Northern light has a specific meaning in the Vancouver setting. The equivalent orientation and shading choices in another climate may be different.</p></section>
<section class="article-faq"><h2>Clerestory window questions</h2><h3>Do clerestory windows have to open?</h3><p>No. They can be fixed or opening. Choose according to the ventilation strategy, weather exposure, access and maintenance needs.</p><h3>Will high windows make a room overheat?</h3><p>They can contribute to overheating if solar gain is poorly managed. Orientation, glazing, shade and the rest of the building design determine the risk.</p><h3>Can clerestory windows provide complete privacy?</h3><p>Not in every setting. Check views from higher neighbouring windows and changes in ground level, as well as views from the street.</p></section>
<section class="source-note"><h2>Sources and image note</h2><p>The project reference was checked against Bobo Architecture's own description linked above. Layout, maintenance and styling observations are by.foro editorial analysis. Images are AI-generated architectural visualisations of fictional homes, not images of the referenced project.</p></section>
<div class="article-end"><span>End</span><p>Published by by.foro Editorial on 10 October 2026. For corrections, contact <a href="mailto:hello@byforo.com">hello@byforo.com</a>.</p></div>
"""
},
{
    "slug": "built-in-window-seat-ideas",
    "title": "A Window Seat Should Be Somewhere You Actually Sit",
    "seo": "Built-In Window Seat Ideas: Comfort, Storage and Layout",
    "description": "Plan a built-in window seat with ideas for deep reveals, kitchen corners and storage, plus practical advice on cushion depth, back support and window access.",
    "deck": "The garden view is the attraction. A comfortable perch, a clear route and somewhere for your feet make you stay.",
    "alt": "Oak-lined window seat with an oatmeal cushion and storage drawers overlooking an autumn garden",
    "image_source": "exec-7ad2d007-4b81-483d-96aa-260e61902ec9.png",
    "inline_sources": [
        ("exec-4094b466-91d4-4d6f-a980-0c5cefe6a9b6.png", "kitchen-seat", "Built-in bench beneath a garden window beside a small round timber dining table"),
        ("exec-1cbe7f39-55e6-493d-ba6b-31a060368315.png", "seat-joinery", "Oak window-seat platform with a fitted cushion and aligned storage drawers")
    ],
    "keywords": ["built in window seat ideas", "window seat storage", "window seat cushion depth", "kitchen window bench"],
    "body": """
<p class="article-opening">A useful built-in window seat combines a good view with a comfortable place to sit, enough space for the way you use it and easy access to the window. Start with the finished seat height and depth, including cushions and back support. Then plan storage, heating, blinds and the route past it. The joinery should fit the room's daily life as carefully as it fits the opening.</p>
<p>Window seats are easy to love in photographs. A patch of daylight, one book, a cushion that appears never to need straightening. The less photogenic questions come later. Where do your feet go? Can you lean back? Does the drawer open when someone has pulled a chair up to the table?</p>
<div class="summary-box" id="answer"><p class="kicker">The short answer</p><h2>Test the sitting position before ordering the joinery</h2><p>Mock up the seat with the intended cushion and something firm behind your back. Check it while sitting upright and while leaning into a corner. Leave a clear route past the seat and make sure drawers, blinds and windows can operate. Comfort is easier to adjust with a temporary platform than after the cabinetry is installed.</p></div>
<section id="position"><h2>Find the place where you already want to pause</h2><p>The strongest location usually has something to look at and a little distance from busy movement. It might be a garden-facing recess, the end of a kitchen or a bay beside the living room. A seat facing a close blank wall can still be pleasant, but it needs something else to make the position attractive.</p><p>Look at how people cross the room. A seat between two frequently used doors may be convenient for putting on shoes, yet awkward for reading. That does not make it a failure. It means the design should support the shorter activity with an upright cushion and a clear path.</p><p>If you want a place to settle with a book, think about light, a surface for a cup and somewhere to put a phone. Those small provisions often matter more than the width of the window. Our <a href="/blogs/home/reading-nook-ideas/">reading nook guide</a> explores the same relationship between position and habit.</p></section>
<section id="comfort"><h2>Plan seat depth and back support together</h2><p>There is no useful single dimension that suits every window seat. A shallow upright perch, a dining bench and a deep lounging recess ask for different proportions. Begin with a chair or sofa you find comfortable and measure the usable area, then compare it with the proposed space.</p><p>Remember that a cushion changes the finished height, and a back cushion reduces usable depth. A beautifully deep timber platform may become surprisingly short once several large cushions are added. Conversely, an extra-deep seat with no back support can leave you perching at the front edge.</p><p>Test the corners. Many people sit sideways on a window seat, leaning against the reveal with their legs along the bench. That can be comfortable when the wall is softened by a firm cushion and the window hardware is out of the way. It is less appealing when a handle presses into your shoulder.</p><p>Consider access and mobility too. A very low seat can be difficult to rise from, and a high one may leave feet unsupported. The mock-up should be tried by the people who will actually use it, not judged only from across the room.</p></section>
<section id="types"><h2>Three built-in window seat ideas</h2><h3>A seat within a deep reveal</h3><p>Here the architecture does much of the work. Timber lining can make the recess feel warm and distinct, while a painted finish lets it blend with the wall. Keep the cushion simple enough that the depth and view remain visible. A shallow sill behind the cushion can be useful, provided it does not interfere with the window.</p><h3>A kitchen bench beneath a window</h3><p>A bench can free up the centre of a dining area, but it changes how people reach their seats. Check the table position with everyone seated and a chair pulled out opposite. A round or carefully sized table may leave an easier route than a large rectangular one.</p><p>Dining use generally asks for a more upright position than lounging. Test the finished table and seat heights together, including the cushion. A dining bench should not require a stack of loose cushions just to bring you close enough to your plate.</p><h3>A bench across a wider wall</h3><p>Extending beyond the window can create useful storage or a long place to sit. Let the joinery relate to the room's other horizontal lines. A continuous bench can feel settled when it ends clearly at a wall or cabinet, rather than stopping at an arbitrary point.</p></section>
<section id="storage"><h2>Choose storage you can reach without dismantling the seat</h2><p>Drawers are convenient for frequently used things when there is space to pull them out. Check their travel against tables, rugs and nearby doors. A large drawer can hold plenty and still be irritating if its handle catches your calves or it cannot open during dinner.</p><p>A lift-up lid may use the cavity efficiently, but the cushion and anything resting on it have to move. That can suit occasional storage, such as spare blankets. It is less practical for the book, charger or shoes you want several times a day.</p><p>Open shelves make the contents visible. Use them when you genuinely want books or baskets in the room, not because the joinery drawing looks empty without them. A closed front is often calmer in a small space with a busy garden view.</p></section>
<section id="details"><h2>Leave room for windows, curtains and warmth</h2><p>Open the window on the drawing and in the existing room. Inward-opening units can meet cushions or a seated person, while handles may become difficult to reach behind a deep platform. Blinds and curtains need a clear route too. Decide whether fabric will stop at the sill, sit within the reveal or fall elsewhere.</p><p>Check any radiator, grille or ventilation opening before enclosing the area. A seat should not compromise the heating or airflow the room relies on. Ask the designer how access for servicing will be maintained and whether the new joinery affects condensation-prone surfaces.</p><p>Choose upholstery for sunlight, cleaning and the way the seat will be used. Removable covers can be helpful in a kitchen or family room. Ask the upholsterer about foam, support and fabric suitability rather than treating a thin decorative pad as a finished seating solution.</p></section>
<section id="project"><h2>A real project that makes the seat part of the plan</h2><p>In <a href="https://www.archdaily.com/797663/harvey-road-erbar-mattes">Erbar Mattes' Harvey Road project</a>, the architects describe a deep window seat facing the garden, with toy storage beneath the upholstered bench. The seat belongs to the everyday family space and connects to the terrace through an opening window.</p><p>The useful lesson is the combination of view, storage and access, rather than a particular timber or cushion colour. A well-placed seat can become part of circulation and family life instead of an isolated feature. The idea has something in common with the <a href="/blogs/home/engawa-modern-house-ideas/">engawa</a>, where the edge between room and garden becomes somewhere to spend time.</p></section>
<section class="article-faq"><h2>Window seat questions</h2><h3>How deep should a built-in window seat be?</h3><p>It depends on whether it is for upright sitting, dining or lounging. Include the back cushion in the calculation and test a full-size mock-up before committing.</p><h3>Are drawers better than a lift-up lid?</h3><p>Drawers are usually easier for frequent access if the room allows them to open fully. A lid can suit items used less often, but requires moving the cushion.</p><h3>Can you build a seat over a radiator?</h3><p>Only with a suitable design that maintains heating performance, ventilation and service access. Have the specific arrangement assessed before enclosing it.</p></section>
<section class="source-note"><h2>Sources and image note</h2><p>The project example is drawn from the architects' description of Harvey Road linked above. Comfort, storage and styling observations are by.foro editorial analysis. Images are AI-generated architectural visualisations of fictional rooms, not images of the referenced project.</p></section>
<div class="article-end"><span>End</span><p>Published by by.foro Editorial on 10 October 2026. For corrections, contact <a href="mailto:hello@byforo.com">hello@byforo.com</a>.</p></div>
"""
}
]

if __name__ == "__main__":
    builder.main()
