"""Build three architecture inspiration articles and their responsive imagery."""
from __future__ import annotations
import html
import json
import re
from pathlib import Path
from PIL import Image
import build_august_two_features as base
from build_september_25_guides import make_body

ROOT = Path(__file__).resolve().parents[1]
SOURCE = Path(r"C:\Users\filip\.codex\generated_images\01a0d9de-ac34-7932-beb5-c4d3df8b396e")
DATE = "2026-09-27"
base.PUBLISHED, base.PUBLISHED_LABEL, base.PUBLISHED_ISO = DATE, "27 September 2026", DATE + "T12:00:00+02:00"

STORIES = [
{
 "slug": "small-courtyard-house-ideas",
 "title": "Small Courtyard Houses Put the Best View on the Inside",
 "seo": "Small Courtyard House Ideas: Layout, Light and Privacy",
 "description": "Explore small courtyard house ideas, from L-shaped layouts to central gardens, with practical guidance on daylight, privacy, planting and everyday use.",
 "deck": "A private patch of sky can change the feeling of an entire house. The plan has to earn the space it takes.",
 "alt": "Compact courtyard framed by pale rendered walls and timber doors, with a young tree, stone paving and two woven chairs",
 "image_source": "exec-b34da12d-b2ba-4ffd-a803-6287ba0cddc8.png",
 "inline_sources": [
  ("exec-a68bf514-f651-4001-9e5a-880ba3b92dc9.png", "courtyard-light", "Dining room opening through a timber-framed sliding door to a narrow planted courtyard"),
  ("exec-eb0bb91c-5cec-4983-bad5-0d629bda5719.png", "courtyard-detail", "Young courtyard tree in a gravel bed beside jointed stone paving and a low rendered bench")
 ],
 "keywords": ["small courtyard house ideas", "courtyard house layout", "narrow house courtyard", "private courtyard garden"],
 "body": """
<p class="article-opening">A small courtyard house arranges part of its living space around an outdoor area within the building's outline. The courtyard might sit at the centre, occupy a corner or form a gap between an old house and a new extension. Its value is simple: rooms gain a private view of planting and sky, even when the street outside is busy or the neighbours are close.</p>
<p>The photographs that make you save these houses usually contain very little. A tree, a patch of stone, a door left open. What you are responding to is the relationship between the room and the garden. The garden feels close enough to belong to the room, while remaining unmistakably outside.</p>
<div class="summary-box" id="answer"><p class="kicker">The short answer</p><h2>Give the courtyard a job before giving it a look</h2><p>Decide whether the courtyard needs to bring daylight into deep rooms, provide a private place to sit or create a garden view. Choose the layout around that priority. Keep the planting simple, leave a clear walking route and plan shade, drainage and maintenance at the same time as the doors.</p></div>
<section id="layouts"><h2>Three small courtyard house layouts worth studying</h2><h3>The L-shaped courtyard</h3><p>Two wings meet at a corner, leaving the garden open on the other sides. A boundary wall or planting can provide enclosure. This is often a useful starting point when a living room and kitchen both need access outside, but the plot does not justify wrapping rooms around all four sides.</p><p>The corner matters. Put the doorways where people naturally move, rather than using every available wall for glass. A protected corner can hold a small table. The open edge can frame a tree or the wider garden. The courtyard still needs somewhere for the eye to rest.</p><h3>The U-shaped courtyard</h3><p>Three sides of the house frame the outdoor space. The result can feel sheltered and generous, but the wings may shade each other. Look at the courtyard in section, with wall heights and roof overhangs, as well as on a floor plan. A lovely square on paper can become a dark slot when the surrounding rooms rise too high.</p><h3>The central courtyard</h3><p>A garden or lightwell sits inside the house, often with rooms looking into it from several directions. This is compelling on a deep urban plot where side windows offer little privacy. It also takes space from the interior, adds external wall and creates more details to maintain. A central courtyard needs to improve several rooms to justify those costs.</p></section>
<section id="light"><h2>Daylight depends on more than the amount of glass</h2><p>A courtyard can bring daylight to the middle of a house, but its shape, orientation and surroundings determine how much. Ask an architect to study the sun across the seasons and the effect of nearby buildings. A narrow courtyard behind high walls behaves very differently from a broad, shallow one.</p><p>On a small site, a pale wall can become a useful backdrop for reflected light. Keep that surface reasonably clear rather than covering every wall with climbing plants. A darker wall may make planting look beautiful, yet absorb light that a neighbouring room needs. Both choices are valid; decide which room benefit matters most.</p><p>Glass also brings responsibility. Roof overhangs, shutters or external screens can help manage glare and summer heat, but they must suit the orientation and local climate. Do not assume that an internal garden automatically cools the house. Air needs a route in and out, and shaded outdoor space needs a design suited to the weather where you live.</p></section>
<section id="privacy"><h2>Privacy has to work between your own rooms too</h2><p>It is easy to concentrate on keeping neighbours out and forget the new views across the courtyard. A bedroom facing the kitchen may gain daylight while losing somewhere private to get dressed. Offset windows, place a planted bed in the sightline or use a smaller opening where a full wall of glass is unnecessary.</p><p>Think about sound as well. A table outside a bedroom window can become awkward during a late dinner. If the courtyard is mainly for social use, give the living spaces its most direct edges and let bedrooms look towards a quieter part of the garden.</p><p>Check the view from upstairs and from neighbouring windows before deciding how enclosed the space feels. A tall hedge along one boundary cannot solve every angle. Sometimes a small canopy over the sitting area is more useful than making the entire courtyard darker with higher walls.</p></section>
<section id="planting"><h2>One good tree is often enough</h2><p>Start with what you want to see from indoors. A fine branch structure can be lovely in winter. A broad leaf can soften a hard wall. A scented plant near a doorway adds something a photograph cannot show. Choose species for the actual light, soil volume and climate, with advice on mature size and roots.</p><p>A courtyard is a poor place to buy a tree solely because it looks good in a pot today. Allow for its grown canopy, the distance to the building and access for pruning. If the soil area is small, a generous container may be more manageable, but it brings its own watering and drainage needs.</p><p>Keep paving and planting in clear groups. A usable strip of paving beside the doors and one substantial planted area usually feels calmer than many tiny beds threaded between chairs. The same restraint works in our <a href="/blogs/home/greek-chic-interiors/">Greek chic interiors guide</a>: material and proportion can carry the mood without a collection of decorative references.</p></section>
<section id="daily"><h2>Design the ordinary Tuesday, not just the open-door photograph</h2><p>Where will wet shoes go? Can a cleaner reach the outside of the glass? Will leaves collect in the threshold channel? These questions belong in the design brief. Drainage, paving falls and accessible gutters are part of what lets a quiet courtyard stay quiet.</p><p>Leave enough room to move a chair without blocking the route between rooms. Think about where an outdoor cushion will live during bad weather. If the courtyard is tiny, a fixed bench or a single chair may serve it better than a complete dining set. Our guide to <a href="/blogs/home/outdoor-space-that-feels-expensive/">a considered outdoor space</a> explores the same discipline at a smaller scale.</p><p>At night, a dark courtyard can turn large windows into mirrors. One modest light on planting or a wall can restore the view. Keep it low and shielded so it does not shine into bedrooms or overwhelm the interior lamps.</p></section>
<section id="projects"><h2>Two real projects to learn from</h2><p><a href="https://www.chrofi.com/projects/courtyard-house-b">CHROFI's Courtyard House</a> demonstrates how a compact home can combine an enclosed garden with a generous verandah. The architects describe an adaptable plan and a sliding screen that changes the connection to the wider landscape. Study the way enclosure can vary, rather than copying the finishes.</p><p>The architects' account of <a href="https://www.archdaily.com/783537/petersham-courtyard-house-adriano-pupilli-architects">Adriano Pupilli Architects' Petersham Courtyard House</a> shows a different approach on a narrow urban lot. Its rear living spaces are reworked around garden views, daylight and breezes. The useful lesson is that a courtyard idea can guide a renovation without becoming a completely new house.</p></section>
<section class="article-faq"><h2>Small courtyard house questions</h2><h3>Can a courtyard work in a narrow house?</h3><p>Yes, but it needs careful planning. A side courtyard, corner garden or small opening between building sections may work better than a central courtyard that consumes too much floor space.</p><h3>Is a courtyard house always more private?</h3><p>No. It can protect you from street views, but windows facing each other and overlooking neighbours still need to be considered.</p><h3>Can a courtyard make a house cooler?</h3><p>It can support shade and ventilation when designed for the local climate. An unshaded or poorly ventilated courtyard can also become hot.</p></section>
<section class="source-note"><h2>Sources and image note</h2><p>Project references come from CHROFI and the architects' description of Petersham Courtyard House linked above. Layout, planting and everyday-use observations are by.foro editorial analysis. Images are AI-generated architectural visualisations of fictional homes, not photographs of the referenced projects.</p></section>
<div class="article-end"><span>End</span><p>Published by by.foro Editorial on 27 September 2026. For corrections, contact <a href="mailto:hello@byforo.com">hello@byforo.com</a>.</p></div>
"""
},
{
 "slug": "breeze-block-privacy-wall-ideas",
 "title": "Breeze Block Walls Give the Garden an Edge, Not a Lid",
 "seo": "Breeze Block Privacy Wall Ideas for Small Gardens",
 "description": "Find breeze block privacy wall ideas for entrances and small gardens, with guidance on pattern, sightlines, planting, colour and planning a durable screen.",
 "deck": "A patterned wall can screen a terrace and still let the garden breathe. Start with the view through it.",
 "alt": "Cream square-opening breeze-block screen between solid piers beside a timber front door and gravel planting",
 "image_source": "exec-b61bc24c-6e74-4afa-90dd-d5da7729831c.png",
 "inline_sources": [
  ("exec-71e52d60-354b-4875-ba2b-1623f574bed9.png", "breeze-terrace", "Small terrace with a square-opening concrete screen, timber bench and clay pots"),
  ("exec-58cdb3ea-ae99-458c-92b8-10292b07ffd7.png", "breeze-detail", "Cast concrete screen blocks with regular square openings, mortar joints and foliage beyond")
 ],
 "keywords": ["breeze block privacy wall", "breeze block wall ideas for small gardens", "decorative concrete screen wall", "breeze block entrance ideas"],
 "body": """
<p class="article-opening">A breeze block privacy wall uses patterned concrete or masonry units to create a screen with openings. It can soften a view from the street, define a garden terrace or separate an entrance from a sitting area while allowing some light and air through. The pattern is only part of the decision. Height, position and the angle of the view determine how private it will feel.</p>
<p>These walls have an appealing contradiction. They feel solid enough to give a garden structure, yet the space beyond remains visible in fragments. A leaf appears in one opening, a pale wall in another. In the right place, a short screen does more for a terrace than a large collection of pots and outdoor accessories.</p>
<div class="summary-box" id="answer"><p class="kicker">The short answer</p><h2>Use a screen where you need partial separation</h2><p>Place a breeze block wall across the view you want to soften, then check it from both sides at seated and standing height. Choose one pattern, give it a clear edge and keep nearby planting simple. For complete privacy, an open screen may need a second layer or a different kind of wall.</p></div>
<section id="privacy"><h2>How much privacy does a breeze block wall provide?</h2><p>Less than a solid wall, and not always as much as its photograph suggests. Openings that look discreet from an angle can reveal everything when viewed straight on. Before selecting a pattern, stand where a passer-by or neighbour would stand and consider the sightline towards your chair, dining table or doorway.</p><p>Light changes that view. In daylight, plants and a darker background can make openings feel less revealing. At night, a brightly lit terrace behind the screen may become easy to see from outside. Test the idea under both conditions rather than treating the wall as permanent visual cover.</p><p>The manufacturer's product drawings can help compare patterns. <a href="https://www.orco.com/products/concrete-masonry-units/product-2/breeze-block">ORCO's breeze block range</a>, for example, shows several configurations and advises checking colour and texture with physical samples. The shape of the opening affects what is visible, as well as the character of the wall.</p></section>
<section id="placement"><h2>Three places where a short screen earns its space</h2><h3>Beside the front entrance</h3><p>A screen can separate the approach from a bedroom window or a small outdoor chair. Keep the actual route to the door obvious. A decorative wall becomes frustrating if visitors have to guess which side to walk around or if a delivery cannot fit past it.</p><p>Let the wall relate to something already there: the edge of a porch, a planted bed or a change in paving. That makes it feel part of the architecture. A patterned rectangle placed in the middle of an otherwise empty garden can look more like a sample panel.</p><h3>Along one side of a terrace</h3><p>Use the screen to protect the most exposed edge. The other sides can remain lighter, especially in a small garden. A bench placed parallel to the wall leaves the open centre available for movement, and lets the patterned surface become a backdrop rather than an obstacle.</p><h3>Between two garden areas</h3><p>A short wall can distinguish a dining area from a path or a utility corner without enclosing both. Keep its end visible and leave a comfortable passage. You should be able to move a chair, watering can or wheelbarrow without negotiating a tight turn.</p></section>
<section id="pattern"><h2>Choose a pattern you can live with every day</h2><p>Simple square or rectangular openings usually sit comfortably beside contemporary doors and windows. Curves, circles and more decorative patterns can be beautiful, but they deserve quieter surroundings. If the garden already contains patterned tile, elaborate railings or several kinds of brick, the simplest screen may be the strongest choice.</p><p>Look at a full panel, not a single block. A pattern that feels delicate in your hand can become busy when repeated across a large wall. Ask for dimensions and make a rough paper or cardboard mock-up at the scale of several units. Even a small sample area helps you judge how much solid material the wall introduces.</p><p>Use one pattern throughout a short screen. Mixing patterns tends to make the wall compete with the planting. If you want variation, get it from light passing through the openings, the depth of the joints and the way the garden changes beyond.</p></section>
<section id="materials"><h2>Colour and texture can keep it from feeling like a theme</h2><p>White breeze blocks are strongly associated with mid-century houses, but they do not require a Palm Springs garden around them. Pair a pale screen with local planting, a simple timber door and paving that belongs to the house. The result can feel quite ordinary, in the best sense.</p><p>Natural concrete has a different weight. It can sit well against brick, dark timber or stone, though its grey may look colder on a shaded site. Put the sample outdoors beside the actual materials and look at it after rain. Wet concrete, pale render and timber do not all change colour in the same way.</p><p>If you want to paint the screen, ask the supplier which coating system suits it and how repainting will work. Every opening adds an edge to maintain. A colour you love on a flat sample may become more intense across dozens of recessed faces.</p><p>For a warmer material palette, our <a href="/blogs/home/greek-chic-interiors/">Greek chic interiors guide</a> offers a useful reference for combining pale mineral surfaces, weathered timber and restrained colour.</p></section>
<section id="planting"><h2>Let the planting soften the base</h2><p>A low planted strip can make the screen feel settled rather than dropped onto the paving. Leave the pattern visible above it. You do not need a climber filling every opening, particularly if the wall's purpose is to allow air and filtered views through.</p><p>Choose plants for the sun, soil and watering conditions on each side. A screen can cast useful shade, but it is not a substitute for checking the site. Allow enough room for mature growth and for access to the wall. Dense planting pressed against a surface can make cleaning and repairs awkward.</p><p>Keep pots in one or two clear groups. A small terrace already has the repeated geometry of the blocks; lots of little containers can make it visually restless. Our <a href="/blogs/home/outdoor-space-that-feels-expensive/">outdoor space guide</a> explains how fewer, better-scaled objects can make a compact area feel more generous.</p></section>
<section id="build"><h2>Plan the structure before falling in love with the pattern</h2><p>A breeze block screen is masonry, not lightweight garden decoration. Foundations, reinforcement, height, wind exposure and connections need a design appropriate to the units and the site. Follow the supplier's system and use a qualified professional for the structural design and installation where needed.</p><p>Check local requirements for boundary walls and permissions before ordering. Do not assume decorative units can carry a roof or replace a structural wall. Product specifications and an engineer's advice take priority over a photograph, including the inspiration images in this article.</p><p>Ask how the top and ends will be finished. A simple cap, a solid pier or a return into another wall gives the pattern a clear boundary. It also affects how water runs off and how the screen meets the rest of the building. Those details are worth discussing early, because they are hard to hide later.</p></section>
<section class="article-faq"><h2>Breeze block wall questions</h2><h3>Is a breeze block wall completely private?</h3><p>No. Its openings provide filtered separation. Straight sightlines and night lighting can make the space behind it visible.</p><h3>Can breeze blocks work in a small garden?</h3><p>Yes. A short screen on one exposed edge can be more useful than enclosing the whole area. Keep the route through the garden clear.</p><h3>Are decorative breeze blocks load-bearing?</h3><p>It depends on the specific product and engineered design. Never assume they are suitable for structural use without checking the manufacturer's information and professional advice.</p></section>
<section class="source-note"><h2>Sources and image note</h2><p>Product and pattern information was checked against ORCO's breeze block range linked above. Placement, sightline and styling guidance is by.foro editorial analysis. Images are AI-generated architectural visualisations of fictional settings. They illustrate design ideas and are not construction drawings.</p></section>
<div class="article-end"><span>End</span><p>Published by by.foro Editorial on 27 September 2026. For corrections, contact <a href="mailto:hello@byforo.com">hello@byforo.com</a>.</p></div>
"""
},
{
 "slug": "engawa-modern-house-ideas",
 "title": "The Engawa Makes Room for Doing Very Little",
 "seo": "What Is an Engawa? Japanese Veranda Ideas for Modern Homes",
 "description": "Discover what an engawa is and how its Japanese architectural principles inspire modern verandas, sheltered terraces and quiet spaces beside the garden.",
 "deck": "A narrow strip beside the garden can be a passage, a seat and the most inviting part of the house.",
 "alt": "Timber engawa beneath supported roof eaves beside sliding doors and a planted Japanese-style gravel garden",
 "image_source": "exec-9f26f71d-9de0-4534-885d-f5e405c47796.png",
 "inline_sources": [
  ("exec-71a9f56e-9bc2-4587-bab6-1d12dab9603d.png", "engawa-modern", "Modern sheltered timber terrace with supporting posts, sliding glass doors and gravel planting"),
  ("exec-10c3a0db-b70b-4833-acb4-6a3b8d89a3ff.png", "engawa-detail", "Weathered veranda boards and sliding-door tracks beside a timber post and gravel garden")
 ],
 "keywords": ["what is an engawa", "modern engawa design", "Japanese veranda ideas", "engawa indoor outdoor space"],
 "body": """
<p class="article-opening">An engawa is a veranda or perimeter space beside the rooms of a Japanese dwelling. It can be sheltered, partly enclosed by sliding doors or exposed to the outdoors, depending on the building. Its appeal lies in the way it lets you move, sit and look into the garden without making a sharp choice between being inside and being outside.</p>
<p>There is often very little to buy for it. A cushion may be enough. The important things are the roof above, the edge below, the doors behind and the view ahead. It is a useful architectural idea for anyone who has built a terrace and then found that it feels too exposed to use.</p>
<div class="summary-box" id="answer"><p class="kicker">The short answer</p><h2>Borrow the sheltered edge, not a collection of Japanese props</h2><p>For a modern home, translate the engawa through a narrow, usable place beside the garden, some shelter, a comfortable threshold and an opening back to the room. Leave space for sitting as well as passing. A timber deck alone does not create the same relationship.</p></div>
<section id="meaning"><h2>What does engawa mean in Japanese architecture?</h2><p>The <a href="https://www.aisf.or.jp/~jaanus/deta/e/engawa.htm">JAANUS Japanese architecture dictionary</a> describes the engawa as an area beside or around a room's tatami floor, and distinguishes forms with differing exposure and floor construction. The term covers more than a single open deck detail. Its position at the edge of the room is the constant.</p><p>In a traditional setting, sliding partitions can change how that edge relates to the interior and the weather. Open the doors and the room seems to extend towards the garden. Close them and the engawa can become a protected passage or a separate perimeter zone. The building has several ways to meet the day.</p><p>That flexibility explains why the engawa remains interesting beyond a traditional house. It offers a way to make a boundary inhabitable. You can stop there, rather than simply crossing it.</p></section>
<section id="difference"><h2>Engawa, veranda and terrace: what is the difference?</h2><p>The words overlap, and buildings vary. A terrace is often a broader outdoor platform used for dining or seating. A veranda is typically a roofed outdoor space adjoining a building. An engawa is closely tied to the perimeter of the Japanese room and can also serve as circulation. It often feels like a slender continuation of the floor rather than a separate outdoor destination.</p><p>Those distinctions help when looking for inspiration, but they need not become a naming exercise. If your modern home has a sheltered strip outside a living room, the useful question is whether it allows a slower relationship with the garden. Can you sit at the edge? Can someone pass behind you? Does the roof make it comfortable for more than one brief season?</p><p>Calling a conventional patio an engawa does not improve it. Working on those relationships might.</p></section>
<section id="shelter"><h2>Start with the roof and the view</h2><p>The eave gives this kind of space much of its character. It makes a shady foreground through which the garden appears brighter. It also offers protection from some weather, though wind-driven rain can still reach the boards. The depth, orientation and local climate need to be considered together.</p><p>Too much cover can leave the room behind dark. Too little can make the outside edge uncomfortable or expose the door to rain. An architect can study both conditions before an overhang is fixed. The aim is a place that feels usable, with daylight still reaching the room.</p><p>Give the view a quiet structure. A tree, a change in ground level or a modest planted bed can be enough. You do not need to install a stone lantern, bamboo fountain and ornamental bridge to make the garden relate to the architecture. Our <a href="/blogs/home/small-courtyard-house-ideas/">small courtyard house guide</a> explores another way to bring a close garden view into daily life.</p></section>
<section id="width"><h2>Make it wide enough for the way you want to use it</h2><p>A passage and a place to sit ask for different amounts of space. Mark the proposed edge on the ground and try it with the actual chair, stool or cushion you would use. Walk past someone seated there. Open the door. The width needs to work with bodies and door movement, not just the elevation drawing.</p><p>A low seat or floor cushion keeps the view open and makes the edge feel informal. A normal chair can be better for comfort and accessibility. Neither choice should force people into the path between doors. Leave the long line clear enough to be used as a passage.</p><p>If the available strip is very narrow, create one slightly wider stopping place rather than attempting to furnish its whole length. A small recess beside a door can do more than a row of seats nobody can pass.</p></section>
<section id="threshold"><h2>The threshold deserves more attention than the furniture</h2><p>Look closely at photographs of traditional and modern examples. The interest often sits in the meeting of boards, tracks, posts and the floor inside. A good threshold feels clear and deliberate. It does not need to be perfectly flush to be beautiful, but it should be safe and appropriate for the people using it.</p><p>Weatherproofing, drainage, level changes and thermal separation need a technical solution for the specific building. Do not remove a step or continue indoor boards outdoors simply to imitate a photograph. In a wet or cold climate, a sheltered terrace may need to remain clearly outside the heated envelope.</p><p>Choose exterior timber or another suitable surface with maintenance in mind. Ask how it behaves when wet, how it will weather and which fixings suit it. Subtle wear can be attractive; trapped water and slippery boards are not part of the intended atmosphere.</p></section>
<section id="modern"><h2>Three ways to translate the idea into a modern home</h2><h3>A sheltered edge outside the living room</h3><p>Keep the floor material quiet, provide an overhead cover and let the door opening remain the main event. One stool or chair near the edge is often enough. The space should be somewhere to carry a cup of tea, not an outdoor room requiring a full furniture collection.</p><h3>A garden-facing passage</h3><p>When a house has several rooms facing the same garden, a covered external passage can link them. It needs a route that feels practical in the local weather and respects bedroom privacy. A garden edge should not become a public corridor outside someone's sleeping space.</p><h3>A protected balcony</h3><p>In a flat, you may be able to borrow the feeling through a quiet floor surface, one comfortable seat and a view of planting. Work within the existing balcony structure and building rules. Avoid overloading the edge with pots or trying to manufacture traditional architecture with decorative panels.</p><p>The broader principle fits the <a href="/blogs/home/lived-in-interior-design-2026/">lived-in home</a>: make a place for a real habit before deciding what the photograph should contain.</p></section>
<section id="rest"><h2>Leave something unplanned</h2><p>An engawa-inspired space does not need a prescribed activity. It can be where you watch the rain, wait for someone to get ready or put down a basket before opening the door. That freedom is part of its usefulness.</p><p>Keep some of the floor empty. Put the practical things nearby, such as a dry place for cushions, without making storage the view. Let the garden have ordinary seasonal changes rather than holding it to one perfect composition.</p><p>If you find yourself adding more furniture to make the space seem finished, sit there first. You may discover that what it needs is a better roof edge, a clearer view or a seat at the right height. Those changes make it easier to use, which is a more lasting kind of beauty.</p></section>
<section class="article-faq"><h2>Engawa questions</h2><h3>Is an engawa always outside?</h3><p>No. Forms vary, and it can be partly within the building or protected by sliding doors. It occupies the edge beside the main rooms.</p><h3>Can a modern house have an engawa?</h3><p>Yes, or a contemporary space informed by its principles. Shelter, a usable floor edge and a close relationship to the garden matter more than copying traditional finishes.</p><h3>Is an engawa the same as a deck?</h3><p>No. A deck is a platform. The engawa's meaning comes from its position beside rooms and its role as a passage, threshold and place to pause.</p></section>
<section class="source-note"><h2>Sources and image note</h2><p>Terminology was checked against the JAANUS architecture dictionary linked above. Modern adaptations and practical observations are by.foro editorial analysis. Images are AI-generated architectural visualisations of fictional settings, not documentary photographs of Japanese heritage buildings.</p></section>
<div class="article-end"><span>End</span><p>Published by by.foro Editorial on 27 September 2026. For corrections, contact <a href="mailto:hello@byforo.com">hello@byforo.com</a>.</p></div>
"""
}
]

def save_image(source_name: str, stem: str) -> None:
    destination = ROOT / stem.lstrip("/")
    destination.parent.mkdir(parents=True, exist_ok=True)
    with Image.open(SOURCE / source_name) as source:
        image = source.convert("RGB")
        if image.size != (1536, 1024):
            image = image.resize((1536, 1024), Image.Resampling.LANCZOS)
        image.save(str(destination) + ".jpg", quality=85, optimize=True)
        for width, suffix in [(1536, ""), (960, "-960"), (640, "-640")]:
            resized = image if width == 1536 else image.resize((width, round(width * 2 / 3)), Image.Resampling.LANCZOS)
            quality = 80
            target = Path(str(destination) + suffix + ".webp")
            while True:
                resized.save(target, quality=quality, method=6)
                if target.stat().st_size <= (150000 if width == 1536 else 100000) or quality <= 40:
                    break
                quality -= 5

def main() -> None:
    catalogue_path = ROOT / "content/articles.json"
    catalogue = json.loads(catalogue_path.read_text(encoding="utf-8"))
    additions = []
    for story in STORIES:
        story["department"], story["topic"] = "home", "architecture"
        assert "—" not in json.dumps(story, ensure_ascii=False)
        url = f'/blogs/home/{story["slug"]}/'
        hero = f'/assets/images/blogs/home/{story["slug"]}/{story["slug"]}-hero'
        for source, stem in [(story["image_source"], hero)] + [(src, f'/assets/images/blogs/home/{story["slug"]}/{name}') for src, name, _ in story["inline_sources"]]:
            save_image(source, stem)
        body = make_body(story)
        words = len(re.findall(r"\b[\w’-]+\b", re.sub(r"<[^>]*>", " ", story["body"])))
        document = base.page(url, story["seo"], story["title"], story["description"], story["deck"], "Home", "Architecture", hero, story["alt"], body, "BlogPosting", words, story["keywords"])
        destination = ROOT / url.strip("/") / "index.html"
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(document, encoding="utf-8", newline="\n")
        additions.append({"title":story["title"],"seoTitle":story["seo"],"department":"home","topic":"architecture","published":DATE,"readingMinutes":max(1,round(words/195)),"readingWordsPerMinute":195,"url":url,"excerpt":story["deck"],"metaDescription":story["description"],"image":{"webp":hero+".webp","fallback":hero+".jpg","alt":story["alt"],"width":1536,"height":1024},"articleSection":"Architecture","breadcrumbTopic":True})
        print(url, words)
    urls = {x["url"] for x in additions}
    catalogue_path.write_text(json.dumps(additions + [x for x in catalogue if x["url"] not in urls], ensure_ascii=False, indent=2)+"\n",encoding="utf-8")

if __name__ == "__main__":
    main()
