"""Build four by.foro editorial features for 20 August 2026."""
from __future__ import annotations

import html
import json
import re
from pathlib import Path

import build_august_two_features as base


ROOT = Path(__file__).resolve().parents[1]
PUBLISHED = "2026-08-20"
PUBLISHED_LABEL = "20 August 2026"
PUBLISHED_ISO = "2026-08-20T20:00:00+02:00"
base.PUBLISHED = PUBLISHED
base.PUBLISHED_LABEL = PUBLISHED_LABEL
base.PUBLISHED_ISO = PUBLISHED_ISO


def picture(root: str, name: str, alt: str) -> str:
    return f'''<figure class="media article-inline-image"><picture><source type="image/webp" srcset="{root}/{name}-640.webp 640w, {root}/{name}-960.webp 960w, {root}/{name}.webp 1536w" sizes="(max-width: 760px) calc(100vw - 2rem), 760px"><img src="{root}/{name}.jpg" width="1536" height="1024" loading="lazy" decoding="async" alt="{html.escape(alt)}"></picture></figure>'''


DORM_URL = "/blogs/home/dorm-desk-hutch-ideas/"
DORM_ROOT = "/assets/images/blogs/home/dorm-desk-hutch-ideas"
DORM_BODY = f'''<div class="article-layout"><aside class="article-aside"><p class="kicker">The room plan</p><ol><li><a href="#answer">The short answer</a></li><li><a href="#measure">Measure first</a></li><li><a href="#work-zone">Protect the work zone</a></li><li><a href="#storage">Build useful storage</a></li><li><a href="#lighting">Light and power</a></li><li><a href="#style">Make it look considered</a></li><li><a href="#mistakes">Mistakes to avoid</a></li></ol><button class="copy-link" data-copy-link type="button">Copy link</button></aside><div class="article-body">
<p class="article-opening">The best dorm desk hutch uses height without consuming the desk below it. Measure the supplied desk, choose a shallow freestanding unit, preserve a clear rectangle large enough for a laptop and open notebook, and keep power access visible. A beautiful setup is not the one with the most organisers. It is the one that lets you begin work without moving anything first.</p>
<p>That distinction is easy to lose during move-in season, when every empty shelf looks like an invitation to buy another bin. A dorm desk is already asked to do too much. It can be a study surface, breakfast table, dressing area, charging station and the only piece of furniture that belongs entirely to one resident. The hutch should make those changes easier, not become a stage set that has to be dismantled before an essay can begin.</p>
<div class="summary-box" id="answer"><p class="kicker">The useful formula</p><h2>A shallow shelf above, a generous rectangle below</h2><p>Start with the desk dimensions and residence-hall rules. Keep at least 60 centimetres of clear width for a laptop and notebook, avoid a shelf so deep that it darkens the worktop, and stabilise any freestanding hutch according to its instructions. Store daily supplies at hand level, occasional objects higher up and visual clutter inside one opaque box. Leave outlets, ventilation and the path to the door unobstructed.</p></div>
<section id="measure"><h2>Measure the room before you shop</h2><p>Google reported in July 2026 that &ldquo;desk hutch for dorm&rdquo; was among the top-trending &ldquo;for dorm&rdquo; searches in the United States. The interest makes sense, but the phrase hides a practical problem: dorm desks are not standardised. A product that fits one residence hall can cover a light, collide with a fixed shelf or leave too little clearance for a monitor in another.</p><p>Record the desk&rsquo;s full width, usable depth and height. Then measure from the worktop to any fixed shelf, window ledge, sprinkler clearance zone or wall-mounted fitting. Note the position of outlets and data ports. Photograph the measurements with the tape still in frame, because a number typed into a phone is surprisingly easy to mislabel during a crowded shopping trip.</p><h3>The five dimensions that actually matter</h3><ol><li><strong>External width:</strong> the hutch must sit fully on the desk without overhanging edges or blocking drawers.</li><li><strong>Foot depth:</strong> measure how much of the worktop the side supports consume, not just the shelf depth listed online.</li><li><strong>Clearance height:</strong> confirm that a laptop screen, monitor or mirror can open comfortably below the first shelf.</li><li><strong>Internal shelf depth:</strong> eight to twelve inches is often enough for books and small storage without creating a dark cave beneath.</li><li><strong>Total height:</strong> check local rules and keep clear of sprinklers, detectors and anything the housing office says must remain accessible.</li></ol><p>Residence-hall rules take priority over a styling guide. Some universities limit the size or material of extra furniture, require supplied furniture to remain in the room and prohibit wall anchoring, while others provide a shelf already. Manhattan University, for example, publishes a specific size allowance for desk hutches. Treat that as evidence that policies can be precise, not as a universal measurement.</p></section>
{picture(DORM_ROOT, "dorm-desk-work-zone", "Compact dorm desk shelf with an open notebook, laptop stand, vertical files and a large clear writing area")}
<section id="work-zone"><h2>Protect the work zone before styling the shelf</h2><p>Mark the space you need for the largest ordinary task, not the most photogenic one. For many students that means an open 13-inch laptop beside an A4 notebook, with enough depth for forearms to rest on the desk. A student in architecture, fashion or art may need a cutting mat or sketchbook instead. Build the hutch around that rectangle and refuse to place permanent objects inside it.</p><p>The central mistake in many dorm desk ideas is treating free surface as unfinished decor. A small lamp, tray, mirror, calendar, vase and stack of books can each look reasonable alone, yet together they remove the desk&rsquo;s actual function. Keep the centre empty. Place the lamp to the opposite side of the writing hand, move paper vertically into a file and collect charging cables at the rear edge.</p><h3>Use a movable caddy for the second job</h3><p>If the desk is also a vanity, put daily cosmetics in one handled caddy rather than spreading them across the shelf. The entire activity can then move to the bed or dresser while studying. The same method works for art materials, gaming accessories or snacks. A room stays calmer when each secondary job has one movable unit instead of ten permanent objects.</p><p>This is the desk version of the transfer systems in our guide to <a href="/blogs/home/how-to-keep-your-space-clean/">keeping a space clean</a>. Storage should reduce the number of handoffs between use and return. If a charger is used every night, its home needs to be one movement away. If a reference book opens twice a term, it can live higher.</p></section>
<section id="storage"><h2>Give each shelf one job</h2><p>A hutch looks disordered when every level mixes books, toiletries, electronics, snacks and decoration. Assigning a role to each zone creates a visual rhythm and makes returning objects nearly automatic.</p><div class="article-table-wrap" role="region" aria-label="Dorm desk hutch storage zones" tabindex="0"><table class="article-visual-table"><thead><tr><th>Zone</th><th>Best use</th><th>Keep out</th></tr></thead><tbody><tr><td>Worktop rear edge</td><td>Lamp, laptop stand, one cable route</td><td>Loose cosmetics and stacked decor</td></tr><tr><td>Lower shelf</td><td>Daily books, pen cup, current folder</td><td>Heavy objects above head height</td></tr><tr><td>Upper shelf</td><td>Light occasional supplies and one personal object</td><td>Open drinks, unstable stacks</td></tr><tr><td>Opaque box</td><td>Adapters, spare cables, small visual clutter</td><td>Items needed several times a day</td></tr><tr><td>Vertical file</td><td>Active papers and slim notebooks</td><td>Every document from the semester</td></tr></tbody></table></div><p>Keep weight low and centred. Large textbooks are safer on the bottom shelf or in a desk drawer than balanced at the top. Use bookends with a broad base, and do not wedge a shelf between two walls if that means forcing it out of square. A hutch that rocks on the desk is not ready to hold anything.</p><h3>Do not buy containers before assigning categories</h3><p>Begin with the objects, then choose the container. A tiny drawer may be ideal for memory cards and useless for a stapler. A row of matching baskets can look tidy while hiding three boxes of unrelated items. For the first week, use plain temporary boxes labelled by function. Once the categories prove stable, replace only the containers that make retrieval faster.</p><p>The shelf should also leave a small amount of negative space. In a compact room, one empty section does the visual work of a much larger edit. It allows the eye to understand where one group ends and another begins, the same principle that makes a <a href="/blogs/home/small-entryway-that-looks-expensive/">small entryway feel deliberate</a>.</p></section>
{picture(DORM_ROOT, "dorm-desk-lighting", "Dorm desk hutch at night with practical warm task lighting, controlled charging cables and an uncluttered worktop")}
<section id="lighting"><h2>Light the work, not the entire shelf</h2><p>Overhead dorm lighting is often broad, cool and unforgiving. A focused LED task lamp creates a better evening zone, but placement matters. Put the light above or beside the work, not directly behind the laptop where it can produce glare. A lamp with a metal shade and adjustable head is easier to direct than a decorative globe. Check that the bulb and fixture are permitted by the residence hall.</p><p>Do not make power management invisible at the expense of safety. University policies commonly require listed surge-protected power strips, prohibit daisy-chaining and insist that cords remain uncovered and accessible. The University of Cincinnati specifies that approved strips must plug directly into a wall outlet and remain visible rather than hidden under rugs, bedding or furniture. Your own housing policy may differ, so read it before buying a hutch with integrated outlets.</p><h3>A clean cable route has three points</h3><p>Choose one entry point from the wall, one controlled path along the rear edge and one charging tray. Use removable clips only if the desk finish and housing rules allow them. Leave slack where the laptop moves, but do not allow the cable to hang across the chair path. Label identical adapters discreetly near the plug rather than creating decorative tags on the worktop.</p><p>Fairy lights can make a room feel softer, but they do not replace task lighting and are restricted in some buildings. One warm pool of useful light usually looks more grown-up than a perimeter of tiny bulbs. It also photographs better because the desk retains shadows and depth instead of becoming uniformly bright.</p></section>
<section id="style"><h2>Make the dorm desk look considered, not expensive</h2><p>Repeat two materials already present in the room. If the university furniture is warm oak, add a dark metal lamp and one cream textile detail. If the desk is grey laminate, use black, parchment and a small amount of polished steel. Matching every accessory to a themed palette can feel temporary; repeating materials creates continuity.</p><p>Choose one personal object that can hold its own from across the room: a framed postcard, small ceramic piece, family photograph or found object. Keep the rest functional. A shelf full of miniature decor reads as retail because none of it has enough scale to anchor the composition. The lesson from our <a href="/blogs/home/how-to-make-a-home-look-expensive/">guide to making a home look expensive</a> applies even here: improve proportion before adding ornament.</p><p>Paper creates colour more naturally than plastic organisers. Use two or three visible books with jackets you genuinely like, a kraft folder or a linen-covered notebook. Hide brightly branded packaging inside a drawer or opaque box. Steam the bedding, wipe the desk and remove shipping stickers before deciding that the room needs another purchase. Maintenance provides more polish than novelty.</p><h3>Coordinate with a roommate by sightline</h3><p>A shared room does not require identical desks. Agree on the elements visible from the doorway, such as lamp temperature, the height of desktop shelves and whether large storage faces outward. Personal zones can remain different. The aim is not a matching set. It is preventing two tall hutches, two pinboards and two strings of lights from creating competing skylines in one narrow room.</p></section>
<section id="mistakes"><h2>Seven dorm desk hutch mistakes to avoid</h2><ol><li><strong>Buying from product width alone.</strong> Side supports consume worktop depth and can block drawers.</li><li><strong>Covering the outlet.</strong> Power connections need to remain visible and reachable.</li><li><strong>Using the upper shelf for heavy textbooks.</strong> Keep weight low and follow load limits.</li><li><strong>Mounting before reading the rules.</strong> Wall anchors, adhesive strips and extra furniture may be restricted.</li><li><strong>Filling every shelf on move-in day.</strong> Live in the room long enough to learn what needs to be close.</li><li><strong>Turning the worktop into a display.</strong> Empty space is the desk&rsquo;s most valuable feature.</li><li><strong>Ignoring the chair.</strong> Confirm that the seat can move, the knees clear the drawer and the exit path stays open.</li></ol><p>If the hutch makes the room darker, busier or harder to clean, it is not earning its footprint. Remove one shelf, reduce the containers or choose a simpler desktop riser. A smaller solution that gets used is more luxurious than a large one that performs organisation without delivering it.</p></section>
<section class="article-faq"><h2>Dorm desk hutch questions</h2><h3>How deep should a dorm desk hutch be?</h3><p>Choose the shallowest depth that holds your books securely while preserving the desk below. Always compare the product&rsquo;s support depth with the actual worktop, because shelf depth alone can be misleading.</p><h3>Can I add a hutch to university furniture?</h3><p>Only if your residence-hall policy permits it and the unit fits without damaging, modifying or obstructing supplied furniture. Check size, material, anchoring and fire-safety rules first.</p><h3>How do I stop a dorm desk from looking cluttered?</h3><p>Keep the central work rectangle empty, move loose small items into one opaque box and let each shelf hold one category. Remove packaging and duplicate organisers before buying more storage.</p></section>
<section class="source-note"><h2>Sources and safety note</h2><p>Search-interest context comes from Google&rsquo;s <a href="https://blog.google/products-and-platforms/products/shopping/back-to-school-trends/">back-to-school trends report</a> published 16 July 2026. Safety examples were checked against current residence-life guidance from <a href="https://manhattan.edu/offices/residence-life/prohibited">Manhattan University</a>, the <a href="https://www.uc.edu/campus-life/housing/resident-support/rules-regulations.html">University of Cincinnati</a> and <a href="https://reslife.umd.edu/moving-breaks/before-move">University of Maryland</a>. Rules vary by building. Follow your own housing contract, fire code and product instructions. Images are original fictional editorial photographs created for this article.</p></section>
<section><h2>The desk is finished when it is ready to be used</h2><p>A dorm hutch succeeds quietly. Books return without thought, the charger reaches the laptop, the lamp falls across the page and enough surface remains for actual work. That is the final edit. The shelf can carry personality, but the empty rectangle below it carries the semester.</p></section><div class="article-end"><span>End</span><p>Published by by.foro Editorial on 20 August 2026. For corrections, contact <a href="mailto:hello@byforo.com">hello@byforo.com</a>.</p></div></div></div>'''


NAILS_URL = "/blogs/beauty/dragonfly-nails/"
NAILS_ROOT = "/assets/images/blogs/beauty/dragonfly-nails"
NAILS_BODY = f'''<div class="article-layout"><aside class="article-aside"><p class="kicker">The manicure file</p><ol><li><a href="#answer">The short answer</a></li><li><a href="#quiet">Quiet designs</a></li><li><a href="#colour">Colour and light</a></li><li><a href="#dark">Darker versions</a></li><li><a href="#salon">The salon brief</a></li><li><a href="#care">Wear and removal</a></li></ol><button class="copy-link" data-copy-link type="button">Copy link</button></aside><div class="article-body">
<p class="article-opening">Dragonfly nails look most elegant when the insect is treated as line, structure or reflected light rather than a literal cartoon. Use a sheer base, keep the body fine, let the wings occupy only part of the nail and repeat one colour elsewhere in the manicure. Short natural nails can carry the idea as convincingly as extensions.</p>
<p>The attraction is easy to understand. A dragonfly has a recognisable silhouette, but its wings already contain the translucent veining, colour shift and precision that nail art handles well. Pinterest reported a 145 per cent rise in searches for &ldquo;dragonfly nails&rdquo; in its 2026 Wilderkind forecast. The useful response is not to place a large decal on every finger. It is to decide which quality you want: the outline, the shimmer, the movement or the strange delicacy of the real insect.</p>
<div class="summary-box" id="answer"><p class="kicker">Before the appointment</p><h2>Choose one dragonfly language</h2><p>For a minimal result, request one fine-line insect over a milky or bare base. For iridescence, ask for translucent blue-green interference pigment under fine black veining. For a darker manicure, use smoky grey, oxblood or deep green and keep the wing detail metallic rather than glittery. Bring a reference that shows nail length, base colour and scale, not only the drawing.</p></div>
<section id="quiet"><h2>Six quiet dragonfly nail ideas</h2><h3>1. One black line on milky pink</h3><p>Place a tiny dragonfly on one ring finger and leave the other nails translucent. The insect should be narrow enough that a border of bare colour remains around it. This is the most versatile version because the manicure reads as natural from a distance and only reveals the motif up close.</p><h3>2. Silver over a bare nail</h3><p>Swap black for a cool silver liner. Keep the body matte and add shine only to the wings. Against a clean natural nail, the difference in finish provides dimension without introducing several colours.</p><h3>3. The half-wing crop</h3><p>Instead of drawing a complete insect, let one veined wing enter from the side of the nail and disappear beyond the edge. Repeat the crop on two non-adjacent fingers. The incomplete image feels editorial because the nail becomes a frame rather than a sticker sheet.</p><h3>4. A pin-point gold body</h3><p>Draw the wings in taupe or soft grey and mark the head with one microscopic gold dot. A small metallic point catches light more effectively than a row of crystals. Pair it with short oval nails so the design remains close to the hand.</p><h3>5. French tips with hidden wings</h3><p>Use an extremely thin ivory French line, then add a ghosted wing just beneath the tip on two nails. From a distance the manicure is conventional. In direct light, the wing appears as a private detail. This works best when the base closely matches the wearer&rsquo;s natural nail tone.</p><h3>6. A single blue dragonfly</h3><p>Choose desaturated ink blue rather than bright turquoise. Paint one insect on the thumb, where there is room for four believable wings, and leave the rest sheer. The thumb placement prevents the design from dominating every hand gesture.</p></section>
{picture(NAILS_ROOT, "dragonfly-nails-minimal", "Short natural oval nails with a milky base, one fine-line dragonfly and a single restrained gold detail")}
<section id="colour"><h2>Six designs built from colour and reflected light</h2><h3>7. Iridescent wing veining</h3><p>Apply a thin blue-green interference layer over smoky grey, then draw the wing cells with a fine liner. The pigment should shift only when the hand moves. If it looks rainbow-bright in every position, the effect has moved from dragonfly wing to holographic foil.</p><h3>8. Watercolour pond tones</h3><p>Blend washed blue, reed green and a trace of violet across two nails before adding a barely visible silver body. Keep the colour edges soft and the surrounding nails clear. This is atmospheric rather than literal, which makes it easier to wear.</p><h3>9. Chrome caught at the edge</h3><p>Rub pearl chrome into only one side of a translucent wing, leaving the rest nearly bare. The uneven reflection resembles light crossing a real membrane. A full chrome nail beside it gives the eye too much information, so use plain taupe or pink on the remaining fingers.</p><h3>10. Pale blue micro-French</h3><p>Paint a cool blue micro-tip on every nail and place one matching dragonfly over the nude base. Repeating the colour connects the motif to the set. The tip should be narrow enough that the manicure still lengthens the nail rather than cutting it into two blocks.</p><h3>11. Opal dots, not rhinestones</h3><p>Use three or four tiny translucent dots to suggest reflected water around one dragonfly. Vary their size and keep them flat. Raised stones can snag and quickly turn a delicate idea into a heavily embellished one.</p><h3>12. Sheer lavender with pewter lines</h3><p>A transparent lavender base softens cool metallic linework and flatters the silvery quality of the motif. Use pewter instead of bright chrome and paint only the outer wings. The result works particularly well on a medium squoval shape.</p></section>
{picture(NAILS_ROOT, "dragonfly-nails-iridescent", "Smoky grey manicure with sophisticated blue-green iridescent dragonfly-wing veining on four accent nails")}
<section id="dark"><h2>Five darker dragonfly manicures</h2><h3>13. Oxblood and old gold</h3><p>Use a deep translucent red, then draw one aged-gold dragonfly over the ring finger. The warm metal removes the chilly fantasy quality and connects the manicure to jewellery. Keep the gold brushed rather than mirror-bright.</p><h3>14. Blackened green wings</h3><p>Paint the nails a nearly black forest green and reveal wing cells with a slightly lighter magnetic or cat-eye polish. The design appears through movement instead of outline. Ask for one or two accents only, because magnetic pigment on every nail can overpower the structure.</p><h3>15. Charcoal negative space</h3><p>Leave a dragonfly-shaped sliver of bare nail inside a charcoal field. Negative-space work requires precision, but it avoids adding another colour and remains graphic on short nails. A matte top coat can make the empty shape clearer.</p><h3>16. Moonlit moth-grey</h3><p>Combine soft graphite, pearl and one fine silver dragonfly. The palette sits near the <a href="/blogs/beauty/vamp-romantic-beauty-guide/">vamp romantic beauty</a> world without becoming gothic costume. Keep the cuticle area sheer so the darkness feels suspended rather than heavy.</p><h3>17. Midnight blue with clear wings</h3><p>Paint four nails in deep blue and leave one accent nail transparent. Draw only the insect&rsquo;s body on the clear base, then describe the wings with gloss over matte. The image appears when light changes, which is more intriguing than a bright outline.</p><p>These ideas can also form a small visual cluster with our guide to the <a href="/blogs/fashion/bug-jewellery-trend/">bug jewellery trend</a>. The point is not to match a brooch and manicure exactly. Repeat a metal tone or one species, then let the scale change.</p></section>
<section id="salon"><h2>How to brief the nail artist clearly</h2><p>Save one reference for the shape, one for the base and one for the insect scale. Showing ten unrelated designs usually produces a compromise with too many elements. State the non-negotiable first: short oval nails, sheer pink base, one fine-line dragonfly, no crystals. Then identify where the artist has freedom, such as the exact wing angle.</p><p>A fine-line design requires enough contrast to remain visible but not so much product that the wings become raised ridges. If you want a chrome or magnetic effect, ask how it will look in ordinary indoor light. Salon ring lights exaggerate shimmer. A good photograph taken near a window gives a more honest preview.</p><h3>Match the design to nail length</h3><p>Short nails suit complete micro-dragonflies, partial wings and single-line bodies. Medium nails can handle veining or a diagonal insect. Long nails allow more detail, but the design should not automatically grow to fill the available area. Leaving space around it is what keeps the motif modern.</p><p>Choose the base for your skin and nail plate rather than copying the exact bottle in a reference. Milky pink can appear chalky on some tones; a sheer beige, peach or mauve may look more natural. The dragonfly is already the statement. The base should make the hand look intentional before art is added.</p><div class="article-table-wrap" role="region" aria-label="Dragonfly nail design guide by nail shape" tabindex="0"><table class="article-visual-table"><thead><tr><th>Nail shape</th><th>Best dragonfly treatment</th><th>What to avoid</th></tr></thead><tbody><tr><td>Short oval</td><td>One micro outline or cropped wing</td><td>Dense crystals and thick borders</td></tr><tr><td>Short square</td><td>Negative space or side-entering wing</td><td>Long vertical bodies that crowd the tip</td></tr><tr><td>Medium almond</td><td>Diagonal complete insect or watercolour wash</td><td>Identical art on every nail</td></tr><tr><td>Medium squoval</td><td>Wing veining and smoky iridescence</td><td>Overly sharp graphic lines</td></tr><tr><td>Long almond</td><td>Fine articulated wings with generous bare space</td><td>Scaling the insect to fill the entire nail</td></tr></tbody></table></div></section>
<section id="care"><h2>Wear the manicure without sacrificing the nail</h2><p>Traditional polish can carry most fine-line and decal designs. Gel offers durability and can suspend chrome or magnetic pigment cleanly, but it is not required simply because the art is detailed. Choose the system based on your nails, removal habits and professional advice rather than the photograph.</p><p>The American Academy of Dermatology notes that repeated gel manicures can contribute to brittleness, peeling and cracking. Its dermatologists advise sunscreen or opaque fingertip-less gloves before ultraviolet curing, avoiding cuticle cutting and never picking off gel. If your nails are persistently painful, discoloured or separating, pause cosmetic services and seek qualified medical advice.</p><h3>Protect the smallest details</h3><p>Ask the artist to seal free edges and keep raised additions minimal. Wear gloves for cleaning, use cuticle oil around rather than beneath lifted product and return for professional removal when appropriate. A manicure designed around one precise image looks better when the surrounding nails stay healthy and simple.</p><p>Photograph the finished set in diffuse daylight with the hands relaxed. Dragonfly wings depend on movement, so capture one direct angle and one tilted angle rather than forcing the shimmer into a heavily edited image. The realism is part of the design.</p></section>
<section class="article-faq"><h2>Dragonfly nail questions</h2><h3>Can dragonfly nail art work on short nails?</h3><p>Yes. Use a micro outline, partial wing or single accent nail and preserve bare space around the design.</p><h3>What colours suit dragonfly nails?</h3><p>Sheer pink, smoky grey, desaturated blue, deep green and oxblood all work. Choose one reflective accent such as silver, old gold or blue-green interference pigment.</p><h3>Are dragonfly nails only a summer design?</h3><p>No. Pale blue and clear versions feel light, while pewter, oxblood and blackened green make the motif suitable for autumn and evening wear.</p></section>
<section class="source-note"><h2>Sources and image note</h2><p>Trend data comes from Pinterest&rsquo;s <a href="https://business.pinterest.com/en-gb/pinterest-predicts/2026/wilderkind/">2026 Wilderkind forecast</a>, based on global English-language search data. Nail-health guidance was checked against the American Academy of Dermatology&rsquo;s <a href="https://www.aad.org/public/everyday-care/nail-care-secrets/basics/pedicures/gel-manicures">gel manicure recommendations</a>. Styling and salon briefing are by.foro editorial guidance, not medical advice. Images are original fictional editorial photographs created for this article.</p></section>
<section><h2>The most convincing wing is the one that almost disappears</h2><p>A dragonfly manicure does not need to announce its reference from across the room. Let the outline remain fine, the pigment shift only when the hand turns and the surrounding nails stay quiet. The design then behaves like the insect itself: precise, quick and visible for a moment before the light changes.</p></section><div class="article-end"><span>End</span><p>Published by by.foro Editorial on 20 August 2026. For corrections, contact <a href="mailto:hello@byforo.com">hello@byforo.com</a>.</p></div></div></div>'''


KHAKI_URL = "/blogs/fashion/khaki-coded-style/"
KHAKI_ROOT = "/assets/images/blogs/fashion/khaki-coded-style"
KHAKI_BODY = f'''<div class="article-layout"><aside class="article-aside"><p class="kicker">The wardrobe file</p><ol><li><a href="#answer">The short answer</a></li><li><a href="#why">Why utility returns</a></li><li><a href="#palette">Build the palette</a></li><li><a href="#proportion">Fix the proportions</a></li><li><a href="#formulas">Six outfit formulas</a></li><li><a href="#buy">What deserves a place</a></li></ol><button class="copy-link" data-copy-link type="button">Copy link</button></aside><div class="article-body">
<p class="article-opening">Khaki coded style combines field jackets, utility shirts, pleated trousers, Bermuda shorts and earth tones, then removes the costume signals. The modern version works through contrast: washed cotton with silk, pockets with clean tailoring, olive beside ivory and practical leather beside a refined shoe. Wear one piece that implies work and one that clearly does not.</p>
<p>Pinterest named Khaki Coded among its 2026 predictions after searches rose for brown linen shirts, utility shirts, field-jacket outfits and a newly named &ldquo;paleontologist aesthetic.&rdquo; The label is playful, but the clothes have a longer life than the trend name. Field jackets, safari shirts and khaki trousers return because their pockets, cloth and adjustable shapes solve ordinary problems. Fashion keeps translating that usefulness into a different social language.</p>
<div class="summary-box" id="answer"><p class="kicker">The easiest rule</p><h2>One utility piece, one polished counterweight</h2><p>Pair a field jacket with a silk skirt, cargo trousers with a narrow knit, a utility shirt with full tailoring or khaki Bermuda shorts with a precise leather shoe. Keep the palette to sand, olive, tobacco, ivory and one dark anchor. Avoid literal expedition accessories, matching sets with too many pockets and styling that borrows authority from uniforms without considering their history.</p></div>
<section id="why"><h2>Why utility clothing keeps returning to fashion</h2><p>The Museum at the Fashion Institute of Technology&rsquo;s 2026 exhibition <em>Beyond Utility</em> traced the way garments created for work, military use and protection become fashion objects. Its central point is useful here: practical clothing prioritises movement, durability and bodily protection, yet those features are continually reinterpreted to express identity, status or resistance.</p><p>A pocket begins as storage and ends as visual architecture. Reinforced stitching begins as durability and becomes a graphic line. Khaki begins as camouflage and, in a city wardrobe, becomes a sophisticated neutral. The transformation is not politically empty. Military and colonial references carry histories that should not be flattened into mood-board adventure. The strongest modern styling keeps the functional grammar while discarding insignia, rank and caricature.</p><p>That is why the trend feels sharper in 2026 than a generic safari revival. The clothes do not need props. A good field jacket looks complete on a train platform because its washed cloth, drawcord and pockets already communicate use. A brown linen shirt works because heat changes the fabric and the creases improve it. The wearer does not have to pretend to be elsewhere.</p><h3>Khaki is a family, not one colour</h3><p>Retail often uses khaki to describe anything from pale stone to green-brown. Treat it as a range rather than searching for an exact match. Yellow khaki sits well with chocolate, cream and oxblood. Grey olive prefers black, cool white and silver. Sandy beige becomes richer beside tobacco, denim and dark green. The undertone matters more than the label.</p></section>
{picture(KHAKI_ROOT, "khaki-coded-palette", "Khaki field jacket, sand linen shirt, olive pleated trousers and dark brown accessories arranged on an old oak table")}
<section id="palette"><h2>Build a khaki palette with temperature and depth</h2><p>A head-to-toe earth palette can look luxurious or strangely flat. The difference is temperature. If the jacket, trousers, shirt and shoe are all the same medium yellow-brown, the eye cannot find a beginning. Introduce one pale lift, one deep anchor and one material that reflects light differently.</p><div class="article-table-wrap" role="region" aria-label="Khaki coded colour combinations" tabindex="0"><table class="article-visual-table"><thead><tr><th>Khaki tone</th><th>Best companions</th><th>Finish that adds depth</th></tr></thead><tbody><tr><td>Pale stone</td><td>Ink navy, olive, tobacco</td><td>Dark polished leather</td></tr><tr><td>Warm sand</td><td>Ivory, chocolate, faded red</td><td>Brushed gold or horn</td></tr><tr><td>Grey olive</td><td>Black, oyster, steel blue</td><td>Silver or pewter</td></tr><tr><td>Deep army green</td><td>Cream, pale denim, burgundy</td><td>Glossy silk or patent accent</td></tr><tr><td>Brown khaki</td><td>Chalk white, saffron, dark plum</td><td>Woven raffia or suede</td></tr></tbody></table></div><p>Do not insist that every green agree. A faded olive jacket over darker trousers often looks more convincing than a near-match. The contrast shows that the pieces were collected rather than purchased as a costume. Repeat the difference once, perhaps in a bag or belt, so it feels intentional.</p><h3>Texture performs the colour work</h3><p>Washed cotton absorbs light. Silk sends it back. Dry wool creates soft shadow; smooth leather creates a clean line. When the palette is narrow, these differences replace pattern. This principle also appears in the <a href="/blogs/fashion/european-summer-style-2026/">European summer wardrobe</a>, where linen, raffia and tailoring prevent neutral outfits from becoming blank.</p></section>
<section id="proportion"><h2>The trend succeeds or fails on proportion</h2><p>Utility garments are designed with room for movement and layers. Fashion versions can be cropped, narrowed or exaggerated, but an outfit needs to decide where volume lives. If the jacket is broad and the trousers are cargo-cut, keep the inner layer close and the shoe visually lean. If the trousers are full and pleated, shorten the jacket or show the waist. If the shirt is long and loose, pair it with a straight skirt or fitted short.</p><p>The field jacket is easiest when it ends around the high hip or can be drawn inward at the waist. A hem that stops at the widest part of the thigh can feel heavy beside large pockets. Roll the sleeves to reveal a wrist and a different lining colour, not as a casual gesture applied to every look but as a way to interrupt the block of fabric.</p><h3>Pockets add volume even when empty</h3><p>Patch and bellows pockets create shadow and visual weight. Four large pockets across a short jacket may be enough detail for the whole outfit. Avoid pairing them automatically with a cargo bag, hiking boot and wide belt. Let one practical element keep its authority while the rest of the clothes become quieter.</p>{picture(KHAKI_ROOT, "khaki-coded-tailoring", "Headless dress form in a softly belted olive field jacket, sand silk shirt and dark chocolate pleated trousers")}
<p>A useful fitting test is to photograph the outfit from the side. Front-facing mirrors hide how far pockets project and where a stiff belt changes the line. The side view will show whether the jacket is shaping the body or merely sitting around it.</p></section>
<section id="formulas"><h2>Six khaki coded outfit formulas that do not look like costume</h2><h3>1. Field jacket, silk skirt, dark loafer</h3><p>This is the clearest formality contrast. The jacket supplies structure and wear; the skirt moves and catches light. Use ivory, cream or muted bronze rather than a bright print. A dark loafer grounds both pieces and keeps the outfit useful for a city day.</p><h3>2. Pleated khaki trouser, ribbed knit, sculptural cuff</h3><p>Choose trousers with a true crease and enough drape to separate them from chinos. A narrow knit controls the waist, while one broad metal cuff introduces a deliberate object. If you already wear brooches, the placement ideas in our <a href="/blogs/fashion/how-to-wear-brooches/">modern brooch guide</a> work especially well on a pocket flap or collar.</p><h3>3. Brown linen shirt, black maxi skirt, bare sandal</h3><p>The dark vertical skirt removes the expedition association and gives brown linen a cleaner frame. Leave the shirt relaxed at the shoulder and tuck only enough fabric to show the waistband. The sandal should be spare, not trail-ready.</p><h3>4. Utility shirt, tailored Bermuda shorts, small heel</h3><p>Keep the shorts pressed and slightly longer than the widest part of the thigh. Button the shirt low over a simple vest or wear it closed with sleeves turned back. A refined kitten heel or pointed flat creates useful tension with the pockets.</p><h3>5. Olive cargo skirt, white poplin, polished belt</h3><p>A straight cargo skirt carries the utility language without the volume of trousers. Pair it with crisp white poplin and a belt that has one clean buckle. Avoid piling on straps. The skirt already has more seams than an ordinary base.</p><h3>6. Khaki suit, soft T-shirt, unexpected colour</h3><p>Choose a suit with restrained pockets and relaxed tailoring, then add one controlled colour: iris purple, faded coral or icy blue. This follows the method in <a href="/blogs/fashion/how-to-wear-colour-again/">how to wear colour again</a>. The accent should be small enough that the khaki remains the structure, not a backdrop for several trends.</p></section>
<section id="buy"><h2>What deserves a place in the wardrobe</h2><p>Start with a field jacket that can close comfortably over a knit, has pockets placed at a useful height and looks better slightly creased. Check the stitching around pocket corners, the movement of zips and snaps, and whether the waist adjustment lies flat. Decorative drawcords that do not change the silhouette add visual noise without function.</p><p>For trousers, choose the cloth before the pocket count. Cotton-linen works in heat but may lose a crease quickly; dry wool can make cargo construction feel unexpectedly formal; cotton twill lasts but can become stiff if cut too narrow. Sit, walk and use the pockets before removing tags. A pocket that pulls the whole side seam when holding a phone is not practical design.</p><h3>Shop the second-hand rail with a tailor&rsquo;s eye</h3><p>Utility pieces often improve with wear, making vintage and resale strong sources. Inspect cuffs, collar edges, pocket bags and underarms. Fading can be beautiful when it follows use; brittle fabric, failed coatings and corroded hardware are harder to repair. A tailor can shorten sleeves or refine a waist, but moving large pockets may leave permanent marks.</p><p>Pay equal attention to hardware. A matte horn button, dark metal press stud or substantial two-way zip can make inexpensive cotton look composed, while shiny lightweight hardware often gives the game away. If a jacket is otherwise excellent, replacing its buttons is an easy alteration. Replacing a full exposed zip is not. Also check the garment from behind. Oversized patch pockets and shoulder tabs can make the back unexpectedly busy, especially when a bag strap crosses them.</p><p>Do not buy a complete trend uniform in one week. Add the jacket, wear it with the wardrobe you already have and observe what it asks for. Perhaps the missing piece is not another khaki item but a cream skirt, dark shoe or better belt. The same restraint keeps our <a href="/blogs/fashion/fall-2026-fashion-trends-worth-wearing/">Fall 2026 trend guide</a> useful after the season ends.</p></section>
<section class="article-faq"><h2>Khaki coded style questions</h2><h3>What does khaki coded mean?</h3><p>It describes 2026&rsquo;s interest in earth-toned utility clothing such as field jackets, cargo shapes, linen shirts and practical pockets, styled as contemporary fashion rather than literal expedition wear.</p><h3>What colours go with khaki?</h3><p>Ivory, chocolate, black, ink navy, burgundy and muted blue all work. Match the companion colour to the khaki&rsquo;s warm, cool or green undertone.</p><h3>How do you make utility clothes look elegant?</h3><p>Use one practical garment with a polished counterweight, control where volume sits and introduce a contrasting texture such as silk, dry wool or refined leather.</p></section>
<section class="source-note"><h2>Sources and editorial note</h2><p>Search-growth context comes from Pinterest&rsquo;s <a href="https://business.pinterest.com/en-gb/pinterest-predicts/2026/khaki-coded/">Khaki Coded forecast</a>. Historical and design context was checked against the Museum at FIT&rsquo;s 2026 exhibition <a href="https://www.fitnyc.edu/museum/exhibitions/beyond-utility/index.php"><em>Beyond Utility</em></a> and its <a href="https://exhibitions.fitnyc.edu/uniformity/">Uniformity</a> exhibition. Styling, colour combinations and buying advice are by.foro editorial judgement. Images are original fictional editorial photographs created for this article.</p></section>
<section><h2>The clothes should look capable, not theatrical</h2><p>Khaki coded style is convincing when the wearer appears ready for an ordinary day. The jacket closes, the pocket holds something, the trouser moves and the silk skirt makes the cotton look intentional. Remove the props and keep the contrast. Utility has enough character without pretending to be an expedition.</p></section><div class="article-end"><span>End</span><p>Published by by.foro Editorial on 20 August 2026. For corrections, contact <a href="mailto:hello@byforo.com">hello@byforo.com</a>.</p></div></div></div>'''


BUG_URL = "/blogs/fashion/bug-jewellery-trend/"
BUG_ROOT = "/assets/images/blogs/fashion/bug-jewellery-trend"
BUG_BODY = f'''<div class="article-layout"><aside class="article-aside"><p class="kicker">The jewellery file</p><ol><li><a href="#answer">The short answer</a></li><li><a href="#return">Why insects returned</a></li><li><a href="#history">The longer history</a></li><li><a href="#motifs">Choose the motif</a></li><li><a href="#style">How to wear it</a></li><li><a href="#buy">How to buy well</a></li></ol><button class="copy-link" data-copy-link type="button">Copy link</button></aside><div class="article-body">
<p class="article-opening">The bug jewellery trend is the most refined branch of 2026&rsquo;s Wilderkind aesthetic. Beetles, moths, bees and dragonflies are appearing as brooches, pendants, rings and earrings because their structures translate naturally into metal and enamel. Wear one anatomically legible insect against an ordinary fabric and let the oddness remain small.</p>
<p>Nature-inspired jewellery is hardly new, which is exactly why the current return has depth. A dragonfly can carry Art Nouveau delicacy; a scarab brings ancient revival references; a bee may feel orderly or communal; a moth introduces darkness without the blunt symbolism of a skull. The motif matters, but so do scale, material and placement. A tiny silver beetle on a white shirt says something different from a crystal swarm across a lapel.</p>
<div class="summary-box" id="answer"><p class="kicker">The modern rule</p><h2>One creature, one clear habitat</h2><p>Choose a motif you would still like without the trend name. Place it where the garment offers enough plain ground: a blazer lapel, shirt collar, knit shoulder, fine chain or signet-sized ring. Mix an elaborate insect with an ordinary textile such as denim, cotton or dry wool. Avoid realistic pieces made from actual insect bodies unless you have verified ethical and legal sourcing.</p></div>
<section id="return"><h2>Why bug jewellery returned now</h2><p>Pinterest&rsquo;s 2026 Wilderkind report recorded a 60 per cent rise in searches for &ldquo;bug jewellery&rdquo;, alongside growth for dragonfly nails, animal-inspired outfits and deer imagery. The platform frames the trend as animal aesthetics with a delicate touch. That final phrase explains why insects fit more easily than a large leopard print or literal animal costume. A bug can occupy the space of a coin.</p><p>The return also follows years of extremely restrained accessories. A fine gold hoop can be beautiful, but it carries little narrative on its own. Insect jewellery restores the pleasure of recognition. The wearer can choose a species, material and degree of realism. Even at small scale, it creates a question: antique, heirloom, scientific specimen or joke?</p><p>That narrative quality suits the wider move toward personal style. Our article on why <a href="/blogs/fashion/celebrity-style-is-getting-personal/">celebrity style is getting personal again</a> describes the same appetite for details that cannot be reduced to a shopping link. A vintage bee found at a market has a story before it enters an outfit. A mass-produced logo arrives already explained.</p><h3>Wilderkind is most convincing when it stays specific</h3><p>Buying a generic &ldquo;forest aesthetic&rdquo; collection risks turning nature into another coordinated retail category. Specificity resists that. Learn whether the form resembles a beetle, moth or dragonfly. Notice whether the wings are enamelled, engraved or simply suggested. The closer the object comes to observation, the less it needs fantasy styling around it.</p></section>
{picture(BUG_ROOT, "bug-jewellery-motifs", "Patinated gold beetle pendant and oxidised silver moth earrings with moonstone details on handmade paper and black silk")}
<section id="history"><h2>The jewel box already has an insect history</h2><p>In the late nineteenth century, jewellers found ideal subjects in wings, segmented bodies and shells. The Metropolitan Museum of Art&rsquo;s dragonfly brooch by Edgar Bense for Boucheron, made around 1890, uses gold, diamonds and translucent plique-&agrave;-jour enamel. The open-backed enamel creates a stained-glass effect, while the wings are set to tremble and catch light.</p><p>The object feels contemporary because it is not timid. Its body is long, the wings are technically complex and the insect remains visibly strange. Art Nouveau did not make nature tasteful by smoothing away every difficult part. It allowed jewellery to become asymmetrical, sinuous and alive.</p><p>Victorian and early twentieth-century pieces also used bees, spiders, butterflies, beetles and lizards. Christie's records describe creatures worn in multiples to secure veils or scattered across a bodice. That historical placement helps explain why today&rsquo;s brooch revival and insect trend fit together so naturally. The body was already a field for small moving forms.</p><h3>Actual beetle wings require a separate ethical question</h3><p>Some historic textiles and objects were decorated with iridescent beetle wing cases. Cooper Hewitt notes their use in Mughal-period India and later Victorian popularity. Contemporary jewellery made with biological material may raise questions about species, trade, harvesting and import rules. Do not assume that &ldquo;natural&rdquo; means harmless. If provenance is unclear, choose enamel, glass or lab-made colour effects instead.</p><p>A motif can honour the visual structure of an insect without containing one. Metalwork is often more durable, easier to repair and capable of developing its own history through wear.</p></section>
<section id="motifs"><h2>Choose the insect by shape, not a generic meaning list</h2><p>Online symbolism lists often assign universal messages to animals without identifying a culture, date or source. Treat those claims cautiously. A motif can have several histories, and the wearer can choose it simply because its form is beautiful. Start with what the insect does visually.</p><div class="article-table-wrap" role="region" aria-label="Bug jewellery motif and styling guide" tabindex="0"><table class="article-visual-table"><thead><tr><th>Motif</th><th>Visual character</th><th>Best jewellery form</th><th>Strong placement</th></tr></thead><tbody><tr><td>Dragonfly</td><td>Long, airy, symmetrical</td><td>Brooch or hair pin</td><td>High lapel or side of a low bun</td></tr><tr><td>Beetle</td><td>Compact, armoured, graphic</td><td>Ring or pendant</td><td>Index finger or short chain</td></tr><tr><td>Moth</td><td>Soft, nocturnal, broad-winged</td><td>Earrings or pendant</td><td>Against black silk or bare skin</td></tr><tr><td>Bee</td><td>Small, recognisable, orderly</td><td>Stud, collar pin or pair</td><td>Shirt collar points</td></tr><tr><td>Spider</td><td>Radial, sharp, deliberately uneasy</td><td>Brooch or fine ring</td><td>Plain knit shoulder or cuff</td></tr><tr><td>Scarab</td><td>Oval, polished, architectural</td><td>Signet ring or carved pendant</td><td>Single hand or central neckline</td></tr></tbody></table></div><p><strong>Dragonflies</strong> need width. Compressing four wings into a tiny stud often loses the quality that makes them interesting. Let them stretch across a lapel or hair pin. The modern manicure version is covered in our guide to <a href="/blogs/beauty/dragonfly-nails/">elegant dragonfly nails</a>.</p><p><strong>Beetles and scarabs</strong> tolerate volume. Their domed shells suit rings, pendants and small boxes. Look for an underside and legs that are finished cleanly, because a three-dimensional piece will turn while worn.</p><p><strong>Moths</strong> are softer and more atmospheric. Oxidised silver, moonstone and dark enamel suit their powdery wings. Keep the surrounding outfit simple so the motif does not slide into themed gothic styling.</p><p><strong>Bees</strong> work well in pairs, particularly on collar points or small earrings. Their familiar outline can handle a little gold, but bright yellow enamel quickly becomes illustrative. Choose texture over literal colour.</p></section>
{picture(BUG_ROOT, "bug-jewellery-styling", "Antique-inspired dragonfly brooch pinned high on a charcoal dry-wool blazer over an ivory cotton shirt")}
<section id="style"><h2>How to wear insect jewellery without looking costumed</h2><h3>Put the formal jewel on an ordinary fabric</h3><p>Crystal wings become modern on denim. Seed pearls feel sharper on dry grey wool. A detailed beetle pendant looks better against a plain cotton vest than beside a printed botanical dress. The contrast breaks the expectation that nature jewellery needs romantic clothing.</p><h3>Use the garment seam as a landscape</h3><p>Pin a dragonfly parallel to a blazer notch, place a beetle just above a pocket or let a spider sit where a knit shoulder changes direction. The seam gives the creature orientation. A brooch floating in the middle of a large lapel can appear accidental, while a motif responding to construction looks composed.</p><h3>Cluster by logic, not quantity</h3><p>If one insect is not enough, repeat a relationship. Three tiny bees travelling up a collar make sense. A beetle, bow, pearl flower and logo pin collected at random do not. Our full guide to <a href="/blogs/fashion/how-to-wear-brooches/">wearing brooches in 2026</a> explains weight distribution, fabric support and less obvious placements.</p><h3>Let earrings move and necklaces stay still</h3><p>Moth or dragonfly earrings can use articulated wings, but pair them with a short, quiet neckline. A pendant with several projecting legs needs a chain length that prevents constant catching. Test how a piece behaves while sitting, wearing a coat and carrying a bag. Jewellery is successful only when the body can forget it for a while.</p><h3>Repeat one metal elsewhere</h3><p>Aged gold insect jewellery can feel isolated in a cool wardrobe. Repeat the metal once in a belt buckle, shoe hardware or slim ring. Do not match every object. One echo is enough to make the piece belong.</p><p>For evening, insect jewellery can sit inside an <a href="/blogs/culture/art-deco-revival/">Art Deco revival</a> look through geometric black clothing, gloves or a structured bag. The insect should remain the organic interruption, not one more ornate element competing with fringe, velvet and embellishment.</p></section>
<section id="buy"><h2>How to buy bug jewellery that lasts beyond the trend</h2><p>Turn the piece over. The back reveals whether the maker resolved the object or only designed the photograph. Check hinge movement, solder points, pin length, clasp security and whether sharp legs catch knitwear. For earrings, compare weight and confirm that posts or wires are straight. A wide brooch may need two pin points to prevent rotation.</p><p>Ask what the materials actually are. &ldquo;Gold tone&rdquo; does not identify a base metal or plating thickness. Enamel can mean fired glass, resin or coloured lacquer. None is automatically wrong, but the price and care should reflect the construction. Gemstone names should be specific, and antique claims should be supported by marks, provenance or a knowledgeable seller rather than an aged finish.</p><h3>Vintage, artisan and mass-market pieces serve different purposes</h3><p>Vintage jewellery offers patina and construction that may be difficult to reproduce, but it can require repair. Independent makers may provide better material transparency and allow scale changes. Mass-market pieces make experimentation affordable, though clasps, plating and repeated friction deserve close inspection.</p><p>Buy the motif you would keep after its social label disappears. If a dragonfly reminds you of a place, a bee connects to family or a beetle simply feels beautifully engineered, the object already has a life beyond 2026. That is more persuasive than owning one example of every predicted trend.</p><h3>Store projecting forms separately</h3><p>Wings and legs can scratch softer pieces or bend under weight. Close brooch pins, fasten chains and store each three-dimensional object in a small fabric pouch or divided box. Keep perfume, hairspray and household cleaners away from enamel, pearls and plated surfaces. For valuable or antique pieces, follow a qualified jeweller&rsquo;s advice rather than experimenting with home cleaning solutions.</p></section>
<section class="article-faq"><h2>Bug jewellery questions</h2><h3>Is insect jewellery in style in 2026?</h3><p>Yes. Pinterest identified rising searches for bug jewellery within its Wilderkind trend, while the wider brooch revival has made insect motifs easier to wear on collars, lapels and accessories.</p><h3>What insect jewellery is easiest to wear?</h3><p>A small beetle pendant, bee stud or medium dragonfly brooch offers a clear motif without requiring a themed outfit.</p><h3>How can I tell if an insect brooch is well made?</h3><p>Inspect the back, hinge, clasp, soldering and sharp edges. The pin should support the piece without rotating or pulling heavily on the fabric.</p></section>
<section class="source-note"><h2>Sources and image note</h2><p>Trend context comes from Pinterest&rsquo;s <a href="https://business.pinterest.com/en-gb/pinterest-predicts/2026/wilderkind/">Wilderkind forecast</a>. Historical details were checked against the Metropolitan Museum of Art&rsquo;s record for Edgar Bense&rsquo;s <a href="https://www.metmuseum.org/art/collection/search/770198">circa-1890 dragonfly brooch</a>, Cooper Hewitt&rsquo;s <a href="https://www.cooperhewitt.org/2018/09/14/natures-sequins/">research on beetle-wing decoration</a> and Christie&rsquo;s archive of late nineteenth-century animal jewellery. Symbolic interpretations are intentionally presented as contextual rather than universal facts. Images show fictional metal and enamel jewellery created for this article. No real insects or animal parts were used.</p></section>
<section><h2>The smallest creature can carry the whole outfit</h2><p>Bug jewellery works because it turns observation into ornament. The wing, shell or segmented body is already a design. Choose one form, give it enough plain fabric to be seen and resist explaining every meaning. A good insect jewel should remain slightly strange. That is what keeps it alive after the trend moves on.</p></section><div class="article-end"><span>End</span><p>Published by by.foro Editorial on 20 August 2026. For corrections, contact <a href="mailto:hello@byforo.com">hello@byforo.com</a>.</p></div></div></div>'''


ARTICLES = [
    dict(url=DORM_URL, seo="Dorm Desk Hutch Ideas for a Chic, Clutter-Free Room", title="The Dorm Desk That Actually Works", description="Plan a dorm desk hutch that saves space without stealing your work surface, with measurements, lighting, cable control and styling that stays practical.", deck="Use height, protect the writing surface and make every shelf earn its space. The best dorm desk is ready before the laptop opens.", department="Home", topic="Dorm Rooms", hero=f"{DORM_ROOT}/dorm-desk-hutch-hero", alt="Sophisticated oak dorm desk hutch with books, lamp, laptop and a clear work surface beside a Twin XL bed", body=DORM_BODY, words=2100, keywords=["dorm desk hutch ideas", "dorm desk setup", "dorm desk organization", "small dorm desk ideas"]),
    dict(url=NAILS_URL, seo="Dragonfly Nails: 17 Elegant Designs to Try in 2026", title="Dragonfly Nails, Drawn With a Lighter Hand", description="Discover 17 elegant dragonfly nail ideas, from fine-line and chrome-wing details to short natural manicures, plus practical salon notes for lasting results.", deck="Keep the body fine, the wings translucent and the surrounding nails quiet. Seventeen versions prove the motif does not need to feel literal.", department="Beauty", topic="Nails", hero=f"{NAILS_ROOT}/dragonfly-nails-hero", alt="Natural almond nails with three tiny silver and translucent blue dragonflies resting on ivory linen", body=NAILS_BODY, words=2050, keywords=["dragonfly nails", "dragonfly nail ideas", "dragonfly nail art", "elegant nature nails"]),
    dict(url=KHAKI_URL, seo="Khaki Coded Style: How to Wear Utility Fashion in 2026", title="Khaki Coded, Without the Costume", description="Learn how to wear khaki coded style with field jackets, pleated trousers, linen and polished accessories, without making utility fashion feel like costume.", deck="The modern utility wardrobe is built on contrast: washed cotton with silk, useful pockets with clean tailoring, and earth tones with one dark anchor.", department="Fashion", topic="Trends", hero=f"{KHAKI_ROOT}/khaki-coded-hero", alt="Face-free street-style view of an olive field jacket with an ivory silk midi skirt, brown bag and loafers", body=KHAKI_BODY, words=2000, keywords=["khaki coded style", "khaki coded fashion", "utility fashion 2026", "field jacket outfits women"]),
    dict(url=BUG_URL, seo="Bug Jewellery Is Back: The Wilderkind Trend Explained", title="A Small Field Guide to Bug Jewellery", description="Explore the bug jewellery trend through beetles, moths, bees and dragonflies, including symbolism, antique references and modern ways to style each motif.", deck="Beetles, moths and dragonflies have returned to the jewel box. Wear one precise creature against an ordinary fabric and let it remain strange.", department="Fashion", topic="Jewellery", hero=f"{BUG_ROOT}/bug-jewellery-hero", alt="Gold beetle, silver dragonfly, bee earrings, moth pendant and scarab ring arranged on tobacco velvet", body=BUG_BODY, words=2050, keywords=["bug jewellery trend", "insect jewellery", "Wilderkind jewellery", "dragonfly brooch styling"]),
]


def add_reciprocal_link(path: Path, sentence: str) -> None:
    text = path.read_text(encoding="utf-8")
    if sentence in text:
        return
    match = re.search(r'(<p class="article-opening">.*?</p>)', text, flags=re.S)
    if not match:
        raise RuntimeError(f"Could not find opening paragraph in {path}")
    text = text[:match.end()] + sentence + text[match.end():]
    path.write_text(text, encoding="utf-8", newline="\n")


def main() -> None:
    for item in ARTICLES:
        document = base.page(item["url"], item["seo"], item["title"], item["description"], item["deck"], item["department"], item["topic"], item["hero"], item["alt"], item["body"], "BlogPosting", item["words"], item["keywords"])
        destination = ROOT / item["url"].strip("/") / "index.html"
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(document, encoding="utf-8", newline="\n")
        print("Built", destination.relative_to(ROOT))

    catalogue_path = ROOT / "content" / "articles.json"
    current = json.loads(catalogue_path.read_text(encoding="utf-8"))
    additions = []
    for item in ARTICLES:
        additions.append({"title": html.unescape(item["title"]), "seoTitle": html.unescape(item["seo"]), "department": item["department"].lower(), "topic": item["topic"].lower().replace(" ", "-"), "published": PUBLISHED, "readingMinutes": round(item["words"] / 195), "readingWordsPerMinute": 195, "url": item["url"], "excerpt": html.unescape(item["deck"]), "metaDescription": item["description"], "image": {"webp": f'{item["hero"]}.webp', "fallback": f'{item["hero"]}.jpg', "alt": item["alt"], "width": 1536, "height": 1024}, "articleSection": item["topic"], "breadcrumbTopic": True})
    urls = {item["url"] for item in additions}
    catalogue_path.write_text(json.dumps(additions + [item for item in current if item["url"] not in urls], ensure_ascii=False, indent=2) + "\n", encoding="utf-8", newline="\n")

    add_reciprocal_link(ROOT / "blogs/home/how-to-keep-your-space-clean/index.html", '<p>A small room also depends on protecting its work surface. Our <a href="/blogs/home/dorm-desk-hutch-ideas/">dorm desk hutch guide</a> applies the same systems to shelving, lighting and cable control.</p>')
    add_reciprocal_link(ROOT / "blogs/beauty/vamp-romantic-beauty-guide/index.html", '<p>For a smaller nature-led detail, see our guide to <a href="/blogs/beauty/dragonfly-nails/">dragonfly nails</a>, including smoky and moonlit versions that keep the motif precise.</p>')
    add_reciprocal_link(ROOT / "blogs/fashion/fall-2026-fashion-trends-worth-wearing/index.html", '<p>Our dedicated <a href="/blogs/fashion/khaki-coded-style/">khaki coded style guide</a> explains how to balance field jackets, utility trousers and desert neutrals without turning them into costume.</p>')
    add_reciprocal_link(ROOT / "blogs/fashion/how-to-wear-brooches/index.html", '<p>For the nature-led branch of the revival, our <a href="/blogs/fashion/bug-jewellery-trend/">bug jewellery field guide</a> covers beetles, moths, bees and dragonflies across brooches, rings and pendants.</p>')


if __name__ == "__main__":
    main()
