"""Build the 11 August 2026 scarf belt, Birkin bangs and mahjong features."""

from __future__ import annotations

import html
import json
from pathlib import Path

import build_august_two_features as base


ROOT = Path(__file__).resolve().parents[1]
PUBLISHED = "2026-08-11"
PUBLISHED_LABEL = "11 August 2026"
PUBLISHED_ISO = "2026-08-11T14:00:00+02:00"

base.PUBLISHED = PUBLISHED
base.PUBLISHED_LABEL = PUBLISHED_LABEL
base.PUBLISHED_ISO = PUBLISHED_ISO


def picture(root: str, name: str, alt: str) -> str:
    return f'''<figure class="media article-inline-image"><picture><source type="image/webp" srcset="{root}/{name}-640.webp 640w, {root}/{name}-960.webp 960w, {root}/{name}.webp 1536w" sizes="(max-width: 760px) calc(100vw - 2rem), 760px"><img src="{root}/{name}.jpg" width="1536" height="1024" loading="lazy" decoding="async" alt="{html.escape(alt)}"></picture></figure>'''


SCARF_URL = "/blogs/fashion/how-to-wear-a-scarf-belt/"
SCARF_TITLE = "How to Wear a Scarf Belt: The Proportion Rules That Make It Work"
SCARF_SEO = "How to Wear a Scarf Belt: 9 Chic Outfit Ideas for 2026"
SCARF_DESCRIPTION = "Learn how to tie a scarf as a belt with nine polished outfit formulas, secure knots, the right scarf sizes and proportion advice for every trouser rise."
SCARF_ROOT = "/assets/images/blogs/fashion/how-to-wear-a-scarf-belt"
SCARF_HERO = f"{SCARF_ROOT}/scarf-belt-hero"

scarf_body = f'''<div class="article-layout"><aside class="article-aside"><p class="kicker">The scarf belt file</p><ol><li><a href="#answer">The short answer</a></li><li><a href="#choose">Choose the scarf</a></li><li><a href="#tie">Fold and tie it</a></li><li><a href="#proportion">Read the proportions</a></li><li><a href="#outfits">Nine outfits</a></li><li><a href="#movement">The movement test</a></li><li><a href="#care">Care and storage</a></li></ol><button class="copy-link" data-copy-link type="button">Copy link</button></aside><div class="article-body">
<p class="article-opening">To wear a scarf as a belt without looking over-styled, fold a 65 to 90 centimetre square on the bias, thread it through one or more belt loops and make a compact knot slightly off-centre. Keep the clothes around it quiet. Denim, cotton poplin, linen and dry wool give printed silk enough resistance to look intentional.</p>
<p>The scarf belt has returned because it solves a familiar summer problem: an outfit is comfortable and complete, yet visually flat. Google&rsquo;s Summergeist report says searches for &ldquo;scarf belt&rdquo; reached a 20-year high, while its Spring 2026 fashion report identified &ldquo;bandana belt&rdquo; as a breakout query. The search interest is real. The styling question is still practical. A scarf is softer than leather, often decorative rather than load-bearing, and unusually sensitive to where it sits on the body.</p>
<div class="summary-box" id="answer"><p class="kicker">The concise answer</p><h2>Use the scarf as punctuation, not scaffolding</h2><p>Choose trousers that already fit, fold the scarf into a band, anchor it through at least one loop and tie a square knot rather than a loose bow. A short tail suits a defined waist; a longer fall works at the hip. If the print is loud, repeat only one of its colours elsewhere. The scarf should finish the silhouette, not hold it together.</p></div>

<section id="choose"><h2>Start with the right scarf, not the right knot</h2><p>A beautiful scarf can still make a poor belt. The useful variables are size, hand and print scale. Silk twill is the easiest place to begin because it has enough structure to hold a fold without becoming bulky. A very slippery satin loosens more quickly. Cotton bandanas grip well but look more casual. Fine wool works over autumn tailoring, provided it is not so thick that the knot becomes a fist at the waist.</p><h3>The most useful sizes</h3><p>A 65 to 75 centimetre square gives a neat band with short tails on a smaller waist or a partial-loop placement. An 85 to 90 centimetre square offers more room for a full pass through belt loops. Ghini Como&rsquo;s silk guide notes that a 70-centimetre square folded diagonally produces a band roughly four to five centimetres wide. That is a sound starting proportion: broad enough to register, narrow enough to pass through most loops.</p><p>Measure before relying on a knot. Fold the scarf, wrap it around the intended position and check that at least 15 centimetres remain at each end. If not, use it through two front loops, one side loop or over a dress rather than pulling the knot tight. Never force a delicate rolled hem through a narrow metal loop.</p><h3>Print scale changes the effect</h3><p>A small geometric print reads almost like texture once folded. A large equestrian, floral or landscape print becomes a sequence of abstract colour fragments. Neither is better, but the second demands restraint. Lay the scarf open and decide which diagonal contains the colours you want visible. The reverse diagonal can produce what looks like a completely different accessory.</p></section>

{picture(SCARF_ROOT, "scarf-belt-bias-fold", "Hands folding a burgundy, cream and olive silk scarf diagonally on an oak table")}

<section id="tie"><h2>How to tie a scarf as a belt so it stays put</h2><h3>The bias-fold method</h3><ol><li>Lay the scarf face down and bring two opposite corners towards the centre.</li><li>Fold those pointed edges inward again until they meet.</li><li>Fold the long band once more to reach a width of about four centimetres.</li><li>Press the fold with your palm. Use a cool iron only if the care label allows it.</li><li>Thread the band through the loops without dragging the rolled edges against zips or rivets.</li><li>Tie the ends right over left, then left over right, creating a flat square knot.</li></ol><p>The square knot matters because it lies flatter than a double overhand knot and resists twisting. Leave enough room to place two fingers beneath the band. Silk pulled under constant tension can crease and the knot can become difficult to release.</p><h3>Three placements that look deliberate</h3><p><strong>Full belt:</strong> thread every loop when the trousers fit independently and the scarf is long enough to tie without strain. <strong>Front bridge:</strong> pass through the two front loops and let the scarf replace only the visible section of a belt. This is useful with shorter squares. <strong>Side anchor:</strong> pass through one side loop and knot at the hip, allowing longer tails to fall. This is decorative and particularly good over tailoring or a column dress.</p><p>A loose scarf placed over beltless trousers will migrate. If there are no loops, use it on a dress with a defined waist seam, or discreetly secure the band to the garment from the inside with two small safety pins. Do not pin through a valuable silk scarf.</p></section>

<section id="proportion"><h2>The proportion rules that stop it looking costume-like</h2><p>The most important decision is not the knot. It is the line the scarf draws across the body. A high-rise trouser with a scarf at the natural waist shortens the torso and lengthens the leg. A mid-rise placement feels neutral. A scarf slung below the waistband lengthens the torso and makes the styling more relaxed, but it can also interrupt a short frame if the tails are very long.</p><p>Match tail length to the garment volume. Wide trousers can carry a longer vertical fall because the line gives them direction. Slim jeans look cleaner with compact ends. A full skirt already creates movement, so a small knot keeps the waist from becoming busy. With a straight dress, an asymmetrical tail can introduce shape without cinching every centimetre.</p><p>Then consider contrast. A scarf belt works best when it is the softest, most expressive object in the outfit. Pair it with fabrics that have a matte or slightly weathered surface. This is the same tension that makes the modern brooch work: as our <a href="/blogs/fashion/how-to-wear-brooches/">guide to wearing brooches</a> explains, formality feels current when it meets an ordinary garment.</p></section>

<section id="outfits"><h2>Nine scarf belt outfits worth repeating</h2><div class="article-table-wrap" role="region" aria-label="Nine scarf belt outfit formulas" tabindex="0"><table class="article-visual-table"><thead><tr><th>Base</th><th>Scarf move</th><th>Finish</th></tr></thead><tbody><tr><td>Dark straight jeans and white shirt</td><td>Burgundy square through every loop</td><td>Black loafer and small gold earring</td></tr><tr><td>Ecru linen trousers and ribbed tank</td><td>Navy print in a front bridge</td><td>Brown flat sandal and woven bag</td></tr><tr><td>Charcoal pleated trousers and grey tee</td><td>Ivory scarf knotted at the side</td><td>Minimal trainer or almond-toe flat</td></tr><tr><td>Black column dress</td><td>Long scarf resting low on the hip</td><td>One silver cuff, nothing else</td></tr><tr><td>Denim Bermuda shorts and poplin shirt</td><td>Red bandana in a compact front knot</td><td>Leather fisherman sandal</td></tr><tr><td>Khaki utility trousers and cream knit</td><td>Botanical silk through two loops</td><td>Suede loafer and canvas tote</td></tr><tr><td>White midi skirt and black tee</td><td>Black and ivory scarf at natural waist</td><td>Simple ballet flat</td></tr><tr><td>Navy suit with collarless vest</td><td>Long ecru scarf over the waistband</td><td>Oxblood bag and quiet jewellery</td></tr><tr><td>Pale blue shirtdress</td><td>Brown geometric square, off-centre</td><td>Low wedge and raffia clutch</td></tr></tbody></table></div>
<p>The denim formula is the easiest because the scarf replaces the visual weight of a conventional belt without competing with many details. The suit formula is more advanced. Leave the jacket open and make sure the scarf sits below its buttoning point, otherwise two horizontal centres fight for attention.</p><p>For a holiday wardrobe, use a scarf that already serves as a hair tie or bag handle, but do not wear it in all three places at once. One silk accent feels personal. Repetition turns it into a theme. The principle also keeps the <a href="/blogs/fashion/european-summer-style-2026/">European summer wardrobe</a> from becoming a costume assembled from recognisable props.</p></section>

{picture(SCARF_ROOT, "scarf-belt-tailoring", "Faceless figure in black wool tailoring with a long ecru fringed scarf tied at the waist")}

<section id="movement"><h2>Do the movement test before leaving home</h2><p>Sit, bend, walk quickly and use the bathroom. The test is unglamorous and necessary. A scarf that looks exact in a mirror can rotate as soon as the hips move. If the knot slides, pass the band through one more loop or place the knot immediately beside a loop so the hardware acts as a stop.</p><p>Check that the tails cannot reach a bicycle chain, escalator edge or open flame. Long tails belong on a slow outfit, not a commute involving machinery. At a restaurant, position them away from the lap. A low side knot should not sit exactly where a shoulder bag rubs.</p><p>The scarf is not a substitute for a functioning belt. If trousers need tension to stay up, wear a slim belt and tie the scarf around one loop, or choose a belt buckle designed to accept fabric. This prevents strain on the silk and prevents the waistband from sagging beneath a decorative band.</p><h3>If it still feels too styled</h3><p>Remove one adjacent signal. Unbutton the shirt rather than adding necklaces. Carry a plain leather bag rather than raffia. Choose a loafer instead of a wedge. The answer is rarely a smaller scarf; it is usually fewer ideas competing around it. The strongest outfits in our <a href="/blogs/fashion/romantic-fashion-trend-2027/">sharper romantic fashion guide</a> use the same editing method: one expressive material, one resistant material, then stop.</p></section>

<section id="care"><h2>Keep the scarf crisp without making it precious</h2><p>Untie the knot after each wear. Leaving silk knotted sets deep creases and puts sustained pressure on the same fibres. Air it flat, then roll or fold it loosely away from direct sun. Treat spills according to the label, particularly with hand-rolled hems and saturated prints. Water, perfume and hand sanitiser can mark some silks.</p><p>Before buying vintage, examine the diagonal for pinholes, thinning and old fold lines. A scarf can be strong enough for the neck but too fragile for repeated contact with denim hardware. Cotton and washable silk blends are more forgiving if the belt will be used often.</p></section>

<section class="article-faq"><h2>Scarf belt questions, answered</h2><h3>What size scarf works as a belt?</h3><p>A 70-centimetre square suits partial-loop styling and smaller waists. An 85 to 90-centimetre square is more reliable for threading around a full waistband. Always test the folded length against your body and garment.</p><h3>Can a scarf belt hold up trousers?</h3><p>It should not be responsible for heavy tension. Wear trousers that fit, add a slim functional belt underneath or anchor the scarf decoratively through one or two loops.</p><h3>How do I stop a silk scarf belt slipping?</h3><p>Use a flat square knot, position it beside a belt loop and avoid very glossy satin. A bias fold provides a little more grip and distributes pressure better than rolling the scarf into a rope.</p></section>

<section class="source-note"><h2>Sources and editorial notes</h2><p>Search-interest facts were checked on 11 August 2026 against <a href="https://trends.withgoogle.com/trends/summergeist/">Google Summergeist</a> and Google&rsquo;s <a href="https://blog.google/products-and-platforms/products/search/spring-2026-fashion-beauty-trends/">Spring 2026 fashion and beauty trends report</a>. Current styling context was reviewed in <a href="https://www.whowhatwear.com/fashion/outfit-ideas/scarf-belt-outfits-2026">Who What Wear</a>, <a href="https://www.glamourmagazine.co.uk/article/scarf-belt-trend">Glamour UK</a> and <a href="https://chatelaine.com/style/fashion/how-to-style-a-silk-scarf/">Chatelaine</a>. Scarf-size guidance was checked with <a href="https://ghinicomo.com/blogs/world-of-silk/how-to-wear-a-silk-scarf-as-a-belt-the-complete-styling-guide">Ghini Como</a>. Styling recommendations are by.foro editorial opinion. The photographs are original, fictional editorial images created for this article.</p></section>
<section><h2>The best scarf belt looks discovered, not demonstrated</h2><p>The pleasure of the scarf belt is that it introduces colour without the commitment of a new wardrobe. Its success depends on accuracy: the right length, a flat knot, a position that agrees with the rise and enough restraint elsewhere. Once those decisions are sound, the scarf can look as if it simply happened to belong there.</p></section>
<div class="article-end"><span>End</span><p>Published by by.foro Editorial on 11 August 2026. For corrections, contact <a href="mailto:hello@byforo.com">hello@byforo.com</a>.</p></div></div></div>'''


BIRKIN_URL = "/blogs/beauty/birkin-bangs-guide/"
BIRKIN_TITLE = "Birkin Bangs: What the Effortless Fringe Actually Requires"
BIRKIN_SEO = "Birkin Bangs: The 2026 Fringe Trend and Styling Guide"
BIRKIN_DESCRIPTION = "Birkin bangs are the soft, eyebrow-grazing fringe trending in 2026. Learn who they suit, what to ask for, how to style them and maintain the cut."
BIRKIN_ROOT = "/assets/images/blogs/beauty/birkin-bangs-guide"
BIRKIN_HERO = f"{BIRKIN_ROOT}/birkin-bangs-hero"

birkin_body = f'''<div class="article-layout"><aside class="article-aside"><p class="kicker">The fringe file</p><ol><li><a href="#definition">What they are</a></li><li><a href="#anatomy">The anatomy</a></li><li><a href="#consultation">What to ask for</a></li><li><a href="#suitability">Will they suit you?</a></li><li><a href="#styling">How to style them</a></li><li><a href="#maintenance">Maintenance</a></li><li><a href="#compare">Birkin vs curtain</a></li></ol><button class="copy-link" data-copy-link type="button">Copy link</button></aside><div class="article-body">
<p class="article-opening">Birkin bangs are a light, eyebrow-grazing fringe with shorter pieces through the centre, slightly longer edges and separated, textured ends. They are worn mostly forward rather than divided into a perfect curtain. The result looks relaxed, but the cut is precise: too much density creates a blunt block, while too little planning makes the fringe resemble accidental breakage.</p>
<p>Google identified &ldquo;Birkin bangs&rdquo; as a breakout search in its Spring 2026 report. The name refers to the soft fringe associated with Jane Birkin&rsquo;s 1960s and 1970s hair, yet a useful salon appointment needs more than a reference photograph. Hairline, shrinkage, density, glasses and tolerance for daily restyling decide whether the idea translates.</p>
<div class="summary-box" id="definition"><p class="kicker">The concise definition</p><h2>A soft full fringe, not a miniature curtain</h2><p>Ask for an eyebrow-length fringe that is airy at the ends, slightly shorter in the middle and softly connected to longer face-framing pieces. It should contain less hair than a traditional blunt fringe. Wear it forward with small separations, not split into two heavy wings.</p></div>

<section id="anatomy"><h2>The four details that make bangs look Birkin</h2><h3>1. The centre sits near the brows</h3><p>The central pieces normally graze the brow or sit just above it once dry. This is the part that gives the haircut its recognisable frame. Cutting it wet without allowing for shrinkage can push it into baby-bang territory, especially on waves and curls.</p><h3>2. The sides become longer gradually</h3><p>The transition should be visible but not dramatic. Longer corners soften the join into the rest of the hair and make growing the fringe out less awkward. They are not cheekbone-length curtain pieces. If the difference becomes too large, the centre looks disconnected.</p><h3>3. The ends are broken, not shredded</h3><p>Texture removes the hard horizontal line. It should not leave translucent strings. NewBeauty&rsquo;s interviews with stylists describe the fringe as thinner towards the ends, with dimension rather than a solid edge. That requires judgement. Aggressive thinning shears can make fine hair fly away and curly hair expand unpredictably.</p><h3>4. The section is relatively shallow</h3><p>A classic heavy fringe may begin farther back on the crown, pulling a substantial triangular section forward. Birkin bangs usually need less hair. The exact section depends on density and hairline, which is why copying a diagram from social media is risky.</p></section>

<section id="consultation"><h2>What to ask for at the salon</h2><p>Bring three references: the version you love, the longest version you could accept and one example on hair with a texture close to yours. A single celebrity image often shows a styled result, not the raw cut. Tell the stylist how your hair behaves after air-drying, where it separates and how often you use heat.</p><blockquote><p>&ldquo;I want a light, eyebrow-grazing fringe worn forward, slightly shorter in the centre, longer at the outer edges and softly texturised. Please keep the section shallow and cut with my dry shrinkage in mind.&rdquo;</p></blockquote><p>That sentence is a starting brief, not a technical command. An experienced stylist may adjust it for a cowlick, low hairline or strong wave. NewBeauty&rsquo;s experts specifically recommend a clean, dry finish for precision. For textured hair, a stylist who routinely cuts the texture in its natural state matters more than the trend name.</p><p>Agree on the shortest acceptable point while you are both looking at dry hair. If you are uncertain, start longer. A fringe can be refined in millimetres; it cannot be returned after one decisive snip.</p></section>

{picture(BIRKIN_ROOT, "birkin-bangs-salon", "Stylist hands blow-drying a soft fringe forward on a featureless salon training block")}

<section id="suitability"><h2>Who Birkin bangs suit is the wrong first question</h2><p>Face-shape advice can be useful, but daily compatibility matters more. The fringe exposes the brows and concentrates attention around the eyes. Longer side pieces can soften a square jaw or add width beside a longer face. Those are visual effects, not rules. A good stylist can alter width, density and length without losing the character of the cut.</p><p>Ask instead whether your hair and routine can support the finish:</p><div class="article-table-wrap" role="region" aria-label="Birkin bangs by hair type and routine" tabindex="0"><table class="article-visual-table"><thead><tr><th>Hair or habit</th><th>Useful adjustment</th><th>Watch for</th></tr></thead><tbody><tr><td>Fine, straight hair</td><td>Keep a shallow section and blunt enough interior weight</td><td>Over-texturising that creates gaps</td></tr><tr><td>Thick, straight hair</td><td>Remove controlled weight beneath the surface</td><td>A dense shelf across the brows</td></tr><tr><td>Wavy hair</td><td>Cut near its natural dry pattern</td><td>Uneven shrinkage after washing</td></tr><tr><td>Curly hair</td><td>Work curl by curl and begin longer</td><td>Stretching curls during the cut</td></tr><tr><td>Strong cowlick</td><td>Adjust the part, width or length around it</td><td>Demanding perfect symmetry</td></tr><tr><td>Glasses wearer</td><td>Test the dry fringe with frames on</td><td>Ends catching behind the lenses</td></tr><tr><td>Oily forehead</td><td>Use less product and refresh the fringe alone</td><td>Heavy creams separating the ends</td></tr></tbody></table></div>
<p>Who What Wear&rsquo;s 2026 bang report highlights the fringe for fine hair and longer or square faces, but no chart can account for the angle of a hairline or the position of someone&rsquo;s glasses. The consultation should happen with your usual frames and your normal part visible.</p><p>If daily styling already irritates you, choose a longer interpretation that can be pushed aside. This is one advantage over the very graphic short fringe. Birkin bangs can migrate into face-framing layers rather than requiring a dramatic grow-out.</p></section>

<section id="styling"><h2>How to style Birkin bangs in five minutes</h2><p>Style the fringe first, while it is properly wet. Once the hair has dried in a split or cowlick, adding more heat usually creates stiffness rather than movement.</p><ol><li><strong>Reset the roots.</strong> Mist the fringe from root to end, even if the rest of the hair stays dry.</li><li><strong>Dry forward.</strong> Vogue Germany cites stylist Larry King recommending a forward blow-dry, ideally with a round brush. Direct the roots down before trying to curve the ends.</li><li><strong>Move side to side.</strong> Sweep the dryer left and right across the forehead to interrupt a fixed part.</li><li><strong>Bend, do not curl.</strong> Give the ends one slight pass with a small round brush. Rolling them under for too long creates a bubble.</li><li><strong>Separate with dry fingers.</strong> Use the residue of a light styling cream or a tiny spray of flexible hold on the fingers. The spaces should look irregular.</li></ol><p>A flat brush works if a round brush gives too much lift. On wavy hair, twist only the pieces that naturally want definition and leave the rest imperfect. Air-drying can be beautiful, but clip the root in the intended direction while it sets.</p><p>Dry shampoo is most useful as prevention. Apply a small amount underneath clean fringe roots before they become oily, then brush through. Spraying a white cloud over separated ends makes them dull and gritty.</p></section>

<section><h2>Weather changes the fringe before it changes the haircut</h2><p>Humidity can make a carefully separated fringe contract, widen or return to its natural wave. Rain can split it at the root. Carry a small comb, but resist repeatedly brushing through damp hair, which can create a fuzzy, expanded edge. Instead, press the roots into place with clean fingers and let the fringe settle before deciding it has failed.</p><p>In dry weather, static creates the opposite problem: the light ends float away from the intended line. Put a pinhead amount of hand cream on your palms, wipe almost all of it away, then touch only the outer surface of the hair. A silk-lined hat is kinder than rough wool, but any close hat will flatten the root. When you remove it, dampen the fingertips and move the fringe side to side at the base rather than adding more product.</p></section>

{picture(BIRKIN_ROOT, "birkin-bangs-wavy", "Dark wavy wig with a piecey fringe on a featureless black display form beside a rainy cafe window")}

<section id="maintenance"><h2>The maintenance nobody includes in the reference picture</h2><p>The fringe touches skin, collects product and shows growth quickly. Expect to wash it separately between full wash days. A sink rinse takes two minutes and generally looks fresher than layering powder over yesterday&rsquo;s oil.</p><p>Trim timing varies with growth rate and chosen length. When the centre begins entering the eyes rather than grazing the brows, the shape has changed. Many salons offer short fringe appointments between full cuts. Use them. Cutting the centre at home can flatten the soft arc, and pulling hair taut produces a shorter result when it springs back.</p><p>Skin care also affects the fringe. Allow sunscreen and moisturiser to settle before releasing the hair. At night, clip it loosely away from the face rather than coating it in sleep-mask product. Clean brushes regularly, since a small fringe can pick up more oil from a dirty tool than from an entire day of wear.</p><h3>The graceful exit plan</h3><p>As the centre grows, move the part a few millimetres off-centre and let the longer corner lead. At cheekbone length, ask the stylist to connect the former fringe into face-framing layers. The transition mirrors the logic in our <a href="/blogs/beauty/japanese-bob-vs-scandi-bob/">Japanese bob versus Scandi bob guide</a>: the most wearable haircut is one whose shape remains coherent between appointments.</p></section>

<section id="compare"><h2>Birkin bangs vs curtain bangs vs Bardot fringe</h2><p>Names drift across salons and social platforms, so describe geometry rather than relying on a label. Birkin bangs sit forward, reach the brows and have a fine, irregular edge. Curtain bangs are usually longer, divided through the centre and swept away from the face. A Bardot fringe often has a fuller, more voluptuous centre with pronounced parted sides and greater crown volume.</p><p>Cosmopolitan describes the Birkin shape as shorter through the middle and longer at the edges, while Who What Wear&rsquo;s comparison places it just below the eyebrow with textured ends. These definitions overlap, but both distinguish it from a clearly parted curtain. If the image you love has the forehead fully visible at the centre, you probably want curtain bangs, whatever the caption calls them.</p><p>The distinction matters because the routine changes. A forward fringe needs root control and more frequent washing. A curtain can tolerate length and oil more easily but often needs outward heat styling. Bardot volume may require rollers or more deliberate blow-drying. Choose the work you prefer, not the name with the most momentum.</p></section>

<section class="article-faq"><h2>Birkin bangs questions</h2><h3>Are Birkin bangs high maintenance?</h3><p>They are moderate to high maintenance because brow length changes quickly and the hair touches the forehead. Daily styling can take under five minutes, but fringe washing and regular trims are part of the cut.</p><h3>Can curly hair wear Birkin bangs?</h3><p>Yes, with a curl-aware adaptation. The stylist should account for dry shrinkage, work with the curl pattern and usually begin longer. The result will not copy straight-hair separation exactly.</p><h3>Are Birkin bangs the same as curtain bangs?</h3><p>No. Birkin bangs are shorter and worn mainly forward. Curtain bangs are longer, more clearly parted and swept towards the sides.</p></section>

<section class="source-note"><h2>Sources and image note</h2><p>Current search interest was checked on 11 August 2026 against Google&rsquo;s <a href="https://blog.google/products-and-platforms/products/search/spring-2026-fashion-beauty-trends/">Spring 2026 fashion and beauty report</a>. Cut terminology and salon guidance were cross-checked with <a href="https://www.newbeauty.com/view/bang-trend-jane-birkin-bangs">NewBeauty</a>, <a href="https://www.vogue.de/galerie/birkin-bangs-pony-jane-birkin-70er">Vogue Germany</a>, <a href="https://www.cosmopolitan.com/style-beauty/beauty/a68075095/birkin-bangs-haircut/">Cosmopolitan</a> and <a href="https://www.whowhatwear.com/beauty/hair/2026-bang-trends">Who What Wear</a>. Salon recommendations remain general and should be adapted by a qualified stylist who can assess the hair in person. The original editorial images show hair on featureless salon display forms; no human faces appear.</p></section>
<section><h2>The effortlessness is in the editing</h2><p>Birkin bangs work because the line is incomplete. Brows appear through the fringe, corners dissolve into the haircut and the ends refuse perfect spacing. None of that is accidental. A cautious first cut, honest conversation about texture and a light daily reset create the ease that the finished photograph seems to promise.</p></section>
<div class="article-end"><span>End</span><p>Published by by.foro Editorial on 11 August 2026. For corrections, contact <a href="mailto:hello@byforo.com">hello@byforo.com</a>.</p></div></div></div>'''


MAHJONG_URL = "/blogs/fashion/mahjong-necklace-meaning/"
MAHJONG_TITLE = "Mahjong Necklaces: Know the Tile Before You Wear It"
MAHJONG_SEO = "Mahjong Necklace Meaning: The 2026 Jewellery Trend"
MAHJONG_DESCRIPTION = "Mahjong necklaces are trending in 2026. Learn what common tile designs mean, how to buy responsibly and style this culturally significant jewellery."
MAHJONG_ROOT = "/assets/images/blogs/fashion/mahjong-necklace-meaning"
MAHJONG_HERO = f"{MAHJONG_ROOT}/mahjong-necklace-hero"

mahjong_body = f'''<div class="article-layout"><aside class="article-aside"><p class="kicker">The object file</p><ol><li><a href="#answer">The short answer</a></li><li><a href="#why-now">Why it is trending</a></li><li><a href="#tiles">Read the tile</a></li><li><a href="#history">History and context</a></li><li><a href="#buying">Buy responsibly</a></li><li><a href="#styling">How to wear it</a></li><li><a href="#questions">Ask the seller</a></li></ol><button class="copy-link" data-copy-link type="button">Copy link</button></aside><div class="article-body">
<p class="article-opening">A mahjong necklace usually suspends a miniature tile, a tile-inspired design or a repurposed playing tile as a pendant. Its clearest meaning is the identity printed on that tile: a circle, bamboo or character suit number, a wind, a dragon or, in some sets, a flower or season. It is not safe to assign every design a universal promise of luck, wealth or romance. Mahjong varies across regions, families and rule sets, and jewellery descriptions often simplify that context.</p>
<p>The necklace has moved into fashion&rsquo;s foreground. Google&rsquo;s Summergeist report identified &ldquo;mahjong necklace&rdquo; as a breakout search over the previous month. At the same time, boutique mah-jongg events, clubs and redesigned sets have brought the game into wider lifestyle coverage. The object is visually ideal for jewellery: small, graphic, recognisable and personal. That makes knowing what it represents more important, not less.</p>
<div class="summary-box" id="answer"><p class="kicker">The concise answer</p><h2>The tile has an identity before it has a fashion meaning</h2><p>First identify the suit or honour shown on the pendant. A nine-circle design is the nine of the circles or dots suit; it is not automatically a charm for &ldquo;ninefold fortune.&rdquo; Winds and dragons have roles inside the game, while flower and season tiles differ by set. Ask the seller to name the exact tile, explain whether it is newly made or repurposed and disclose its material.</p></div>

<section id="why-now"><h2>Why mahjong necklaces are appearing now</h2><p>The easy explanation is nostalgia. The better one is convergence. Fashion is interested in object jewellery, pieces that resemble keys, dice, matchbooks, shells and game components. Mahjong tiles already have colour, scale and a grid-like face. They read clearly in a close photograph and layer naturally with chains or pearls.</p><p>Mahjong itself is also highly visible. Recent reporting by Vanity Fair and The Week has examined the growth of boutique sets, clubs and social play. The game provides an analogue gathering at a moment when many people are seeking structured ways to spend time together. Jewellery converts that table-level belonging into something portable.</p><p>There is a tension inside that popularity. A pendant can be an intimate reference to family games, a gift between players, an heirloom remade after a set becomes incomplete or simply an attractive object bought without knowledge. Those stories are not interchangeable. The necklace becomes more interesting when its owner can explain which one is true.</p></section>

<section id="tiles"><h2>How to read the most common mahjong tile designs</h2><p>A common traditional set contains 144 tiles, although composition changes across regional versions. The basic numbered suits are circles or dots, bamboo and characters. Honour tiles include winds and dragons. Flower and season tiles may be present as bonus tiles. English names and romanisation vary, and American mah-jongg introduces its own rule structure and conventions.</p><div class="article-table-wrap" role="region" aria-label="Mahjong tile pendant identification guide" tabindex="0"><table class="article-visual-table"><thead><tr><th>Design</th><th>Game identity</th><th>What a seller should clarify</th></tr></thead><tbody><tr><td>One to nine circular marks</td><td>Numbered circles or dots suit</td><td>The exact number and whether the graphic copies a specific regional set</td></tr><tr><td>Bamboo-like strokes</td><td>Numbered bamboo suit</td><td>Whether the one bamboo is represented by a bird, as in many sets</td></tr><tr><td>Chinese numerals and a red character</td><td>Numbered characters suit</td><td>The number, character accuracy and maker</td></tr><tr><td>East, South, West or North character</td><td>Wind honour tile</td><td>Which wind and why it was selected</td></tr><tr><td>Red, green or blank/outlined tile</td><td>Dragon honour tile</td><td>Which dragon convention the design follows</td></tr><tr><td>Plant, flower, figure or season image</td><td>Often a bonus flower or season tile</td><td>The set, region and inscription, because designs vary widely</td></tr></tbody></table></div>
<h3>Identity is not the same as symbolism</h3><p>Numbers, colours and characters can carry associations in Chinese culture, and individual families may have their own favourite tiles. That does not create a standard necklace dictionary. A product page that turns every numbered tile into a precise personality or destiny is usually selling a story rather than documenting the game.</p><p>The safest language is specific. Say &ldquo;nine of circles pendant&rdquo; if that is what the piece shows. Say &ldquo;East wind tile&rdquo; if the character has been checked. If a maker describes a personal or familial meaning, attribute it to that maker rather than presenting it as universal.</p></section>

{picture(MAHJONG_ROOT, "mahjong-necklace-game-table", "Family-style mahjong game at dusk with circle-suit tiles and a gold tile pendant beside a velvet box")}

<section id="history"><h2>A brief history the trend cannot be separated from</h2><p>Mahjong developed in China during the late Qing period. Research from Academia Sinica connects its emergence to earlier card play, including the madiao tradition. By the early twentieth century the tile game was travelling internationally, adapting as communities carried it across languages and borders.</p><p>In the United States, mah-jongg became important within both Chinese American and Jewish American social life. Time&rsquo;s history of the game describes how it created community while also being marketed through exoticised images of China. Those parallel histories matter because today&rsquo;s revival repeats an old pattern: genuine social connection sits beside commercial reinvention.</p><p>A necklace does not need to become a history lecture. It should, however, resist the idea that the tile is an anonymous lucky token. If the pendant comes from a grandmother&rsquo;s incomplete set, record that story. If it was newly designed by a Chinese jeweller who grew up playing, credit the maker. If you simply like the graphic form, learn its name before wearing it.</p><h3>Mahjong and mah-jongg are both used</h3><p>&ldquo;Mahjong&rdquo; is the common broad spelling. &ldquo;Mah-jongg&rdquo; is frequently associated with the American game, including organised American rules. Spelling alone does not prove a piece&rsquo;s origin. Look for the maker&rsquo;s description of the set, play tradition and source tile.</p></section>

<section id="buying"><h2>How to buy mahjong tile jewellery responsibly</h2><p>Begin with provenance. A newly cast ceramic, resin or enamel pendant should be described as tile-inspired, not antique. A repurposed tile should come with the best available information about its age, material and how it left the set. Turning one tile from a complete usable vintage set into jewellery destroys the set&rsquo;s function; using an orphaned replacement is a different decision.</p><h3>Material is not a decorative footnote</h3><p>Old tiles may be bamboo-backed bone, early plastic, celluloid or other materials. Some antiques may contain ivory. Do not rely on colour, weight or a hot-needle test, which can damage an object and still mislead. Ask a reputable specialist, request written material information and avoid purchasing ivory. Laws differ by location and can restrict sale, transport and import.</p><p>For a wearable everyday piece, contemporary ceramic, glass, enamel or responsibly documented resin is usually simpler. Check how the bail is attached. A screw eye driven into an old laminated tile can separate layers. A fitted cap or well-designed bezel distributes strain more evenly. Examine the corners for chips and the drilled area for hairline cracks.</p><p>Then inspect the graphic. Decorative interpretations are legitimate when clearly described, but pseudo-characters presented as authentic are a warning sign. A maker should be able to name the tile and explain intentional departures from a traditional design.</p></section>

{picture(MAHJONG_ROOT, "mahjong-necklace-layering", "Black silk blouse styled with a pearl strand, fine gold chain and small four-circle mahjong tile pendant")}

<section id="styling"><h2>How to style a mahjong necklace without turning it into a theme</h2><p>The pendant already contains a miniature composition, so treat it like an artwork rather than a charm among ten unrelated charms. On a short gold chain, let it sit against a plain crew neck, black silk blouse or open white collar. On a longer cord, pair it with dry linen, denim or a dark knit so the glossy tile has contrast.</p><p>Pearls work because they repeat the circular marks found in the dots suit without copying the tile literally. Keep the pearl strand close to the neck and place the pendant several centimetres lower so the two pieces occupy separate lines. Heavy gold links make a stronger 1980s statement, especially beside the oversized tailoring in our <a href="/blogs/fashion/glamoratti-style-2026/">Glamoratti style guide</a>.</p><p>Avoid combining the pendant with printed silk covered in fans, dragons or generic chinoiserie. That creates a costume from unrelated symbols. The cleaner approach resembles modern brooch styling: one charged object against an ordinary, beautifully cut garment. See our <a href="/blogs/fashion/how-to-wear-brooches/">brooch placement guide</a> for the same formality contrast.</p><h3>Three reliable combinations</h3><ul><li><strong>Day:</strong> an ivory dots-suit pendant on a 45-centimetre gold chain, worn over a charcoal crew-neck tee with straight trousers.</li><li><strong>Evening:</strong> a dark tile in a gold bezel against a black silk column, with one cuff and no competing earrings.</li><li><strong>Personal:</strong> an inherited or gifted pendant on a plain cord beside clothing with family relevance, allowing the story rather than the price to carry the look.</li></ul><p>If the tile is physically large, avoid a long chain that lets it strike a table edge. A pendant intended for regular game nights should sit above the sternum or be removed before play.</p></section>

<section id="questions"><h2>Seven questions to ask before buying</h2><ol><li>Which exact tile does this pendant depict?</li><li>Is it newly made, tile-inspired or repurposed from a playable set?</li><li>What material is it, and how was that identification made?</li><li>If vintage, was it an orphaned tile or taken from a complete set?</li><li>Who designed or assembled the jewellery?</li><li>Does the product description claim a cultural meaning, and what source supports it?</li><li>Can the setting, bail and chain support the tile&rsquo;s weight in daily wear?</li></ol><p>A seller who answers these clearly is offering more than polish. They are showing respect for the object&rsquo;s history and giving the buyer enough information to care for it. This is part of <a href="/blogs/culture/how-taste-is-built/">how taste is built</a>: close attention replaces the assumption that recognition alone equals knowledge.</p></section>

<section class="article-faq"><h2>Mahjong necklace questions</h2><h3>What does a mahjong necklace mean?</h3><p>Its most verifiable meaning is the identity of the tile it depicts. Personal, family or maker-specific meanings may be important, but numbered tiles do not have one universal jewellery symbolism.</p><h3>Are mahjong necklaces good-luck charms?</h3><p>Some owners or makers may treat particular pieces as lucky, especially when connected to play or family. Do not assume every mahjong pendant was traditionally created as a good-luck amulet.</p><h3>What does a nine-dot mahjong necklace mean?</h3><p>It depicts the nine of the circles or dots suit. Any further claim, such as a precise promise of prosperity, should be attributed to a particular maker or tradition rather than stated as a universal fact.</p><h3>Is it respectful to wear one?</h3><p>Context matters. Learn the tile, choose transparent sourcing, avoid invented meanings and credit the maker or family story. Treating the object as culturally specific is more respectful than presenting it as an anonymous exotic charm.</p></section>

<section class="source-note"><h2>Sources and editorial notes</h2><p>Search interest was checked on 11 August 2026 against <a href="https://trends.withgoogle.com/trends/summergeist/">Google Summergeist</a>. Tile composition was cross-checked with <a href="https://www.thoughtco.com/explanation-of-mahjong-tiles-687561">ThoughtCo&rsquo;s illustrated tile guide</a>, with the caveat that sets and rules vary. Historical context draws on research from the <a href="https://www1.ihp.sinica.edu.tw/en/Publications/Bulletin/1123/Article/207">Institute of History and Philology, Academia Sinica</a>, the <a href="https://www.museumofplay.org/app/uploads/2022/05/Finding-Aid-to-the-Mahjong-oral-history-collection_060622.pdf">Strong Museum of Play oral-history collection</a> and <a href="https://time.com/6045817/mahjongg-history/">Time</a>. Current revival context was reviewed in <a href="https://www.vanityfair.com/culture/story/business-history-boutique-mah-jongg-boom">Vanity Fair</a> and <a href="https://theweek.com/environment/mahjong-chinese-tile-game-community-analog-game">The Week</a>. Legal restrictions vary; this article is not legal advice. The photographs are original editorial images and use circle-suit motifs rather than copied branded tiles.</p></section>
<section><h2>Wear the object with its name intact</h2><p>The mahjong necklace is compelling because it compresses a social game into a small, exact object. Its surface may be fashionable, but it is not blank. Knowing the suit, number, maker and material does not make the pendant less playful. It gives the beauty somewhere honest to begin.</p></section>
<div class="article-end"><span>End</span><p>Published by by.foro Editorial on 11 August 2026. For corrections, contact <a href="mailto:hello@byforo.com">hello@byforo.com</a>.</p></div></div></div>'''


ARTICLES = [
    dict(url=SCARF_URL, seo=SCARF_SEO, title=SCARF_TITLE, description=SCARF_DESCRIPTION, deck="The scarf belt is back, but the difference between effortless and overworked comes down to size, placement and one very practical knot.", department="Fashion", topic="Accessories", hero=SCARF_HERO, alt="Faceless street-style outfit with an ivory shirt, dark jeans and a burgundy silk scarf tied through belt loops", body=scarf_body, words=2050, keywords=["how to tie a scarf as a belt", "scarf belt outfits", "silk scarf belt", "bandana belt outfit"]),
    dict(url=BIRKIN_URL, seo=BIRKIN_SEO, title=BIRKIN_TITLE, description=BIRKIN_DESCRIPTION, deck="The soft 1970s fringe has returned. Its apparent ease depends on a shallow section, an exact dry length and a routine you can actually maintain.", department="Beauty", topic="Hair", hero=BIRKIN_HERO, alt="Chestnut wig with a soft eyebrow-grazing Birkin fringe on a featureless salon display head", body=birkin_body, words=2000, keywords=["Birkin bangs", "Birkin bangs 2026", "Birkin bangs vs curtain bangs", "how to style Birkin bangs"]),
    dict(url=MAHJONG_URL, seo=MAHJONG_SEO, title=MAHJONG_TITLE, description=MAHJONG_DESCRIPTION, deck="The tile pendant is becoming 2026&rsquo;s most specific piece of object jewellery. Before wearing one, learn what the design actually represents.", department="Fashion", topic="Accessories", hero=MAHJONG_HERO, alt="Gold chain with an ivory nine-circle mahjong tile pendant arranged on oxblood silk", body=mahjong_body, words=2050, keywords=["mahjong necklace meaning", "mahjong tile jewellery", "mahjong necklace trend 2026", "tile pendant"]),
]


def write_pages() -> None:
    for item in ARTICLES:
        document = base.page(item["url"], item["seo"], item["title"], item["description"], item["deck"], item["department"], item["topic"], item["hero"], item["alt"], item["body"], "BlogPosting", item["words"], item["keywords"])
        destination = ROOT / item["url"].strip("/") / "index.html"
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(document, encoding="utf-8", newline="\n")
        print(f"Built {destination.relative_to(ROOT)}")


def update_catalogue() -> None:
    path = ROOT / "content/articles.json"
    current = json.loads(path.read_text(encoding="utf-8"))
    additions = []
    for item in ARTICLES:
        additions.append({
            "title": item["title"], "seoTitle": item["seo"], "department": item["department"].lower(),
            "topic": item["topic"].lower(), "published": PUBLISHED, "readingMinutes": round(item["words"] / 195),
            "readingWordsPerMinute": 195, "url": item["url"], "excerpt": html.unescape(item["deck"]),
            "metaDescription": item["description"],
            "image": {"webp": f'{item["hero"]}.webp', "fallback": f'{item["hero"]}.jpg', "alt": item["alt"], "width": 1536, "height": 1024},
            "articleSection": item["topic"], "breadcrumbTopic": True,
        })
    urls = {item["url"] for item in additions}
    path.write_text(json.dumps(additions + [item for item in current if item["url"] not in urls], ensure_ascii=False, indent=2) + "\n", encoding="utf-8", newline="\n")


def main() -> None:
    write_pages()
    update_catalogue()


if __name__ == "__main__":
    main()
